### ISSUE TITLE
An unexplained error occured - github app signin

### ISSUE THREAD

**Issue by rwendt-bw** [integrations/slack#1001]
Not really sure where to go on this . I've searched the issues here / been working with our IT department on this issue. The Github app is in our channel, I'm subscribed to our repos but when I perform a `/github signin` I receive the following error message:
```
An unexpected error occured. ref: bdd58197a83242af858e4a671c85c2ee
```
However I see the authorized app in my github settings.

![github_authorized_apps](https://user-images.githubusercontent.com/42274154/76810422-5ffeb380-67c4-11ea-9555-61e119f94721.png)
![channel](https://user-images.githubusercontent.com/42274154/76810431-6725c180-67c4-11ea-93d6-3156a4c86e50.png)

I don't see any commits from any repo I subscribe to.

**Comment by zmoazeni** [comment]
@rwendt-bw I think this may be an edge case with Slack Workspace apps. It's possible that the user who installed your slack app is no longer part of the slack workspace. 

I recommend having a slack admin for your workspace go to https://slack.github.com/ and click "Add to Slack" one more time to re-authorize it. Then give the `/github signin` a shot again.

Let me know if that fixes it or if you still have issues. ❤️

**Comment by rwendt-bw** [comment]
Sorry for the late reply.  The slack admin re-added the slack app to the workspace. After trying to sign in I'm still receiving a similar error message.

```An unexpected error occured. ref: bd2c504292244a97b31dd24ffb9d6259```

**Comment by rwendt-bw** [comment]
Going to open a ticket with Github Support

**Comment by zmoazeni** [comment]
I'm sorry that didn't resolve the problem. I do think a support ticket is the best option at this point. ❤️

**Comment by rwendt-bw** [comment]
So removing the app / reinstalling it would affect multiple teams so as a work around I created a public slack channel and it is working as expected. 

Thanks again.
