### ISSUE TITLE
Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.

### ISSUE THREAD

**Issue by rex-remind101** [integrations/slack#1007]
Getting
>Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.

 with the github app.

I read through https://github.com/integrations/slack/issues/559 and my issue is different. I do not get a 404 to add the app, the app is already added. While I was clicking around trying to set something up for my org I got some obscure jwt error and after that I've been getting the above error repeatedly. I basically can't control the Github app anymore. Please help.

**Comment by rex-remind101** [comment]
seems to have been fixed for me

**Comment by jaihanumann** [comment]
Don't install my app only 404 error or 405 error
