### ISSUE TITLE
Subscribe not working

### ISSUE THREAD

**Issue by personal-security** [integrations/slack#1009]
![image](https://user-images.githubusercontent.com/53793039/78869357-1f096000-7a4d-11ea-86cd-d90fd16f223c.png)
Command /github subscribe owner
All permission app have

**Comment by emilsivervik** [comment]
@personal-security I also stumbled upon this message and it seems that you have to provide the link to the org/repo that you wanna subscribe to. 

For instance `/github subscribe https://github.com/integrations/slack/`
