### ISSUE TITLE
Disable pull request reviewers? 

### ISSUE THREAD

**Issue by Pojahn-Netent** [integrations/slack#1017]
Currently the Github bot is a bit verbose mentioning the reviewers every time a pull request is open. 

I ran this command: `/github unsubscribe my-org/my-repo reviews`

And I got this response: 
```
This channel will get notifications from my-org/my-repo for:
issues, pulls, deployments, public, commits, releases
```

Yet whenever a new pull request is created, the bot writes the following:

```
Pull request opened by Pojahn-Netent
Pojahn-NetentPojahn-Netent
#56 Integration Environment
This is is the description
Reviewers
@user1, @user2, @user3, @user4, @user5, @user6
<https://url-to-repo.com | Today at 4:58 PM
Google Cloud Build: SummaryGoogle Cloud Build: Summary
```

How do I disable everything after the name of the pull request?

**Comment by tebriel** [comment]
@Pojahn-Netent Thanks for your issue, currently there is no way to customize the message as you're requesting. Removing `reviews` will only remove the notifications about `reviews` from the [pull request review webhook](https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent). Sorry that we don't currently have a way to accomplish what you're asking.

**Comment by Pojahn-Netent** [comment]
Thanks for the quick response.
