### ISSUE TITLE
Bug: "/github is not a valid command" with GitHub integration installed in old version of Slack

### ISSUE THREAD

**Issue by Brunox13** [integrations/slack#1019]
I have installed the GitHub integration in Slack but it is simply not working. I tried reinstalling the integration, but that didn't help. Any clues?

<img width="1145" alt="Screen Shot 2020-04-27 at 16 59 32" src="https://user-images.githubusercontent.com/45436070/80420309-8f670c80-88a8-11ea-9676-2a91770bbb5b.png">

**Comment by SandraFB** [comment]
You need to subscribe first. Write "Subscribed to integrations/slack"
![imagen](https://user-images.githubusercontent.com/8702594/80420734-dea93f00-88a0-11ea-80f5-eec6b7da024c.png)

**Comment by Brunox13** [comment]
> You need to subscribe first. Write "Subscribed to integrations/slack"
> ![imagen](https://user-images.githubusercontent.com/8702594/80420734-dea93f00-88a0-11ea-80f5-eec6b7da024c.png)

Do you mean that I need to use the following command
`/github subscribe organization/repository`
?

Any command with `/github`, such as the one above, or even `/github help` (which should work even without subscribing, afaik) produces the error in the title, "/github is not a valid command"

**Comment by SandraFB** [comment]
Yes, you could press the button in "About github" to init command:
![imagen](https://user-images.githubusercontent.com/8702594/80421258-d1408480-88a1-11ea-84fc-fc5a1895622f.png)

![imagen](https://user-images.githubusercontent.com/8702594/80421274-d7366580-88a1-11ea-83bd-c95248fe2a3c.png)

![imagen](https://user-images.githubusercontent.com/8702594/80421207-b9690080-88a1-11ea-83d1-efe38def2d5f.png)

**Comment by SandraFB** [comment]
I see. How are you using slack? I used https://app.slack.com to connect my github account as it's mentioned in [https://slack.com/intl/es-mx/help/articles/232289568-GitHub-para-Slack](https://slack.com/intl/es-mx/help/articles/232289568-GitHub-para-Slack)

**Comment by Brunox13** [comment]
> I see. How are you using slack? I used https://app.slack.com to connect my github account as it's mentioned in https://slack.com/intl/es-mx/help/articles/232289568-GitHub-para-Slack

I believe I did the same - also via the website.

**Comment by SandraFB** [comment]
What's your screen when you type "/"?
![imagen](https://user-images.githubusercontent.com/8702594/80424700-dc96ae80-88a7-11ea-951d-038b32904a82.png)

Could you type /git and wait if some suggestion appears?

**Comment by Brunox13** [comment]
Yes, I have tried that. Nothing appears when I type `/git`. This is what appears when I type `/gi`:
<img width="1145" alt="Screen Shot 2020-04-27 at 18 03 12" src="https://user-images.githubusercontent.com/45436070/80425310-66974500-88b1-11ea-8a48-9f84113a2b09.png">

**Comment by SandraFB** [comment]
Please, verify that you've installed the github app:
![imagen](https://user-images.githubusercontent.com/8702594/80425528-6bf09180-88a9-11ea-9662-6ddc49ee3507.png)

![imagen](https://user-images.githubusercontent.com/8702594/80425622-a35f3e00-88a9-11ea-9efd-cf3dcf4f1efc.png)

![imagen](https://user-images.githubusercontent.com/8702594/80425637-a9edb580-88a9-11ea-96d0-2efb419a0e65.png)

The github app must be installed in the slack space where you are trying to use:
![imagen](https://user-images.githubusercontent.com/8702594/80425655-b3771d80-88a9-11ea-90d2-512dddc3c416.png)

![imagen](https://user-images.githubusercontent.com/8702594/80425713-d3a6dc80-88a9-11ea-9820-47a3de94be8a.png)

You also need to select the channels.

![imagen](https://user-images.githubusercontent.com/8702594/80425824-0cdf4c80-88aa-11ea-9503-28e4265cf4c2.png)

Once you do this, you'll be able to use github as mentioned before: 

![imagen](https://user-images.githubusercontent.com/8702594/80425857-1d8fc280-88aa-11ea-9b6d-77f8098fd5d7.png)

**Comment by Brunox13** [comment]
Thanks to your instruction, I have found out that the workspace where I am getting this error, uses an old version of Slack, while from your screenshots, it seems that you are using the [new version of Slack](https://www.pocket-lint.com/apps/news/151493-new-slack-update-everything-new-in-the-major-redesign).

First of all, let me show you that I do, indeed, have the GitHub integration installed in this workspace (this looks different from yours because it is the **old version of Slack**):
<img width="1439" alt="Screen Shot 2020-04-28 at 09 15 13" src="https://user-images.githubusercontent.com/45436070/80491539-da2c6700-8930-11ea-9af9-ebecc1e22910.png">
And, like I showed in screenshots before, the integration is still not working:
<img width="1373" alt="Screen Shot 2020-04-28 at 09 18 27" src="https://user-images.githubusercontent.com/45436070/80492891-a2beba00-8932-11ea-867a-e771d10f269e.png">

However, I just tried to install the GitHub integration in a _different workspace_ that has already migrated to the **new version of Slack** and it _does work_:
<img width="1373" alt="Screen Shot 2020-04-28 at 09 21 27" src="https://user-images.githubusercontent.com/45436070/80492982-c1bd4c00-8932-11ea-8b27-13bb081c8e37.png">
<img width="1373" alt="Screen Shot 2020-04-28 at 09 20 46" src="https://user-images.githubusercontent.com/45436070/80492997-c8e45a00-8932-11ea-8f8f-44919748f6a4.png">

From this I conclude that the bug was caused by some error in the migration process - perhaps the GitHub integration has already been migrated to the new version and is therefore incompatible with the old version of Slack?

**Comment by SandraFB** [comment]
Hi Bruno, I'm glad this helps to solve your problem. About your question, it seems so.  Installing the new app will allow you to migrate subscriptions from legacy versions [https://slack.github.com/](https://slack.github.com/). You could close this issue now :)

**Comment by Brunox13** [comment]
It does not _solve_ the problem - it only helps to **explain** it.
I am stuck with the old version of Slack because the new version is being rolled out slowly and I cannot affect if/when I get it for that workspace. I cannot install some other/old version of the GitHub integration either, as far as I know.
And so until I get the new Slack version in that workspace, this will continue being an issue (a bug) and that is why I don't think it is appropriate to close this issue, until the issue is **resolved**. This bug still needs to be fixed because many workspaces out there still rely on the old version of Slack and may install (updated) integrations that seem to be no longer compatible with it.

**Comment by Brunox13** [comment]
**UPDATE:** The workspace in question has been updated to the new version of Slack today and **the integration is still not working**, despite uninstalling & installing it again. The bug must be caused by something else.
