### ISSUE TITLE
I think my Github account is connected to multiple Slack accounts in the same workspace, and I'm getting the wrong name on notifications

### ISSUE THREAD

**Issue by apaleslimghost** [integrations/slack#1021]
just over a year ago, i changed names¹. because of how my employer handles accounts, this required a new Slack account. now, i've set up Scheduled Reminders, but my Github username is being replaced by my deadname Slack account. i've tried running `/github signout`, but that hasn't worked, i'm guessing because it's not my current Slack account that's the issue. i have no access to the old account.

---
¹ i'm trans, and seeing my old name ("deadname") is really painful

**Comment by tebriel** [comment]
@apaleslimghost Thank you for reporting this, and I'm sorry that you're experiencing this issue. It looks like your name change came with a new Slack User ID. We're currently discussing how to resolve this for you, and then also starting discussions on how to mitigate in the future.

**Comment by jules2689** [comment]
Hi there,

Thank you for bringing this to our attention. First - I want to apologize for this mistake. There should never have been a situation on GitHub's platform or ecosystem where a deadname was shown to you. This is something we take seriously.

Here is how we will fix it:

First, we're looking at immediately changing the select query to use the _latest_ user we have in our database. This should result in your active Slack account being used.

Second, we're going to look at cleaning up the data and deleting the old user from the database. This should hopefully clear up any lingering issues.

Third, we're going to look at making sure a GitHub account can only be linked to one Slack user per Slack workspace. This should prevent the same issue from negatively impacting anyone else in the future.

If you have any questions, feel free to reach out here or through our support lines ❤️

**Comment by apaleslimghost** [comment]
this is incredible, thank you so much for resolving this @jules2689. i can confirm that it's fixed for me
