### ISSUE TITLE
/github deploy should have option to disable auto-merge

### ISSUE THREAD

**Issue by rikoe** [integrations/slack#1030]
![image](https://user-images.githubusercontent.com/3295115/82224731-22311f00-991c-11ea-8ec5-f84df1f1d063.png)

When I try to trigger a deployment from a tag or branch, it always tries to merge to master first. This is limiting, as I might want to deploy a different branch without merging to master first, or deploy a tag on a different branch.

I should be able to just specify a ref I want to deploy without a merge to master being forced on me.

**Comment by nimajalali** [comment]
This might explain #937
