### ISSUE TITLE
GH Slack integration vs Panda PullReminders

### ISSUE THREAD

**Issue by mhumeSF** [integrations/slack#1036]
Had been a user of Panda Pull reminders and switched over to this per GH recommendation. Excited about the native integration, but I've noticed the notifications are very spotty compared to what Panda had provided. Mentions in pull requests do not happen anymore. You have to subscribe to individual repos vs having org wide notifications. Is there something I am missing to better configure my notifications so I am not missing updates?

**Comment by gnumoksha** [comment]
I've the same issue. Also, I'm nothing receiving notifications for failed tests in Pull Requests.

The [README.md](https://github.com/integrations/slack#migrating-from-the-legacy-github-integration-for-slack) of this repository implies that migrating will have no issues.

**Comment by chenbobby** [comment]
@mhumeSF I never used Panda Pull reminders, but do you remember how more granular subscriptions were handled?

I might try submitting a PR, and knowing how Panda did it would give me a good starting point.

**Comment by mhumeSF** [comment]
Notifications that have are not working for me are:
- Someone comments on your PR
- Someone comments in a thread you're in
- You are mentioned in a comment
- Your team is assigned a review

I have these same settings turned on in Github as I had in PullReminders but again the behavior doesn't seem to work like it did.

**Comment by mhumeSF** [comment]
Issue on our end turned out to be wrong permissions in the org settings for notifications. This is now working as expected. 🥳
