### ISSUE TITLE
'An unexpected error occurred' when 

### ISSUE THREAD

**Issue by dpier** [integrations/slack#1051]
Successfully added GitHub to Slack and it is working fine in a private DM with the GitHub app.

I added GitHub to a Channel and when prompted to 'Connect GitHub account', I receive 'An unexpected error occurred'.

<img width="427" alt="Screen Shot 2020-07-17 at 9 58 43 AM" src="https://user-images.githubusercontent.com/51213295/87794185-4625b980-c814-11ea-9ff8-1001396a76a3.png">

<img width="680" alt="Screen Shot 2020-07-17 at 9 59 30 AM" src="https://user-images.githubusercontent.com/51213295/87794196-49b94080-c814-11ea-8590-045170c8e7a1.png">

When I click 'Connect GitHub Account' - I get the ''An unexpected error occurred' message

**Comment by dpier** [comment]
Working now

**Comment by mvlasovatl** [comment]
Have you found the cause of the error? I have the same problem right now.
