### ISSUE TITLE
Allow blacklisting of labels

### ISSUE THREAD

**Issue by pforrence-inquirer** [integrations/slack#1065]
We can currently whitelist labels, but I'd like to blacklist them so if a user DOESN'T want the automation to run they can NOT run on certain labels which they can mark manually.

**Comment by devpow112** [comment]
There was actual a PR opened for this months ago that never got merged
https://github.com/integrations/slack/pull/974
This would be an awesome feature to have

**Comment by kylechadha** [comment]
Very important feature to make the Slack integration useful for our team -- way too much noise from dependency PRs otherwise!

**Comment by pforrence-inquirer** [comment]
Thanks @devpow112 , I've left a comment there as well!

**Comment by pforrence-inquirer** [comment]
I may close this as a duplicate

**Comment by pforrence-inquirer** [comment]
This is a duplicate of #974, please merge 974!
