### ISSUE TITLE
Spammed with irrelivant notifications

### ISSUE THREAD

**Issue by guba-odudkin** [integrations/slack#1082]
Is there a way to set up messages/notifications the same way pull-panda used to work? 
So get notification is someone requests you review, or mentions you or replies to you. And nothing else.
Currently it seems to be all or nothing. It's either every single bit of activity in the repo or PRs only, no comments/responses. 
Is there a way to fix this, or some settings I missed?

**Comment by JoannaFalkowska** [comment]
@guba-odudkin It's really hidden, but you can change Slack notification settings on Github site: https://github.com/settings/reminders/[YourOrganization]
![image](https://user-images.githubusercontent.com/14551750/98228193-8bebc680-1f58-11eb-9c54-c033d4b041aa.png)

Then you can safely `/unsubscribe` in the Slack app.

**Comment by solares** [comment]
This isn't working for me after quite a few attempts. 

Can anyone explain the difference between "Reminders" and the `/github subscribe` functionality? They seem similar, but managed in totally different ways.

**Comment by solares** [comment]
OK now I understand. [https://github.com/settings/reminders](https://github.com/settings/reminders/%5BYourOrganization%5D) is **only** for PRs. Not for normal issues. 

Anyone know how to get notified in Slack when someone mentions you on an issue? Seems to be the most basic requirement.

**Comment by amitkumariiit** [comment]
Thanks @guba-odudkin for reaching out to us. Seems like this has been answered that you can achieve more control on PRs by scheduling real time alert from github.com side as mentioned in this comment https://github.com/integrations/slack/issues/1082#issuecomment-722283032

@solares there is already a feature request for @ mention https://github.com/integrations/slack/issues/1082#issuecomment-722283032 . We will track this feature from that issue. 
Closing this one.
