### ISSUE TITLE
How to get rid of the Github conversation?

### ISSUE THREAD

**Issue by PEZ** [integrations/slack#1102]
At work we have integrated Github nicely into some channels. It is super useful!

However, before we integrated it into the channels I had enabled GitHub integration in a private message conversation. I do not remember how I did it, and now I have no idea how to get rid of it. It's like a zombie. Badging my Slack as unread and driving me crazy. 😄 

<img width="311" alt="image" src="https://user-images.githubusercontent.com/30010/102464793-1a219500-404d-11eb-8626-3fde75577c63.png">

I am not even sure it is the same integration/plugin/bot as we have in the channels, so I do not dare disable any integrations at the team level.

Sorry if this is not the right place to ask this question, I'd be happy to be told where to ask it.

**Comment by mgriffin** [comment]
@PEZ Do you see this message in your Slack App, or in the web interface?

**Comment by PEZ** [comment]
It's in the Slack app. Both on iOS and on my Mac. Now checked in the browser and it ia there as well.

**Comment by mgriffin** [comment]
I'm guessing that you aren't able to click into it at all in any of the platforms, is that right?

**Comment by PEZ** [comment]
I can actually. It's a conversation.

**Comment by mgriffin** [comment]
I don't know what you've already tried, so please bear with me if you've already tried these things.

Are you able to mark the conversation as read?

Can you view any of the messages in the conversation?

Have you tried to delete the conversation itself? When I did this in a test location, it didn't delete the integration; that was left in place.

If you've already tried all these things, maybe Slack support might be able to give you other ideas to try out?

**Comment by PEZ** [comment]
I'm just so happy you are trying to help me with this. ❤️ 

I can mark the convo as read and I can read the messages there. I've deleted the conversation but it keeps resurrecting. 

I've reached out to Slack support now. Will update this issue if I learn anything about this.

**Comment by PEZ** [comment]
Hello again. I got this reply from Slack support:

> I'm just checking back with you about the issue you had reported where the GitHub app was sending an unread badge for messages.
>
> After taking a closer look, this appears to be coming from the GitHub workspace app which was actually directly by the GitHub team. Therefore, if you want to stop the notifications entirely, you'll need to contact them to find out how to do that.

It doesn't tell me very much, but maybe someone here know what should be my next step?

**Comment by mgriffin** [comment]
> GitHub workspace app

I wonder what they meant by this?

I think that it might be best to open a support ticket with us, so that we can get a few more details from you and see if we can get to the bottom of it. Would you be able to do that?

**Comment by PEZ** [comment]
Yes, where would I open that ticket?

**Comment by amitkumariiit** [comment]
Hi @PEZ , Thanks for reaching out to us. 
What I understood is that you have added the @GitHub app in you private conversation and you are getting the notifications over there and you want to get rid of these notifications.
If this is the case, you can do following. 
1. Remove the subscriptions created.  First check what all subscription you have created by running command `/github subscribe list` in you private conversation. This will list the subscriptions.
2. Then run the unsubscribe command one by one to remove the subscription like `/github unsubscribe {repo copied pasted from above command output}

Once you remove all the subscriptions, github won't post any notifications on this conversation.
Something like 
![image](https://user-images.githubusercontent.com/9694413/105345484-532fc500-5c0a-11eb-89ca-72561517c10e.png)

Please let us know if it works for you.

**Comment by PEZ** [comment]
OMG, @amitkumariiit , I think this actually works! I do not dare to call it done just yet, but the bot did answer that it had unsubscribed me.

I don't know what the Slack API allows, but maybe the app should suggest this when a user deletes the conversation?

**Comment by amitkumariiit** [comment]
Happy to see that it worked for you. Thanks @PEZ for the confirmation and reaching out to us. I am closing the ticket now. Keep raising concerns.
