### ISSUE TITLE
Unsubscribing after repository ownership change is impossible

### ISSUE THREAD

**Issue by cfra** [integrations/slack#1105]
We had a repository in our GitHub organization that was moved to a user, because our organization handed over maintenance.

The subscription in Slack automatically updated to point to the repository of the user.

Trying to unsubscribe, I get:

```
Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
Note: You will need to ask the owner of the repository to install it for you. Give them this link.
```

This obviously doesn't make sense. Unsubscribing from the old subscription should be possible, even if the new owner doesn't have the app installed.

**Comment by mgriffin** [comment]
@cfra Can you open a ticket with GitHub Support with the details and I can see about getting this removed for you? Feel free to mention me and this issue when you open the ticket.

**Comment by amitkumariiit** [comment]
support ticket seems to be closed. Closing this ticket from here. @cfra feel free to re-open this or to reach to us via support.
