### ISSUE TITLE
Unable to logout of github integration

### ISSUE THREAD

**Issue by duane-at-cosell** [integrations/slack#1110]
I changed github accounts recently and, unfortunately, I can't update my github integration from slack—there's no way to invalidate the current set of authorized credentials and re-associate with github.

Any advice, or improvements to the integration, would be appreciated.

**Comment by amitkumariiit** [comment]
Hi @duane-at-cosell , 
Thanks for reaching out to us. Can you please tell us more what happening if you run `/github signout` command. Ideally it should sign you out and after that you can again run the `/github signin` command to signin. 
Please note that on signing out your subscription gets deleted and you need to re-subscribe.

**Comment by duane-at-cosell** [comment]
Worked like a charm. FWIW I tried '/github logout', so it might be worth
implementing the same thing for that command.

**Comment by amitkumariiit** [comment]
Happy to see that solution worked for you and you are unblocked. Thanks @duane-at-cosell 
I am closing this ticket.
