### ISSUE TITLE
Github Repo Is Automatically Removed From The Subscription List

### ISSUE THREAD

**Issue by mguttsait** [integrations/slack#1132]
Hello all,

I have been trying to integrate the GitHub app to my slack workspace. We had it working before for a LONG time, but about a week ago, we stopped receiving notifications and when I re-subscribe, it still does not work. 

I have tried creating a new private channel and successfully added the GH user to the channel. I am successfully able to subscribe to one of my repos, but I still get no notifications..

When I subscribe and add the features that I would like to the command, ex: `/github subscribe x/x reviews comments branches commits:all`, I see the repo in the subscribe list.. But when I go to test it out by leaving a comment on one of our PR's, we get no notification and the repo is removed from the list... Issuing a `/github subscribe list` after subscribing shows the repo.. But then when I leave a comment on a PR, the repo is no longer in the subscribe list - it's as if it is being removed once I leave a comment.

Anyone facing similar issues?

**Comment by luoxiu** [comment]
same

**Comment by Alpenglow88** [comment]
Same

**Comment by biennh** [comment]
I'm facing the same issue. Is there any update on this issue?

**Comment by derekjkeller** [comment]
Same thing happens for me.

**Comment by m8ow** [comment]
I faced same error.

My research is below
1. I uninstalled Github App in Slack, and re-installing wouldn't solve this problem
2. some repos work, but other repos don't work
3. new repos don't work (in my case, since March 28th 2021)

**Comment by mguttsait** [comment]
All,

We finally got it working.

We added the GitHub app to Slack about 3 years ago, so we decided to "start over":

1. Delete GitHub App from Slack 
2. Re-Add
3. Re-Enable
4. Voila 

I'm not sure if this will work for others, but it helped us.. 

Cheers.
