### ISSUE TITLE
[feature request] Message shortcut: open a new issue from Slack message

### ISSUE THREAD

**Issue by quezak** [integrations/slack#1137]
There already is a message shortcut to comment on an issue.

It would be cool to have another one to create a new issue from a Slack message.
It could open the same dialog that `/github open` does, and prefill the `Body` section with `Created from [Slack message](<message link>)` followed by the message text.

**Comment by brianamarie** [comment]
➕ Plus one! I would really like to have the ability to emoji react to a slack message, then have it automatically open an issue OR open a PR, appending the message to a certain doc in a repo based on the emoji used. 

This would be especially useful for information shared ad-hoc or casually, that could provide more and broader value if maintained in an evergreen place. Additionally, I believe this use case extends beyond GitHub, as many teams at many companies use Slack regularly, but don't necessarily have eternal message retention. 

Relevant: [Slack docs on emoji response as trigger](https://slack.com/intl/en-nl/help/articles/360053571454-Set-up-a-workflow-in-Slack#h_01EJVP297CA3B1MDG83WJANMEQ)

**Comment by jphorn** [comment]
Duplicate #973

**Comment by quezak** [comment]
Didn't find those back when I posted 😕  All right, closing this one
