### ISSUE TITLE
Why is the GitHub Slack app labeled `(Legacy)`?

### ISSUE THREAD

**Issue by arielkirkwood** [integrations/slack#1147]

**Comment by jamesonhill** [comment]
+1

**Comment by jalaziz** [comment]
Maybe because `Scheduled Reminders` replace some of the features? However, this app is still useful and I'm pretty sure Scheduled Reminders uses to handle personal notifications anyway...

**Comment by ghirsch1** [comment]
My `Scheduled Reminders` messages are also coming from `GitHub (Legacy)` though

**Comment by IchordeDionysos** [comment]
It also does not show up when you search for "Github" in the Slack app directory:
https://thesimpleclub.slack.com/apps/search?q=github

**Comment by jalaziz** [comment]
> It also does not show up when you search for "Github" in the Slack app directory:
> https://thesimpleclub.slack.com/apps/search?q=github

Seems like installing from https://slack.github.com/ still works though.

**Comment by bobeagan** [comment]
They are getting ready to replace it, see https://github.com/integrations/slack/compare/ashokirla-slack-migration

**Comment by MeredithAnya** [comment]
☠️   death to all workspace apps☠️

**Comment by yutachaos** [comment]
https://github.com/integrations/slack/pull/1141
It seems to merge.

**Comment by smemsh** [comment]
perhaps this section from the readme is relevant:
https://github.com/integrations/slack#moving-away-from-the-legacy-workspace-app-model-in-slack

**Comment by darryn02** [comment]
Looks like they pushed the replacement. All is right with the world again.

**Comment by dral3x** [comment]
> By installing the new GitHub app from the Marketplace or click on the install link here. We will automatically detect and update the old app and migrate your subscriptions.

Maybe it's just me, but when I try to install the new app, it says that the legacy one is already installed and it does NOT install/upgrade it. So that of the guide is not correct.
Should I remove the old one?

**Comment by jalaziz** [comment]
> > By installing the new GitHub app from the Marketplace or click on the install link here. We will automatically detect and update the old app and migrate your subscriptions.
> 
> Maybe it's just me, but when I try to install the new app, it says that the legacy one is already installed and it does NOT install/upgrade it. So the guide is not correct.
> Should I remove the old one?

Hmm, it worked fine for me. I went to https://slack.github.com/, clicked install and it said it was migrating to the new app. I got Slack notifications from the Github app to tell me the migration was complete.

**Comment by torbjornvatn** [comment]
Seems like the `/github deploy` command has disappeared 👻 

I use it a lot, so that's a real bummer if it's permanent

**Comment by dral3x** [comment]
I tried a second time, 15 minutes later, and now the upgrade process worked 😅
Thanks @jalaziz

**Comment by iorlas** [comment]
> Seems like the `/github deploy` command has disappeared 👻

The deployment events notifications have disappeared as well. Zero information about this topic in the migration readme file...  We have relied on it. Considering the fact the long-time-awaited feature "environments control" is released as a "public repo or enterprise only", I think we can expect the CD portion of the GH Actions to be fully moved in this direction.

We are considering switching to another vendor right now :(

**Comment by torbjornvatn** [comment]
Got an answer from Github in #1150 🙁

**Comment by ashokirla** [comment]
Answering some of the questions posted above:

Why is the GitHub Slack app labeled (Legacy)?
Slack has moved to new app model and we need to move our app. More details can be found [here].

When did this change happen?
The old app is renamed to legacy and new app is rolled out on April,14 9 PM PST. 

Is there any change to the app?
No change to the way the App works. You just need to take couple of steps to upgrade and our App guides you through the process. However, we have made few minor changes to the app:
- Sign in flow now has MFA with verification code. This is to enhance the security for signin flow.
- Added additional branch filters support for commit notifications.
- Removed deploy command support. Current deploy command functionality is very limited and the adoption is very low. We are working on Actions CD integration. We will relook at the deploy scenarios and build a holistic experience.



We apologize for the inconvenience. We are taking a relook at the deploy functionality as the current experience is limited and doesn't address all the scenarios and we see very little adoption. We have removed deploy command support as part of the new version. We will evaluate the feedback and then build a holistic experience that customers need.

It would be great if you can share your scenarios/requirements around deploy.

**Comment by Minho-Lee** [comment]
> Answering some of the questions posted above:
> 
> Why is the GitHub Slack app labeled (Legacy)?
> Slack has moved to new app model and we need to move our app. More details can be found [here].

Seems like you missed the link for `here`? I only see a plaintext.

**Comment by jamesnicolas** [comment]
After we upgraded, I'm getting `/github failed with the error "no_permission"` and this isn't in a private channel. Any ideas what could be happening?

**Comment by ashokirla** [comment]
@jamesnicolas Did you get upgrade successful message. Can you share a snapshot.

**Comment by jamesnicolas** [comment]
> @jamesnicolas Did you get upgrade successful message. Can you share a snapshot.

Never mind, someone readded the legacy app which broke it, but I ran upgrade again and it seems to be working. Although the slash command suggestion doesn't show up, the commands work.

**Comment by schmod** [comment]
Can I recommend adding a note about this transition to https://slack.github.com/ or the page for the Slack Directory listing for the legacy integration?  

It was momentarily disorienting to see the new name without any explanation of what happened.

**Comment by arielkirkwood** [comment]
Lots of great comments here! My question is answered, so I'm closing.

**Comment by 0xdevalias** [comment]
It looks like we also lost the 'message shortcut' that we used to be able to use to share slack messages to GitHub issues?
