### ISSUE TITLE
Even after installation, new bot in private channels reports `app_not_installed_on_team`

### ISSUE THREAD

**Issue by bethac07** [integrations/slack#1154]
We had several GitHub-bot private channels get the upgrade message this morning, we invited the new bot, but now `/github` messages  in those channels fail with `app_not_installed_on_team`

![image](https://user-images.githubusercontent.com/6721515/114875932-cdb44f00-9dcb-11eb-8062-c9fb6a80227d.png)

I tried going through the install process, which said it completed, kicked and re-invited the bot, no effect on the behavior.

![image](https://user-images.githubusercontent.com/6721515/114876861-bc1f7700-9dcc-11eb-98e1-646b7d21d330.png)

I suspect it didn't actually fully install though, despite the message implying that it did, because when I try to do `/github help` I get an `invalid_user` message

![image](https://user-images.githubusercontent.com/6721515/114877004-e113ea00-9dcc-11eb-9887-42694e03981c.png)

**Comment by bethac07** [comment]
Our Slack admin was able to solve this, posting the solution here in case anyone else runs across it:

>We have 6 workspaces that had the github app (legacy) installed and I had to do the upgrade on all of them.

>once I completed the last one and then we only had the new GitHub app installed and no instances of the GitHub (legacy) app then the /slash commands started working

**Comment by cmark** [comment]
@bethac07 That was exactly the case in our system as well, had to remove all Legacy integrations. I have almost sent my comment before yours showed up 😅. Thank you for sharing.

**Comment by sfdc-slumos** [comment]
We have many workspaces with many admins. I can't force them to upgrade. Any other way I can get unstuck?

**Comment by chrisr345** [comment]
Hi there! Experiencing the same issue - many workspaces in an enterprise grid, so it's a bit difficult to get everyone to update. Any workarounds would be appreciated!

**Comment by amitkumariiit** [comment]
> Hi there! Experiencing the same issue - many workspaces in an enterprise grid, so it's a bit difficult to get everyone to update. Any workarounds would be appreciated!

Hey currently we don't have any workaround other than updating the app in all shared workspaces for a channel.
In future we are planning to add support for org-wide installation which would help admins to install app in multiple workspace in on go.

**Comment by amothic** [comment]
We are using github and github enterprise server together, so we can't update all apps
