### ISSUE TITLE
Duplicated notifications on a release but notifications for commits are fine.

### ISSUE THREAD

**Issue by oneseedfruit** [integrations/slack#1155]
![Screenshot_2021-04-15_21-32-06](https://user-images.githubusercontent.com/5054104/114877911-52d24f00-9e32-11eb-8a86-2c76b4b0bc99.png)

**Comment by sushmita-m** [comment]
@oneseedfruit if you are still facing this issue can you please let us know.
Was your channel shared between multiple workspaces anytime in the past?

**Comment by oneseedfruit** [comment]
@sushmita-m sorry, I haven't been facing this issue for a while (as I have not made any releases with my own GitHub account since then). 

Also, it only happened in the same channel when it did happen, but only with my GitHub account. This did not happen with one other GitHub account in the same repo when it was used to make a release, and it did not happen in all the other channels in the same workspace.

And nope, my channel wasn't shared between multiple workspaces.

**Comment by sushmita-m** [comment]
There are no other reported issues similar to this.
I looked in the logs and we haven't identified any bug in the code.
I am closing this issue for now. @oneseedfruit  please reopen this, if you run into this again.
