### ISSUE TITLE
GitHub avatar is gray in the new version after upgrade

### ISSUE THREAD

**Issue by cmark** [integrations/slack#1157]
We did the upgrade to the new version today, but none of our subscriptions worked anymore and still showed the (Legacy) suffix. We have removed all GH integration and redone the entire configuration process, the messages are now arriving with the correct header, but GitHub's avatar icon before the repository link is still light gray.

![image](https://user-images.githubusercontent.com/1174527/114900512-37584b80-9e14-11eb-957a-cfdfdbbf2940.png)

**Comment by ashokirla** [comment]
@cmark It is expected change to make it visible in all the themes of Slack.

**Comment by cmark** [comment]
Hmm, I see, but it looks a bit weird in the light version to use a light gray color on top of a light background. 
Not sure if it is possible to achieve, but if it is, may I suggest using the darker, original avatar on light Slack themes and this new light icon in the darker themes?

**Comment by ashokirla** [comment]
Since the interaction is based on the theme of the Slack, it is not a simple fix. We will add this request but it is not a priority one for us to work on.

**Comment by ashokirla** [comment]
Closing this issue as it is not a priority at the moment.
