### ISSUE TITLE
Pasting a link produces a prompt to install "GitHub (Legacy)"

### ISSUE THREAD

**Issue by schmod** [integrations/slack#1160]
After upgrading to the new version of the Slack integration, link-previews no longer expand when we paste them into a channel.  

Instead, we get a prompt to reinstall the old integration:

> That looks like a GitHub (Legacy) link. Would you like to install the GitHub (Legacy) app from the Slack App Directory?

<img width="555" alt="Screen Shot 2021-04-15 at 1 28 52 PM" src="https://user-images.githubusercontent.com/1102667/114913011-acb12580-9dee-11eb-8214-ba67b2bdf6c6.png">

**Comment by ashokirla** [comment]
@schmod We apologize for the inconvenience caused. This is an issue with the Slack platform. We are working closely with Slack org to get this issue addressed ASAP.

**Comment by amitkumariiit** [comment]
There was an issue in the slack platform which there have fixed. It should not be coming now.
@schmod can you please verify and close the ticket.

**Comment by schmod** [comment]
We're no longer getting prompts to install the legacy app, but we're also not getting any link previews.

**Comment by sjackman** [comment]
I'm getting link previews duplicated! I see them twice.
@schmod I can give you my extra link preview, Andrew. I don't need two.

**Comment by sushmita-m** [comment]
closing this as user is no longer prompted to install GitHub(Legacy) app on pasting an URL.
