### ISSUE TITLE
Command fails with "invalid_user" (private org)

### ISSUE THREAD

**Issue by jakeatoms** [integrations/slack#1161]
Hi, our Slack org just installed the new app, but `/github` fails with `invalid_user`. We have a private GitHub organization, so I suspect when it was installed, either credentials were omitted or the wrong ones were used. How do I go about updating the app with a valid user?

**Comment by ashokirla** [comment]
@jakeatoms We regret the inconvenience. Can you let us know if you are facing this experience in private/public channel or in the GitHub app chat. If it is a private channel, can you try inviting the app again using `/invite @ github`

If not, can you share a snapshot of the issue.

**Comment by gmarinov** [comment]
> Can you let us know if you are facing this experience in private/public channel or in the GitHub app chat. If it is a private channel, can you try inviting the app again using `/invite @ github`

I get this in a private chat to the app itself - @ GitHub, under Apps in the sidebar. 
- In the chat itself it says "You've successfully installed GitHub on this Slack workspace"
- when I try `/github subscribe list` in that same channel, it says "/github failed with the error 'invalid_user'"
- if I `/invite @GitHub`, it replies that "@ GitHub is already in this channel".

**Comment by jakeatoms** [comment]
> @jakeatoms We regret the inconvenience. Can you let us know if you are facing this experience in private/public channel or in the GitHub app chat. If it is a private channel, can you try inviting the app again using `/invite @ github`
> 
> If not, can you share a snapshot of the issue.

This is in all public channels. I have successfully invited the GitHub app, but attempting any command results in the following:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/3605966/115242815-411dcf80-a0f0-11eb-8e89-44ed5f9b5a6c.png">

**Comment by cwardgar** [comment]
I'm seeing the same behavior, also in a private GitHub organization. I'm not getting any notifications in the GitHub app channel about git activity.

I also created a new channel and invited @GitHub too it. But I'm not getting any notifications there either.

**Comment by apurva1112** [comment]
Hi @jakeatoms , we need more information from your side to debug and fix this. Please open a support ticket on  https://support.github.com/contact .

**Comment by apurva1112** [comment]
> I'm seeing the same behavior, also in a private GitHub organization. I'm not getting any notifications in the GitHub app channel about git activity.
> 
> I also created a new channel and invited @github too it. But I'm not getting any notifications there either.

@cwardgar are you on the slack enterprise grid?
On Enterprise Grid, If the user upgrades the app from one workspace and not from others, he can face these errors. Please upgrade the GitHub app on all the workspaces of slack enterprise grid. This would be needed to be done by the admin of the grid.

**Comment by jakeatoms** [comment]
@apurva1112 upgrading it in all the enterprise workspaces resolved the issue. Thanks!

**Comment by apurva1112** [comment]
Thanks @jakeatoms for your response. Closing this as your issue is fixed.
