### ISSUE TITLE
Failed to subscribe repositories with a `public` feature

### ISSUE THREAD

**Issue by pataiji** [integrations/slack#1162]
I sent this command referring to [the document](https://github.com/integrations/slack/blob/e59c6361dca1f559d1308d8cc97c87fa7b0f1154/README.md#configuration).
 
```
/github subscribe org/repo public
```

Then I got an error message.
```
Uh oh! public is not a feature. Available features are:
issues, pulls, releases, +label:"my label"
```

**Comment by amitkumariiit** [comment]
Thanks for raising this @pataiji . You would have by default subscribed for `public` but its true that when running the command it should show error.

@apurva1112 can you take a look

**Comment by apurva1112** [comment]
@pataiji we have made `public` as a default feature and do not provide the option to enable/ disable it from subscriptions.  We are working on updating this in the document as well.

**Comment by apurva1112** [comment]
We have updated the readme document. @pataiji please find the latest information on what changed after upgrade [here](https://github.com/integrations/slack/blob/master/README.md#3-what-changes-after-the-upgrade).

Closing this issue as no more action is required on this.

**Comment by pataiji** [comment]
Thank you!!
