### ISSUE TITLE
Upgrade & onboarding of the new GitHub+Slack app is easy to conflate with GitHub core "scheduled reminders/ real-time alerts" feature, causing undesired usage deemed too noisy

### ISSUE THREAD

**Issue by ronjouch** [integrations/slack#1171]
Hi.

On 2021-04-16 I was migrated to your new Slack GitHub app.

I was super happy with the old app, it provided me with the right amount of notifications, on the PRs & issues activity relevant to me, but not more (see later for what I mean by "relevant to me, but not more").

I'm extremely unhappy with the new app, because it overwhelms me with a zillion notifications about everything happening in my org regardless of my involvement in the PR/issue, and your documentation at https://github.com/integrations/slack doesn't mention a way to configure this. Sure, you provide `/github (un)subscribe owner/repo reviews|comments|...`, but I do _not_ want to unsubscribe to repos for which I'm receiving unrelated notifications! Because sometimes, in these repos, I'm the author, or a reviewer, or sometimes people @ mention me. In all these cases, binarily unsubscribing will cause me to miss relevant activity!

→ How do I express to your new app to notify me _**only about activity that is relevant to me**_? (like the old app was doing!). By "activity that is relevant to me", I mean:

1. @mentions to me
2. PR (re-)requests for review
3. Comments on issues I've commented on
4. Comments on PR threads I've commented on
5. Comments on PRs I'm the author
6. Comments on PRs I'm a reviewer

Am I missing something? How do I make your Slack app usable again, or how do I revert to the old app?

Thanks.

**Comment by Niaro** [comment]
@ronjouch we could do this on the old one??? Bummer I didn't know)

**Comment by sushmita-m** [comment]
@ronjouch I think what you are referring to is [scheduled reminders/ real-time alerts](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-scheduled-reminders). With the upgrade, the support is still there and we haven't taken away these features.

**Comment by ronjouch** [comment]
> @ronjouch I think what you are referring to is [scheduled reminders/ real-time alerts](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-scheduled-reminders). With the upgrade, the support is still there and we haven't taken away these features.

@sushmita-m thanks, I confirm. That's what I've been noticing too since I filed the issue, but I wanted confirmation from you here (to validate that I wasn't in some sort of limbo with a deprecated tool still active in my account).

So, if I understand correctly,

1. A long time ago, I used to use Pull Reminders
2. Pull Reminders was acquired by GitHub, merged into GitHub core as [scheduled reminders/ real-time alerts](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-scheduled-reminders), and the Slackbot was renamed to `GitHub`
3. Recently, the `GitHub` bot became `GitHub (Legacy)`
4. This prompted me to upgrade
5. As I upgraded the Slack app, I followed the new `GitHub` bot's onboarding, suggesting to subscribe to activity

→ I did so, failing to understand that this subscribing was *not* the [scheduled reminders/ real-time alerts](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-your-scheduled-reminders) feature I was using (I was *adding* something else).

→ Confusion.

Looking around me and at the number of upvotes on the issue, many users are confused like I was, and conflating both tools. Maybe you can take this as a hint that things aren't super clear now, and that you could better communicate on each tool's differences, by explicitly laying out what each tool does and how they are complementary.

Renaming the issue to suggest improving this, and leaving it open.

**Comment by sushmita-m** [comment]
@ronjouch ❤️ for renaming the issue.
@ashokirla looping you in to take a note of the above comment.
