### ISSUE TITLE
Not getting notifications after updating to new app

### ISSUE THREAD

**Issue by vaibhav-sharechat** [integrations/slack#1172]
I have stopped receiving notifications after updating the app. I have tried unsubscribing and subscribing again the repo but of no use. Even when I subscribe to organisation I am not receiving notification of some repositories. 
Please help, how can I solve this.
Thanks

**Comment by sushmita-m** [comment]
Is the org that you are trying to subscribe under SAML by any chance? If so, can you do a `\github sigin` once and authorize the repo under SAML during the signin process.

**Comment by vaibhav-sharechat** [comment]
@sushmita-m yes the org is under SAML. I have tried the signin but it still didn't work. I am getting other repo notifications but not of those repos which I had subscribe in the earlier github integration of slack. After moving to this new integration I am not getting the notifications of those repos.

**Comment by sushmita-m** [comment]
Just to be clear once again:
Are you receiving notifications for newly created repos under the org which has SAML enabled? Are the notifications not working only for the migrated subscriptions under this org?

**Comment by vaibhav-sharechat** [comment]
@sushmita-m Yes I am getting notifications of newly created subscriptions post upgrade, but notifications not working for the migrated subscriptions. I have tried to unsubscribe and subscribe again but that also didn't work for those repos

**Comment by sushmita-m** [comment]
I can see from one of our logs that one of your repo is running into a SAML related error. It should be easily resolved. Can you get the person who originally set-up these subscriptions to follow the below steps. In case you are not or can't identify the person who subscribed in the first place.. can you do a unsubscribe and finish below steps before subscribing again.

1. Go to your slack workspace where the app is installed and give `\github signin` command
2. On clicking Connect GitHub account button you will be redirect to a url, in the process of completing the signin in your browser you will see a window similar to 
![image](https://user-images.githubusercontent.com/63236940/115205280-04b19a00-a117-11eb-83ec-d4c5b8d832e0.png)
Click on authorize for your organization and finish the signin process.
3. In case you are not seeing the above authorize window, finish the process by copying the signin url from the browser to a incognito browser window.

Please bear with us while we help you resolve your issue.

**Comment by vaibhav-sharechat** [comment]
@sushmita-m I did the above steps:
- Unsubscribed the repo
- Did github signin, this page didn't come so used incognito. This page came did my SAML and auhorized this
- Subscribed again

Still no notifications. Is it possible to check the logs to see if I missed some step ?

**Comment by Ariakas** [comment]
+1.
Getting only pull request notifications but not pushes.

**Comment by sushmita-m** [comment]
@vaibhav-sharechat sorry for the late reply. We recently fixed a issue in the notification flow. Are you still facing issues with the notifications?

**Comment by vaibhav-sharechat** [comment]
@sushmita-m sorry for the late reply. Yes notifications are working now, Thank you so much 🙂

**Comment by sushmita-m** [comment]
@Ariakas  Hoping notifications are working for you as well. You can log a new issue with us if you are facing issues.
