### ISSUE TITLE
"Please check to make sure the spelling of the resource was correct and that you have access to the resource in GitHub."

### ISSUE THREAD

**Issue by hyeon1520** [integrations/slack#1173]
I used '/github subscribe username/repository' to link my GitHub repository to Slack.
But there's only the error 
"Could not find resource _myname_/_my repositories_.
Please check to make sure the spelling of the resource was correct and that you have access to the resource in GitHub.".
What's the problem?

**Comment by sushmita-m** [comment]
@hyeon1520, thank you for logging this.

1. Is it a private repo that you are trying to access? Do you have access to it?
2. Is the org under which the repo is protected by SAML? 
If it is under SAML, can you do a `\github signin` command once again and authorize the org this time during the signin process?

**Comment by sushmita-m** [comment]
@hyeon1520 are you still seeing this issue?

**Comment by sushmita-m** [comment]
@hyeon1520  please reopen the issue if you are still facing any issues.
