### ISSUE TITLE
Subscribing to specific branches fails with "commits:<branch> is not a valid argument."

### ISSUE THREAD

**Issue by TimWolla** [integrations/slack#1176]
I'm attempting to subscribe a specific branch of one repository using:

```
/github subscribe myorg/repo commits:X.Y
```

X.Y represents a version number in the format `1.0`. This command fails with:

> commits:X.Y is not a valid argument. Learn more about commit filters here

According to the documentation this should be a valid command:

> /github subscribe org/repo commits:myBranch for commit notifications from a specific branch.

Am I doing something incorrectly or is this a bug?

**Comment by ashokirla** [comment]
Is X.Y the name of the branch. Can you pass the branch name enclosed in quotes.

**Comment by TimWolla** [comment]
> Is X.Y the name of the branch.

To be clear: X and Y are a single digit each.

> Can you pass the branch name enclosed in quotes.

I attempted the following:

> commits:X.Y is not a valid argument. Learn more about commit filters here

> commits:'X.Y' is not a valid argument. Learn more about commit filters here

> commits:"X.Y" is not a valid argument. Learn more about commit filters here

> Uh oh! 'commits:X.Y' is not a feature. Available features are:

**Comment by sushmita-m** [comment]
@TimWolla `.` in branch name is not accepted with the commits feature. I will mark this as a feature request. 
The next best alternative I have for you is:  you can subscribe with `github subscribe owner/repo commits:X*`

What this does is.. you will receive notifications for all the commits on branches that starts with `X`

**Comment by TimWolla** [comment]
>  The next best alternative I have for you is: you can subscribe with `github subscribe owner/repo commits:X*`

Thanks, that'll work for me for the time being.

**Comment by sushmita-m** [comment]
@ashokirla marked this as a feature request. Right now `.` is not allowed in the branch name for commits feature.
Something like `github subscribe owner/repo commits:1.2`

**Comment by sushmita-m** [comment]
Closing the issue as the user is unblocked.
