### ISSUE TITLE
Not possible to subscribe to repository after Github account change 

### ISSUE THREAD

**Issue by kijewskimateusz** [integrations/slack#1178]
Hello Team,

Recently I've been migrating my Github accounts into one and after update, I can see no notifications on subscribed actions.  
Whenever I'm trying to subscribe to my organization, I'm seeing an error message of: 
![image](https://user-images.githubusercontent.com/65126185/115398211-35f99b00-a1e7-11eb-9ff0-5c058aad7ad7.png)
I've checked on Org settings and Github integration does not show too. 

Is it possible that organization integration will not work as I'm using my personal email address, not attached to used by Organization @ Slack?

**Comment by kijewskimateusz** [comment]
Attaching screenshot of Organization's Integrations Tab
![image](https://user-images.githubusercontent.com/65126185/115399489-90472b80-a1e8-11eb-869b-482a3381b1de.png)

**Comment by sushmita-m** [comment]
@kijewskimateusz can you do a `\github signin` command once and before trying the subscribe command.

The email you used to login to GitHub during the signin process should have access to the org.

**Comment by kijewskimateusz** [comment]
Yeah, it worked like a charm, You're legendary!
![image](https://user-images.githubusercontent.com/65126185/115443304-5f302080-a213-11eb-8ef6-007a6f58cade.png)
