### ISSUE TITLE
Cannot identify content in notification pop-ups

### ISSUE THREAD

**Issue by kerukukku1** [integrations/slack#1180]
When we had legacy notifications, we could tell if it was a comment or an Approve, but now notifications can't do that.

`Review On # `
You can't get any information from the Please improve it.

**Comment by apurva1112** [comment]
Hello @kerukukku1 , thanks for logging the issue. We need some more information on this. Please let us know for which notifications are you facing problems in pop-ups text.

**Comment by sushmita-m** [comment]
@kerukukku1 we have updated the review notifications to be more meaningful. Thank you for logging this :)
