### ISSUE TITLE
Incorrect username in push message

### ISSUE THREAD

**Issue by hdodov** [integrations/slack#1181]
The new GitHub app correctly sends a message:

> **1 new commit pushed to {{ branch }} by hdodov**

…except I'm not the one pushing. This happens when someone else pushes a commit via PHP plugin for Git. Is it possible that my username was stored somewhere on the server when I was setting that PHP plugin and that's causing the problem? How does the slack app determine who pushed a commit?

**Comment by sushmita-m** [comment]
We are getting the details from the webhook triggered after the push. The username shown is sender.login from https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#push

Does that answer your question?

**Comment by hdodov** [comment]
No, because the docs you sent only say this about `sender`:

>The user that triggered the event.

It seems that the slack app displays the incorrect user because the webhook sends the incorrect one. So how is the _webhook user_ determined? But that's out of the scope if this repo, I assume…

**Comment by sushmita-m** [comment]
@hdodov sorry for the late reply. This seems like a good place to ask the question about webhooks - https://github.community/c/github-ecosystem/webhooks/62

I am closing this issue for now.
