### ISSUE TITLE
Can not get GH notifications through direct messages anymore

### ISSUE THREAD

**Issue by nezriffic** [integrations/slack#1183]
I used to use @myname to get various notifications from GH.
Now - it is not possible anymore OR I don't know how to re-enable it.

When trying to list my subscriptions (/github subscribe list) I get:
> Unable to list subscriptions. You need to invite @GitHub to this conversation to run this command. /invite @GitHub

When trying to invite GitHub (/invite @GitHub or /invite @GitHub @myname) I get:
> A valid channel name is required.

**Comment by apurva1112** [comment]
Hi @nezriffic ,
You should be able to get the notifications properly after migration. As I understand from the title of the issue, you mentioned `direct messages`, are you referring to personal bot messages or messages in channel ? If you are using bot in private channels, **you need to invite it using `/invite @Github`.** However `/invite @github @Myname` is **incorrect** command.

You can try signing in again and it should resolve the issue.

**Comment by kymikoloco** [comment]
Along with the same problems @nezriffic is facing, we have invited `@Github` to a private channel added a new subscription to a repo, and none of the notifications it is subscribed to are being pushed to the channel. Signing in does not do anything either. I am suspecting that the notifications that I am receiving are exclusively from the Reminders feature https://github.com/settings/reminders

Is there a log somewhere in GitHub and/or Slack that I can refer to to see why it is failing to work?

**Comment by crash7** [comment]
Can't invite github app to a private conversation. Slack says: "A valid channel name is required."

**Comment by nezriffic** [comment]
> Hi @nezriffic ,
> You should be able to get the notifications properly after migration. As I understand from the title of the issue, you mentioned `direct messages`, are you referring to personal bot messages or messages in channel ? If you are using bot in private channels, **you need to invite it using `/invite @Github`.** However `/invite @github @Myname` is **incorrect** command.
> 
> You can try signing in again and it should resolve the issue.


Can not do that (in private conversation - NOT a channel).

Signing in again does not help:

> GitHubAPP  16:34
> :white_check_mark: Success! @michal is now connected to @nezriffic

Retrying with /invite @GitHub
> Slackbot  16:34
> A valid channel name is required.

**Comment by ashokirla** [comment]
@nezriffic We regret the inconvenience. We will investigate further and get back to you.

**Comment by ashokirla** [comment]
@kymikoloco This looks like a different problem. Can you please create a separate issue. Our team will investigate it further.

**Comment by ekhaydarov** [comment]
Even though this is a bug I have found that you can simple go to the github itslef in the apps section in slack and treat that how you treated it in activating the app in your own direct messages

**Comment by amitkumariiit** [comment]
> > You can try signing in again and it should resolve the issue.
> 
> Can not do that (in private conversation - NOT a channel).

@nezriffic private conversations (not the private channel. its conversation within few folks) are not supported anymore with the new github app. This is the limitation from the slack platform that the apps built on GBP model can't be added to the private coversations.
You can use the app in the channels or for private DM conversation (you & bot)

I am closing this. Please feel free to reopen in case of any questions or info.
