### ISSUE TITLE
Commit notifications sporadically not working after moving to the new app.

### ISSUE THREAD

**Issue by alex-jitbit** [integrations/slack#1187]
After upgrading to the new app, some pushed commits are not sent to Slack channel. Resubscribing fixes this temporarily, but it stops working after some time again.

**Comment by ashokirla** [comment]
Apologies for the inconvenience. We will look into this issue.

**Comment by sushmita-m** [comment]
Can you add some more details. Are you subscribe to `commits:*`?

**Comment by alex-jitbit** [comment]
We are subscribed but without the "star":

`pulls, commits, releases, reviews, branches`

**Comment by sushmita-m** [comment]
@alex-jitbit  sorry for the late reply. I hope you are aware of this change in `commits feature` in the new app - https://github.com/integrations/slack#branch-filters-for-commit

Without the star, you will be receiving notifications only for the default branch. 

If you are facing issues with the default branch as well, can you do a `/github debug` command on your channel and share the details at https://support.github.com/.

**Comment by sushmita-m** [comment]
@alex-jitbit  are your still facing this issue?

**Comment by alex-jitbit** [comment]
@sushmita-m not recently, no.

**Comment by HamzaAnis** [comment]
@sushmita-m 
I am facing the same issue. Tried both `commits:all` and `commits:*`. The notifications that I am getting is only for the default branch.

**Comment by sushmita-m** [comment]
@alex-jitbit We have fixed a bug in the notification flow after this issue was raised. This should not repeat. I am closing the issue for now. If you run into this again, please reach out again.
