### ISSUE TITLE
Commit notifications do not appear in slack if they contain double quotes

### ISSUE THREAD

**Issue by marklapasa** [integrations/slack#1188]
If I push to my remote github branch...

`With a message that contains "double quotes"`

...it does not appear in Slack channel that I configured to subscribe for commit:*

If I push to my remote github branch...

`With a message that contains no double quotes`

...it works.

This bug was introduced in the latest version of the Slack plugin. Prior to installation of the upgrade, I was able to commit messages in the form of the former type.

**Comment by ashokirla** [comment]
@marklapasa Thanks for reaching out to us. We will look into this issue.

**Comment by sushmita-m** [comment]
@marklapasa  Thank you for logging this. This has been fixed.
