### ISSUE TITLE
[GHE] Expose notification mapping from repo to slack channel

### ISSUE THREAD

**Issue by DTrejo** [integrations/slack#1190]
Hello, thanks for your work on this extension. I saw you're working on a new version, great!

We'd find it very useful if we could list out the which slack channels are getting notifications for which repos. Even better if it's possible to access this via the github graphql API (asking way too much I'm betting :) ). It's enough if it's exposed via the slackbot, as then at least we can get the repo<>channel associations.

Thank you!
David

**Comment by ashokirla** [comment]
@DTrejo Can you share few more details about this ask. 
- From what user context would you need this info. Is it Slack workspace admin or GitHub org admin.
- A slack workspace can have hundreds of channels associated with many repositories each through subscriptions and scheduled reminders. How would this info help
- Today from each channel, you can run `subscribe list` command which gives similar info at channel level. Wouldn't that be good enough.

**Comment by DTrejo** [comment]
Hi @ashokirla ,

We have some signals of our own, but we frequently need to find the right group(s) of people to message about a particular repo (not just engineers, but PMs, EMs, leaders, etc). So if we can get the data out with the github API (preferred ofc), or via the slack bot, then that'd make it much easier to find help during an incident, for example.

Even though these can be listed on a per-channel basis, that'd mean a robot needs to be written to iterate through our hundreds of channels and type messages and read in responses, adding noise to the channels.

Thanks for your quick reply!

**Comment by DTrejo** [comment]
Hey, we're exploring another approach, I'll close this for now and follow up if it doesn't work out.
