### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by harryjarman** [integrations/slack#1193]
**Describe the bug**
I have added the GitHub app to the workspace, but when I use the `/github signin` command, I get `/github failed with the error “invalid_user”` and am unsure how to go about rectifying. 

**To Reproduce**
1. Install the app to the workspace
2. In any channel, either public or as a DM to the GitHub bot, send `/github signin`.
3. Slackbot responds with `/github failed with the error “invalid_user”`

**Expected behavior**
The signin flow starts to link my slack bot with my github account.

**Screenshots**
<img width="645" alt="Screenshot 2021-04-28 at 13 48 18" src="https://user-images.githubusercontent.com/47976212/116406277-64e7c080-a828-11eb-99ac-fb7654d77b67.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 11.2.3
 - Browser [e.g. chrome, safari] Slack Desktop
 - Version [e.g. 22] 4.14.1

**Additional context**
The same error occurs when I send `/github subscribe owner/repo`

**Comment by sushmita-m** [comment]
@harryjarman are you on a slack enterprise grid?
On an Enterprise Grid, If the GitHub app is upgraded in one workspace and not in others, this error can occur. Upgrading the GitHub app on all the workspaces of slack enterprise grid will resolve the issue. This can be done by the admin of the grid.

**Comment by harryjarman** [comment]
> @harryjarman are you on a slack enterprise grid?
> On an Enterprise Grid, If the GitHub app is upgraded in one workspace and not in others, this error can occur. Upgrading the GitHub app on all the workspaces of slack enterprise grid will resolve the issue. This can be done by the admin of the grid.

We are on enterprise grid. I will see if an admin can do this for me.

**Comment by sushmita-m** [comment]
@harryjarman are your notifications working after upgrading the GitHub app in all the workspaces?

**Comment by harryjarman** [comment]
@sushmita-m sorry, haven't asked the admins of ent-grid to do that! Will raise a ticket and get back to you.

**Comment by harryjarman** [comment]
@sushmita-m it would appear that there is a ticket already open internally and they are waiting for some workspaces to upgrade! So I believe this issue can close for now
