### ISSUE TITLE
Commit-level comments no longer pushed to Slack

### ISSUE THREAD

**Issue by pheisiph** [integrations/slack#1195]
Despite being subscribed to `comments`, comments made on commits (not on PRs, reviews or issues, those work fine) are no longer posted to slack since the upgrade. 

**To Reproduce**
In a public slack channel: 

```
/github subscribe owner/repo
/github unsubscribe owner/repo commits releases
/github subscribe owner/repo comments
/github subscribe list features

> Subscribed to the following repositories
> owner/repo
> `issues`, `pulls`, `comments`
```

Got to https://github.com/repo/owner/commit/asdf0815commithash and leave a comment on either a line of code (inline) or on the "entire" commit at the bottom of the page.

**Expected behavior**
The comment should get posted to the slack channel, but it doesn't. 

Comments on pull requests _are_ posted to Slack, but comments on commits that don't belong to a PR are not.

**Screenshots**

![comments](https://user-images.githubusercontent.com/537743/116547569-5d411e00-a8f3-11eb-9fb9-ba9adefd0bce.png)

These messages are no longer propagated to slack since upgrading to the new version. Unfortunately our team was heavily relying on these notifications for our workflows.

**Comment by sushmita-m** [comment]
@pheisiph  Comments on commits are not supported in the new app. We are planning to add them back sometime in the next week.
I will keep this issue open until then.

**Comment by sushmita-m** [comment]
@pheisiph  This feature now available in prod. Closing this issue.
