### ISSUE TITLE
subscribe command doesn't work for features

### ISSUE THREAD

**Issue by thienson-ho** [integrations/slack#1204]
**Describe the bug**
When using the subscribe command for a specific feature such as pulls, the Slack channel is subscribed to all default features (issues, pulls, commits, releases) 

**To Reproduce**
1. Go to Slack channel with GitHub app invited
2. Enter '/github subscribe owner/repo [feature]' 
3. See that the channel is subscribed to all 4 default features instead of the specified one

**Expected behavior**
When I subscribe to just pulls I expect not to be subscribed to issues, pulls, commits, and releases. I have to make an unsubscribe command for the other features to just be subscribed to pulls

**Screenshots**
<img width="593" alt="Screen Shot 2021-05-04 at 2 00 28 PM" src="https://user-images.githubusercontent.com/22736015/117055848-4464ae00-ace1-11eb-92b9-40e4dac67752.png">
<img width="652" alt="Screen Shot 2021-05-04 at 2 00 35 PM" src="https://user-images.githubusercontent.com/22736015/117055884-4cbce900-ace1-11eb-9c13-5aa904666f21.png">
<img width="641" alt="Screen Shot 2021-05-04 at 2 06 14 PM" src="https://user-images.githubusercontent.com/22736015/117056488-f7350c00-ace1-11eb-93ca-d38606c77715.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina V 10.15.7

**Comment by sushmita-m** [comment]
This is by design @thienson-ho. We did not change this behaviour from the old app.
`pulls` is a default feature. To be able to only subscribe to pulls, it is by unsubscribing to other features.
I will mark this as a feature request.
