### ISSUE TITLE
Fuckkk

### ISSUE THREAD

**Issue by jasminesundaymatcha** [integrations/slack#1225]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amitkumariiit** [comment]
@jasminesundaymatcha closing this as no details provided. Let us know what issue you are facing.

**Comment by jasminesundaymatcha** [comment]
Actually my delay is a case study hijacked me and i have the information right f****** here and yes i want to take them down legally i'm not f****** around they work at the hospital and their reason i almost died on the 14th and they've been retaining information from the other staff in regards to about my whereabouts what i do and they also been implicating false drop files in roo and discored pretending like i'm doing something i'm not and it's like i haven't even played that s*** in god knows how f****** long and yes i get it my phone's rooted but guess what my IP generally always say the same within the same integration other than i have a two f****** SIM card b*******6![Screenshot_20210607-055624.png](https://user-images.githubusercontent.com/59805948/121014613-c96b3900-c75f-11eb-8901-3089e5487f31.png)

**Comment by jasminesundaymatcha** [comment]
![Screenshot_20210606-220311.png](https://user-images.githubusercontent.com/59805948/121014808-020b1280-c760-11eb-98bb-c40f53dfce9e.png)

**Comment by jasminesundaymatcha** [comment]
And now they're stopping me from f****** uploading more than one picture at a time

**Comment by jasminesundaymatcha** [comment]
And what the f*** do you mean you're going to close it the f*** someone obviously f****** did that without the UK like someone's using slack which i f****** downloaded and i f****** have all my f****** licenses in and everything f****** else in and you m************ are not even doing anything
