### ISSUE TITLE
I just want to push to the channel when the new version is released. But I don’t know which option to choose to do it. I tried it and didn't find the answer.

### ISSUE THREAD

**Issue by CJayHe** [integrations/slack#1231]
I just want to push to the channel when the new version is released. But I don’t know which option to choose to do it. I tried it and didn't find the answer.

![截屏2021-06-0812 17 14](https://user-images.githubusercontent.com/22066314/121122132-770b4480-c853-11eb-8ace-274fccb3a463.png)

![截屏2021-06-0812 17 33](https://user-images.githubusercontent.com/22066314/121122199-93a77c80-c853-11eb-90a0-19748ee542e9.png)

**Comment by amitkumariiit** [comment]
@CJayHe Ideally you should get the notifications posted for the new release. Can you share the following info to debug it further. 
- Share the details of `/github debug` command on the channel where you have subscribed to repo.
- Are you getting other notifications than releases like PR/Issue/comments ?

**Comment by CJayHe** [comment]
With this setting, I can get the push of the new version. But I will get other information. I just want the push of the new version, nothing else.
![截屏2021-06-1011 58 33](https://user-images.githubusercontent.com/22066314/121462492-422df780-c9e3-11eb-996e-9d8f59464e7c.png)
I tried to exclude each option, but I found the most likely option in the option description`releases `,`deployments ` and it still didn't work.
![截屏2021-06-1011 58 33](https://user-images.githubusercontent.com/22066314/121463202-2a0aa800-c9e4-11eb-8f0e-7d2d91a44bb7.png)

I don't know how to configure

**Comment by apurva1112** [comment]
@CJayHe  On subscribing to release notifications, you will end up seeing the complete release info whenever a new release is created like the below image.
<img width="647" alt="Screenshot 2021-06-10 at 4 08 12 PM" src="https://user-images.githubusercontent.com/42499837/121511250-1112ee80-ca06-11eb-9972-9664c3791985.png">

However if you just want to see push notifications just for the new tag version, you can subscribe to branches. You will see a notification like below as whenever you create a new tag a new branch is also created.
<img width="319" alt="Screenshot 2021-06-10 at 4 09 17 PM" src="https://user-images.githubusercontent.com/42499837/121511408-37d12500-ca06-11eb-804b-9bec4ac25198.png">

**Comment by CJayHe** [comment]
he effect is as you said, but what is the corresponding command?

**Comment by apurva1112** [comment]
@CJayHe You can subscribe to branches with command `/github subscribe repo/org branches`

**Comment by CJayHe** [comment]
solved

`/github subscribe phpzlc releases`  You can complete the configuration

The problem comes out on the channel's permission to speak
