### ISSUE TITLE
"/github unsubscribe" doesn't recognize repos subscribed in a public channel

### ISSUE THREAD

**Issue by blakew** [integrations/slack#1232]
**Describe the bug**
There is a repo subscribed to a public channel in my org. I want to remove it. From the channel, I do `/github unsubscribe org/repo` and it says `You're not currently subscribed to org/repo`. So how do I unsubscribe this repo from the public channel?

Note that I tried `/github subscribe list` and the repo wasn't listed (though the org itself is). 

**To Reproduce**
1. User A subscribes a repo to a public channel
2. User B tries to unsubscribe the repo from the channel
3. See error

**Expected behavior**
I expect to be able to unsubscribe a github repo from a public channel (Note I am an admin of my workspace)

**Comment by amitkumariiit** [comment]
@blakew can you share the `/github debug` output for us to debug further. 

Also, can you please consider upgrading the app to the new version. You should be getting the notifications for upgrading the app. You can follow that to update the app or you can directly install the new version of GitHub app from here https://slack.github.com/ 
Post that

**Comment by blakew** [comment]
@amitkumariiit hey thanks for replying so soon.

Here is the `/github debug` output:

```
{
  "team_id": "T03AZ44FA",
  "team_domain": "faradayio",
  "user_id": "U01N27W220Z",
  "channel_id": "CJJ344465",
  "channel_name": "dev",
  "text": "debug"
}
```

I actually did upgrade the app to the new version before posting this. I clicked "Add to Slack" and "Allow" and I got the notification below

![image](https://user-images.githubusercontent.com/90002/121369210-a67c8880-c909-11eb-8985-f7176171969b.png)

**Comment by apurva1112** [comment]
@blakew I have few questions.

> **Describe the bug**
> There is a repo subscribed to a public channel in my org. I want to remove it. From the channel, I do `/github unsubscribe org/repo` and it says `You're not currently subscribed to org/repo`. So how do I unsubscribe this repo from the public channel?
> 
> Note that I tried `/github subscribe list` and the repo wasn't listed (though the org itself is).

1. How did you find out that the repo is subscribed to your channel when `/github subscribe list` is not showing it?

2. You said you are subscribed to the org in which repo is present so you will get notifications for that repo. If you think you are subscribed to both org and repo, you should get duplicate notifications for events from that repo, one for repo and one for org subscription. Are you getting duplicate notifications?

**Comment by blakew** [comment]
1. One of the repos in our org was polluting our public slack channel with notifications and I wanted to disable it (just the one repo)
2. @apurva1112 thanks I think you helped clarify for me that if you are subscribed to the org, you will get notifications on every repo in that org. There is no way to blacklist. 

I think to get what i want, I have to unsubscribe from the org, and subscribe to just the individual repos that I want. It would be nice to have a blacklist capability though. Let me know if I misunderstand.
