### ISSUE TITLE
/github subscribe owner/repo feature subscribes to all features

### ISSUE THREAD

**Issue by samcdavid** [integrations/slack#1237]
**Describe the bug**
When I type in `/github subscribe owner/repo pulls`, it also subscribes to commits, issues, deployments, and releases.

**To Reproduce**
1. Go to any channel and pick and repo you want
2. Type in `/github subscribe owner/repo pulls`
3. The output will say that the channel will receive notifications for commits, pulls, issues, deployments, and releases.

**Expected behavior**
Output stating that the channel will only receive notifications for pulls (or whatever feature was specified). This screenshot shows what I want to happen (I had to unsubscribe to the other events and delete the slack messages to get this representation).
<img width="649" alt="Screen Shot 2021-06-15 at 3 26 32 PM" src="https://user-images.githubusercontent.com/773102/122111887-4052a280-cdee-11eb-9bbd-34f91b5eb436.png">

**Screenshots**
<img width="693" alt="Screen Shot 2021-06-15 at 3 24 25 PM" src="https://user-images.githubusercontent.com/773102/122111642-f9fd4380-cded-11eb-894f-e07f3b0d69c0.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 11.4
 - Slack 4.17.0 (Production)

**Additional context**

**Comment by sanjeev9160** [comment]
@samcdavid `issues,pulls,commits,releases and deployments` are the default features i.e. they are automatically subscribed when a new artifact(repo or account) is subscribed. And the output message **displays all the features** which are subscribed to the artifact.

![image](https://user-images.githubusercontent.com/64134945/124475350-3efa1180-ddbf-11eb-8a2d-9d76e3cf2624.png)

Now if we want to subscribe to some additional features(non-default features) like comments, then we can use the 
/github subscribe artifact comments

![image](https://user-images.githubusercontent.com/64134945/124475993-fa22aa80-ddbf-11eb-84a1-90562ad6c58e.png)

And you can see the output listing all the features which are subscribed to the artifact including the new feature comments.

In case if we need to **unsubscribe to the features**:
Let's take an example: Unsubscribe features like commits, pulls and deployments, run the following commands:
/github unsubscribe repo commits,pulls,deployments

Do let us know if any other help is required. Thanks.

cc: @ashokirla

**Comment by samcdavid** [comment]
I get that is the default, but the documentation leads me to believe that if a channel is not receiving any notifications for a repo, that you can do `/github subscribe [repo] pulls` and then only be subscribed to pulls rather than all of the defaults.

**Comment by sanjeev9160** [comment]
Thanks for your feedback for the improvement of the documentation. In the documentation, we do mention the features enabled by default in https://github.com/integrations/slack#configuration. 
Will be closing the issue. Thanks.

**Comment by Nikodermus** [comment]
👍 We also had this misunderstanding, it makes you thing that you can enable specific subscriptions on the initial setup.

Troubleshoot (Let's say you want only `pulls`)
```
/github subscribe owner/repo 
/github unsubscribe owner/repo  issues commits releases deployments
```

All `features` are ignored in your first "subscribe" to the repo, so `/github subscribe owner/repo` will be the same as `/github subscribe owner/repo pulls` on your first connection

**Comment by Saminkamoje2810** [comment]
> **Describe the bug** When I type in `/github subscribe owner/repo pulls`, it also subscribes to commits, issues, deployments, and releases.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to any channel and pick and repo you want
> 2. Type in `/github subscribe owner/repo pulls`
> 3. The output will say that the channel will receive notifications for commits, pulls, issues, deployments, and releases.
> 4. See error
> 
> **Expected behavior** Output stating that the channel will only receive notifications for pulls (or whatever feature was specified). This screenshot shows what I want to happen (I had to unsubscribe to the other events and delete the slack messages to get this representation). <img alt="Screen Shot 2021-06-15 at 3 26 32 PM" width="649" src="https://user-images.githubusercontent.com/773102/122111887-4052a280-cdee-11eb-9bbd-34f91b5eb436.png">
> 
> **Screenshots** <img alt="Screen Shot 2021-06-15 at 3 24 25 PM" width="693" src="https://user-images.githubusercontent.com/773102/122111642-f9fd4380-cded-11eb-894f-e07f3b0d69c0.png">
> 
> **Desktop (please complete the following information):**
> 
> * OS: Mac OS 11.4
> * Slack 4.17.0 (Production)
> 
> **Additional context** Add any other context about the problem here.


/github subscribe owner/repo [feature]
/github unsubscribe owner/repo [feature]
