### ISSUE TITLE
more actions not available for messages

### ISSUE THREAD

**Issue by charlieeatonphd** [integrations/slack#1258]
When I click on the More Actions ... of a message, there are no Menu Options for GitHub actions for the message.

1. I am using a Slack on Mac OS Big Sur
2. I have installed the GitHub Application within Slack.
3. I have successfully opened a GitHub issue within the Slack Channel using /github open [owner/repo]

**Expected behavior**
I expected to be able to select an action to comment on the issue from future messages per the following from the README.md file:

> You can also take action on GitHub directly from a Slack message by clicking on the '... More Actions' menu available on every Slack message. From there you can:
> 
> - Attach a message as a comment to an existing issue or pull request
> - - Select an issue by choosing from an automatically loaded list of recently active issues and pull requests that involve you or by entering a URL to an issue or pull request

**Screenshots**
<img width="702" alt="Screen Shot 2021-07-12 at 12 45 36 PM" src="https://user-images.githubusercontent.com/6294571/125347456-cd1a4e80-e30f-11eb-9e9f-cea9e9c1747e.png">
<img width="698" alt="Screen Shot 2021-07-12 at 12 45 13 PM" src="https://user-images.githubusercontent.com/6294571/125347461-ce4b7b80-e30f-11eb-82af-0b1db6a53bee.png">

**Comment by amitkumariiit** [comment]
Hi @charlieeatonphd,
Thanks for opening the issue for this. We need to update the readme about the same. 
This feature was removed in the new version of the GitHub app and we are focused on bringing actions in more holistic way.
