### ISSUE TITLE
Stuck in an installation loop and unable to add subscriptions

### ISSUE THREAD

**Issue by dwightgunning** [integrations/slack#1268]
**Describe the bug**
After installing the GitHub App into my Slack organization and authorizing the integration in my GitHub Organization, when I return to the Slack client and attempt to create a subscription the Slack App prompts to "Install GitHub App".

Of note, is that this Slack Org and GitHub Org has had a legacy GitHub Enterprise Server integration installed.

**To Reproduce**
1. Go to the Slack App Directory and install the GitHub App.
2. After being redirected to open the Slack client, invite the `@Github` user to the channel
3. Enter the GitHub command `/github subscribe owner <org name>`
4. Click the button "Install GitHub App"
5. From the GitHub app installation wizard, select the organization in which to install the app
6. Allow access to all repositories in the organization. Click save.
7. Return to the slack client and type `/github subscribe owner <org name>`
8. _Repeat steps 4 - 7_

**Expected behaviour**
After installing the GitHub App into both Slack and GitHub I expect to be able to create subscriptions.

**Screenshots**

The Slack App Directory indicates the app is installed:

<img width="1570" alt="Screen Shot 2021-07-29 at 5 52 49 pm" src="https://user-images.githubusercontent.com/454042/127525251-54ef9e0a-6043-4a58-84ef-72c584a90332.png">

The GitHub App settings indicates that access is granted to all repositories.

<img width="974" alt="Screen Shot 2021-07-29 at 5 49 50 pm" src="https://user-images.githubusercontent.com/454042/127525258-e704680b-eaa3-4d0d-9ae2-87651380713c.png">

Slack client repeatedly prompts to install the GitHub app.

<img width="923" alt="Screen Shot 2021-07-29 at 5 49 40 pm" src="https://user-images.githubusercontent.com/454042/127525262-5bb62737-cc37-46aa-b197-dac90f55bcdb.png">

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Google Chrome
 - Version Version 91.0.4472.164 (Official Build) (x86_64)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amitkumariiit** [comment]
Hi @dwightgunning , 
are you still facing this issue ? Can you share more details about the slack workspace, channel etc. Can you run the /github debug command and let share the output.

**Comment by dwightgunning** [comment]
Hey @amitkumariiit - We're still experiencing the problem. Is there a way I can get you the debug info without posting on a public issue log?

Sending the command message `/github` produces a listing of valid commands.

Sending the command message `/github settings` doesn't seem to do anything.

The only thing interesting that's come to light since my original post is that there has been messages posted by the integration based on commits to one of our team's less active projects. So somehow it seems to be partially working. However no messages are posted based on activity in our other more active repo.

When clicking on the GitHub avatar in channel, I can follow a link to the Slack App's config for our org. The App Id shown in the URL appears to be `A01BP7R4KNY-github`. I mention this again because I know we had an old legacy Enterprise Git App installed previously. I suspect this may be part of the problem?

On our GitHub 'organization account' > Installed Github Apps listing, I can see the Slack app has access to all repositories:

> Permissions
> (tick) Read access to checks, code, commit statuses, metadata, and repository projects
> (tick) Read and write access to deployments, issues, and pull requests

The slack app shows on the project-specific Settings > Integrations listing.

**Comment by amitkumariiit** [comment]
Hi @dwightgunning,
You can directly reach out to the customer support and the issue will routed to us internally
https://support.github.com/contact?subject=GitHub%2BSlack%20integration

**Comment by dwightgunning** [comment]
Thanks - ticket is #1271182

**Comment by aasiddiq** [comment]
Hi @dwightgunning 
Just to confirm are you running the command `/github subscribe owner <org name>` with the word `owner` included? If so, that would mean you are trying to subscribe to an org/account named 'owner'.
The syntax for the command is `/github subscribe {org/repo}`, could you try this and check if it works for you?

**Comment by dwightgunning** [comment]
Ah! That was the problem. I probably should have figured this out myself. Thanks for pointing this out.

In case it's helpful for improvements down the track....

When reading the help text emitted by the GitHub Slack app... I thought that 'owner' or 'repo' was part of the command. It didn't stand out as an argument/parameter as in your comment above.

<img width="498" alt="Screen Shot 2021-08-16 at 3 05 39 pm" src="https://user-images.githubusercontent.com/454042/129568803-1c664b15-d4a5-4dc6-809f-6e858c33c327.png">

Also the subsequent error message doesn't refer back to the failing argument: "Either the app isn't installed on your account or the account does not exist. Install it to proceed." If the message asked "Are you sure the app is properly installed on the 'owner' account?" it would have been obvious I was providing a bad arg.

I guess the integration has probably been setup successfully by approx. 1 bazillion competent folks... so I'm probably just an outlier.
