### ISSUE TITLE
Rich preview for GitHub wiki page renders markdown links to #anchors as "#private-channel" in Slack

### ISSUE THREAD

**Issue by jeremy-w** [integrations/slack#1292]
**Describe the bug**
When a linked-to document includes `#hashmarks`, the preview provided to Slack appears to pipe the on through, Slack appears to try to render them as channel names, which it treats as "#private-channel", thus making the preview unreadable.

**To Reproduce**
1. Message https://github.com/cpscc/wiki/blob/master/official-cornerstone-api.md in a channel
2. Behold the rendered preview

**Expected behavior**
You can see the text.

**Screenshots**
![Screen Shot 2021-09-15 at 11 57 04](https://user-images.githubusercontent.com/29010/133467856-e1416a60-baa3-475f-8713-c7092972c84c.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version:
   - ProductName:	macOS
   - ProductVersion:	11.4
   - BuildVersion:	20F71

**Additional context**
macOS Slack app version: Version 4.20.0-beta1 HEAD/bcf92ea
584d8efbfd84c88323805d2f31ba0db9b34dcae7@1631696246 (Beta)

Confirmed issue reproduces in iOS Slack app v21.09.11.

The text triggering the issue looks to be anything like `[OneWord](#anchor-name-here)`. Interestingly, if the anchor text is `[two words](#anchor-here)`, it is still distorted, but not redacted by Slack.

**Comment by madhavan-v** [comment]
The fix for this change was tested and deployed to production hence closing this issue, please reopen this issue in case it occurs again
