### ISSUE TITLE
Back slash ("\") is added at the front of underscore characters ("_") in branch names/links

### ISSUE THREAD

**Issue by jay-alansari-axomic** [integrations/slack#1294]
**Describe the bug**
For branch names that contain the underscore character ("_").
A back-slash is added before every underscore.
In slack messages containing "Branch created" or "Branch deleted".

Earliest message containing this issue, was seen at around mid-day (UTC) on 15th September 2021.

**To Reproduce**
Example, when creating a branch:
1. Clone a repository, and create a branch, where the name contains underscore(s):  `git checkout -b my_new_branch`
2. Push the branch to github: `git push --set-upstream origin my_new_branch`
3. Go to slack, and notice a new message will be received from github app:
`Branch created by <yourusername>`
`  |  my\_new\_branch`
`  |  <repo>`
4. Note the extra backslashes (which look like erroneous escape characters).
5. Also, the link on the branch name will ALSO contain the backslashes, therefore, making the links invalid:  e.g.:
`https://github.com/<account>/<repo>/tree/my\_new\_branch`

**Expected behavior**
Branch name should not be altered:
For example:
`Branch created by <yourusername>`
`  |  my_new_branch`
`  |  <repo>`
And, the hyperlink on the branch name must be valid with no extra backslashes:
`https://github.com/<account>/<repo>/tree/my_new_branch`

**Screenshots**
N/A

**Comment by john275** [comment]
Stumbled across this, I re-added our integration to slack after the GH/Slack link got severed when an account was removed, since adding (using newer integration) the branch names (we always user underscores) have a backslash prefixing the underscore which breaks the link in slack message. So interested and watching this issue

**Comment by jrochkind** [comment]
just found this looking to see if bug was already reported. also running into it. it didn't always do this, not sure when it started, last week or two?

**Comment by jay-alansari-axomic** [comment]
@jrochkind as I noted in the description, we started experiencing this issue at "_mid-day (UTC) on 15th September 2021_".
Interested to see if you can also track this issue to the same time.

**Comment by madhavan-v** [comment]
This PR: https://github.com/github/slack/pull/1934/files has fixed this issue hence closing this
