### ISSUE TITLE
PR review notifications are not sent after the PR is approved

### ISSUE THREAD

**Issue by JoannaFalkowska** [integrations/slack#1296]
**Describe the bug**
No notifications about PR reviews are sent after the first approve. 

**To Reproduce**
1. Create a PR.
2. Have it approved by a person.
3. Have it approved by another person.

**Expected behavior**
Notifications about *all* reviews of my PRs are sent.

**Screenshots**
![image](https://user-images.githubusercontent.com/14551750/134171014-d68778cf-02d6-4d72-a80f-29bc30bbb615.png)
![image](https://user-images.githubusercontent.com/14551750/134170236-1ff5eab4-bf92-4e03-9d3b-55adbf897ce3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
Other than the main bug described, the PR requests (visible in screenshot above) are crossed after only one approve, despite the repo settings requiring two approves to merge a PR. I believe this integration wrongly assumes that after the first approve no other reviews can happen to a PR, and that everyone has minimum approves number set to 1.

**Comment by sanjeev9160** [comment]
> **Describe the bug** No notifications about PR reviews are sent after the first approve.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create a PR.
> 2. Have it approved by a person.
> 3. Have it approved by another person.
> 
> **Expected behavior** Notifications about _all_ reviews of my PRs are sent.
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/14551750/134171014-d68778cf-02d6-4d72-a80f-29bc30bbb615.png) ![image](https://user-images.githubusercontent.com/14551750/134170236-1ff5eab4-bf92-4e03-9d3b-55adbf897ce3.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows
> * Browser: Chrome
> 
> **Additional context** Other than the main bug described, the PR requests (visible in screenshot above) are crossed after only one approve, despite the repo settings requiring two approves to merge a PR. I believe this integration wrongly assumes that after the first approve no other reviews can happen to a PR, and that everyone has minimum approves number set to 1.

@JoannaFalkowska I tried reproing the issue with the mentioned repro steps but was unable to repro it. 
Do you still see the issue happening and Is it happening occasionally or consistently? Thanks.

**Comment by sanjeev9160** [comment]
Closing it. Please feel free to reopen it with the relevant details. Thanks.
