### ISSUE TITLE
I still see rich previews of GH links in Slack channel after muting them via `/github settings` 

### ISSUE THREAD

**Issue by daniellepintz** [integrations/slack#1300]
**Describe the bug**
I still see rich previews of GH links in Slack channel after muting them via `/github settings` 

**To Reproduce**
1. Mute rich previews via `/github settings`
2. Have someone other than you send a GH link in the channel
3. Notice the link still has the rich preview. 
4. Confirm that rich previews are "muted" by typing `/github settings` again

**Expected behavior**
When someone sends a GH link in the channel when rich previews are muted, I expect not to see a rich preview.

**Screenshots**
<img width="674" alt="Screen Shot 2021-09-26 at 11 09 06 PM" src="https://user-images.githubusercontent.com/38207072/134856163-78e97b58-d983-4bd9-9a18-28287cf3a6bd.png">

**Environment:**
Slack Desktop App Version 4.20.0

**Comment by amitkumariiit** [comment]
Hi @daniellepintz ,
Currently the settings features for preview is at user level. It means that only for the user, url will not show the rich preview if muted.  This is designed like that as of now, thinking to empower individual to decide whether they want to unfurl or not the urls **they share only.** 

adding @ashokirla for review.

**Comment by daniellepintz** [comment]
Ah I see thanks so much for the explanation! I had interpreted "at the user level" to mean the user determines whether they see previews or not for the channel. Now I understand it is for if their links show or not in the channel.

**Comment by amitkumariiit** [comment]
Yes, your understanding it correct now @daniellepintz . 
You can close the issue if you find it good.

**Comment by ricky-scopely** [comment]
@amitkumariiit You have a bunch of people here asking for a completely different behaviour, in case you are interested:
https://github.com/integrations/slack/issues/487
