### ISSUE TITLE
There is an issue with the drawing function when using on systems with multiple displays

### ISSUE THREAD

**Issue by joshuajohnmarlow** [integrations/slack#1304]
**Describe the bug**
When screen sharing on a setup with multiple displays, and the screen that is being shared is a second monitor, when someone draws on the screen, two lines appear. This seems to be the case when the user drawing is using their main display, and also when using a second display. The lines seem to be closer together the closer to the top left of the screen and further apart towards the bottom right, which seems to indicate an issue with the scaling of the screen size.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a call and share a screen on a second monitor.
2. Enable drawing and have a user in a call draw on the screen.
3. Two lines will appear on the screen, one where expected and one in an incorrect place.

**Expected behaviour**
Only one line should appear on the screen, where the mouse is.

**Desktop (please complete the following information):**
 - OS: This issue has been seen on both a mac and Windows, desktop version.

**Comment by gauravsaralMs** [comment]
@joshuajohnmarlow This repo tracks issues with the integration between slack and GitHub. (slack.github.com)

from the issue description it seems like you are having issues with a slack feature.

**Comment by joshuajohnmarlow** [comment]
@gauravsaralMs thanks for pointing me in the right direction, however the link you have provided doesn't seem to work. I am presented with a page to sign in with Okta - of which do not have an account.

**Comment by gauravsaralMs** [comment]
@joshuajohnmarlow looks like slack adds the workspace by default
can you try 
https://slack.com/intl/en-in/help/requests/new

**Comment by joshuajohnmarlow** [comment]
thank you kindly, I have raised the issue with them.

happy for this issue to now be closed, as is not related to github integration.
