### ISSUE TITLE
Review comments with suggested changes show the warning about bidirectional unicode text

### ISSUE THREAD

**Issue by TimWolla** [integrations/slack#1315]
**Describe the bug**

Notifications about PR review comments containing a suggested change include the warning about bidirectional unicode text at the top of the message. This warning is not shown in GitHub itself.

**To Reproduce**

1. Subscribe to PR notifications in a channel.
2. Make a comment with suggested changes to a PR.
3. Look at the Slack message.

**Expected behavior**

I expected that warning not to be shown.

**Screenshots**

![scrot_2021_11_08_12_59_47](https://user-images.githubusercontent.com/209270/140738502-f016802c-7df1-44d6-899a-b050f0a05299.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Slack Desktop App
 - Version n/a

**Smartphone (please complete the following information):**

**Additional context**

**Comment by madhavan-v** [comment]
The cause of the issue has been identified and is being worked upon by one of the dependant teams

**Comment by madhavan-v** [comment]
this bug was fixed and verified, please reopen if it occurs again
