### ISSUE TITLE
Footnotes displayed badly in pull request messages

### ISSUE THREAD

**Issue by StevenMaude** [integrations/slack#1321]
**Describe the bug**

Fairly recently, GitHub added the ability to use [footnotes in Markdown](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/). There are two issues here:

1. Footnote *links* are incorrectly interpreted as a Slack "private channel". This may be that the `#` in the fragment identifier makes it through and gets incorrectly picked up by Slack as a channel name :man_shrugging:
2. Footnote *content* is shown partially correctly, but has a href fragment shown where the "return to footnote" :leftwards_arrow_with_hook: link appears

I have not tested, but this may well happen elsewhere; for example: where issues have Markdown footnotes.

**To reproduce**

1. Have the GitHub Slack integration configured and subscribe to pull requests for a repository.
2. Create a pull request in that repository via GitHub's web UI with a simple footnote.
3. Observe the pull request in Slack shows "private channel". Also observe that you get a fragment identifier shown where the "jump back to footnote link" appears. (Note that I manually edited the user content ID in the screenshot: it was a random-looking hexadecimal, not a regular pattern.)

![An example of writing a simple footnote in a pull request via GitHub's web UI.](https://user-images.githubusercontent.com/3818079/141836128-d4563b39-1d41-43f1-bc3e-e633aeb53def.png)

![The appearance of the same pull request in Slack via GitHub's Slack integration.](https://user-images.githubusercontent.com/3818079/141836146-b0723404-6806-46d3-9195-2f7c0bebc60a.png)

**Expected behavior**

1. The footnote link to be shown as `[1]`, `[^1]` or similar.
2. The footnote content to not display a raw fragment identifier.

**Comment by sanjeev9160** [comment]
@StevenMaude Thanks for pointing it out. We are looking into it.

**Comment by sanjeev9160** [comment]
@StevenMaude I have fixed the issue. Thanks.

**Comment by StevenMaude** [comment]
@sanjeev9160: I've tested and this now works as expected. Thanks for the prompt fix :rocket:
