### ISSUE TITLE
"The Slack app by github is requesting updated permissions" for Discussions

### ISSUE THREAD

**Issue by joshuacwnewton** [integrations/slack#1333]
Last night, I received permissions emails for some of the organizations I'm a part of. The emails link to this request:

![Screenshot from 2021-12-14 07-15-46](https://user-images.githubusercontent.com/16181459/145996655-17e3f7c2-71d4-4519-80ff-6112a45267f7.png)

I'm 99% sure this is fine, but still, before accepting I wanted to double-check to see if this is tied to a feature update or blog post of some kind (as was the case for https://github.com/integrations/slack/issues/588). I also can't see anything related to Discussions in the [permissions section of the README](https://github.com/integrations/slack#github-permission-scopes)... (I can guess why the app needs read permissions for Discussions, but, just making sure).

**Comment by antn** [comment]
👋 Sorry about this! I'm updating our documentation to include our new discussions support in https://github.com/integrations/slack/pull/1332

**Comment by mscuthbert** [comment]
Did this just happen again today?  I've received two notifications for two different organizations I'm an Owner on and would also like some confirmation that it's legit.  Thanks!

**Comment by fardarter** [comment]
I'm here for the same reason as above. The app is also requesting PR write permissions, which I'm not super keen on.

**Comment by Teshaylanp** [comment]
Here for the same reason as well, not keen on just accepting anything with write permissions

**Comment by fardarter** [comment]
Submitted this to try make sure there's at least some visibility on this: https://github.com/integrations/slack/issues/1547
