### ISSUE TITLE
Unable to filter commits by branch name containing a '.'

### ISSUE THREAD

**Issue by Dylan-Brotherston** [integrations/slack#1354]
**Describe the bug**
Attempting to subscribe to a repository and filter commits by a branch name containing a `.` gives an error:
`commits:"branch.name"` is not a valid argument.

**To Reproduce**
Run the slack command `/github subscribe owner/repository commits:"branch.name"`

**Expected behavior**
To successfully subscribe with the message:
```
This channel will receive notifications for
`issues`, `pulls`, `commits:'branch.name'`, `releases`, `deployments`
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Slack Desktop

**Comment by boroth** [comment]
+1 Also just discovered this issue.

**Comment by nicoloboschi** [comment]
Is there any workaround for that ? 
The best I found is to subscribe is this way: (e.g. branch-2.8)
`/github subscribe owner/repository commits:"branch-*"`

obviously I receive a lot of unnecessary noise anyway

**Comment by Dylan-Brotherston** [comment]
Unfortunately the only way I have found has been to use a wild card as well.

**Comment by aasiddiq** [comment]
@nicoloboschi @Dylan-Brotherston We have publsihed a new change which should address this. Could try to subscribe again? Please let us know if you see any issue

**Comment by aasiddiq** [comment]
Thanks for the confirmation closing this. Feel free to reopen if you see any other issue.
