### ISSUE TITLE
Github app posting to channel it's not a member of

### ISSUE THREAD

**Issue by sej3506** [integrations/slack#1358]
**Describe the bug**
Github integration app is added to my Slack organization and exists in a specific channel (channel B) and successfully posts about subscribed topics.

However, it has begun to intermittently posting some updates to another channel which it is not a member of (channel A).

In the past, we used the integration app in channel A but had turned it off months ago. It was only after we turned the app on in channel B that it started posting to A again. It only posts _some_ updates to channel A now.

**To Reproduce**
1. Add integration bot to channel A
2. Kick the bot out of channel A
3. Add the bot to channel B and subscribe
4. See intermittent posts from bot to channel A (these are also posted to channel B as expected)

**Expected behavior**
Github bot only posts to channel B

**Comment by ashrocket** [comment]
I tried `/github subscribe list` and saw that the channel was subscribed to a particualr repo in our account.
Another team member tried unsubscribing
`/github unsubscribe repo`  without success.
When we tried `/github unsubscribe Owner/repo` it worked.
Maybe the error message can be improved?
when we tried just using the Vault Name we got this message instead.

<img width="615" alt="Screen Shot 2022-02-11 at 7 22 26 AM" src="https://user-images.githubusercontent.com/713675/153637524-a8280605-aa93-42e2-b0d3-62387ca4d982.png">
