### ISSUE TITLE
Assignee and Author mention in Slack Message is not working

### ISSUE THREAD

**Issue by SimonOsipov** [integrations/slack#1362]
**Describe the bug**
Assignee and Author do not receive mention in Slack, even if they both performed `/github signin` command.

**To Reproduce**
1. Sign in (`/github signin` command)
2. Create new PR, set yourself as Assignee and Reviewer
3. Check the notification in Slack

**Expected behavior**
Author, Assignee, and Reviewers should receive mention in Slack

**Screenshots**
Both of us signed in, but only the Reviewer gets Slack mentioned. 
![CleanShot 2022-02-17 at 20 32 53](https://user-images.githubusercontent.com/28685772/154538490-6f4ff2bc-1e28-454c-a996-1348c4a6338f.png)

**Comment by SimonOsipov** [comment]
@apurva1112 Okay, could this be implemented as a new feature?

**Comment by apurva1112** [comment]
> @apurva1112 Okay, could this be implemented as a new feature?

@SimonOsipov We are avoiding too many at mentions in a card to avoid noise and limiting it to reviewers and PR body in PR cards.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
I think the Author mention is absolutely necessary. How about reopening?

**Comment by sungtaekk** [comment]
@apurva1112 It’s not too many.

We need this feature. Without this feature, we are either mentioning ourselves in the PR body or reviewers mentioning contributors.

Even if it is optional, I would be so happy if you provide a function!
