### ISSUE TITLE
Other team members can't authenticate github

### ISSUE THREAD

**Issue by brennaharden** [integrations/slack#1368]
**Describe the bug**
I need the rest of my team to be able to log in to the GitHub app to receive mentions notifications... but we can't figure out how to get other folks signed in :0)
![But how](https://user-images.githubusercontent.com/67924219/156618952-58547da4-6b79-4ae2-a47c-212d42ffc9ff.png)

**Comment by aasiddiq** [comment]
@brennaharden for the folks in your team they need to signing using the command `/github signin`. They do not need to create subscriptions if they are already a part of channel where you have created subscription. 
You refer [here](https://github.com/integrations/slack#getting-started) for more details.

**Comment by brennaharden** [comment]
@aasiddiq Thank you so much! I was scouring the docs for this and couldn't find it. I don't know if I just missed it somehow, but I thought I would let you know!
