### ISSUE TITLE
Verification code is whitespace sensitive during login process

### ISSUE THREAD

**Issue by abrindam** [integrations/slack#1372]
**Describe the bug**
When going through the login process, you need to input a six digit verification code. Including additional trailing whitespace causes the verification to fail. As the code is usually copy-pasted, it is easy to do this by mistake.

**To Reproduce**
1. Start signin via `/github signin`
2. Click `Connect GitHub Account`
3. In web browser, accept authorization
4. Copy the 6 digit code that is shown
5. In Slack, click `Enter Code`
6. Enter the 6 digit code followed by a space
7. Get error `Invalid verification code found. Please try again.`

**Expected behavior**
The code should be accepted. Whitespace should be ignored.

**Desktop (please complete the following information):**
 - OS: MacOS 11
 - Browser: Firefox 97

**Comment by ashokirla** [comment]
@snankani Can you get the DRI to look into this issue.

**Comment by sushmita-m** [comment]
This is now fixed.

Just curious @abrindam are you not seeing a copy button after the verification code?
<img width="642" alt="Screenshot 2022-04-27 at 12 48 33 PM" src="https://user-images.githubusercontent.com/63236940/165463117-f3e4e9c2-3ad4-415b-b335-228568c4e6c6.png">
