### ISSUE TITLE
Docs for mention mapping are unclear

### ISSUE THREAD

**Issue by eloquence** [integrations/slack#1382]
From the README:
> Mentions will work only if you login to GitHub app in your Slack workspace. When you login to GitHub app with your GitHub id, we map it with your Slack id and ping you in Slack whenever you are mentioned in any of the GitHub notifications.

What does that mean exactly? How does an ordinary user "log into their GitHub app in their Slack workspace"? What instructions should we give our users to set up mentions?

**Comment by apurva1112** [comment]
@eloquence thanks for asking.

> Mentions will work only if you login to GitHub app in your Slack workspace.

Mentions will not work for users who have not connected their github account to slack account via `/github signin`.

> When you login to GitHub app with your GitHub id, we map it with your Slack id and ping you in Slack whenever you are mentioned in any of the GitHub notifications.

We create a mapping of user's github id to slack-user id which is used to mention the user.

Also now mentions are supported only for one workspace/enterprise for a particular user. Hence the latest signin via `/github signin` must be done from workspace/enterprise where the user wants to see mentions. If the user still does not see mentions, please ask him/her to run `/github signin` and signin.

**Comment by eloquence** [comment]
Thanks! I would suggest clarifying this in the README, it wasn't at all clear to me that `/github signin` was even a thing. 

Unfortunately, given the broad permission ask to "act on the user's behalf", this is probably a no-go for our purposes - it would be nice if it was possible to map usernames in a manner that doesn't require granting this permission.
