### ISSUE TITLE
Release reporting feature is inconsistent

### ISSUE THREAD

**Issue by pkit** [integrations/slack#1385]
**Describe the bug**
Release can both include and exclude actual release message for different releases or repos.

**To Reproduce**
Subscribe to "releases"
Observe that sometimes release message is included in the slack notification, and sometimes it's not.

**Expected behavior**
Either always include or always exclude the release message.
It's impossible to know if something changed.

**Comment by aasiddiq** [comment]
@pkit There was an issue which prevented the release message being pushed as a part of notification. This is fixed now, please let us know if still see this issue.

**Comment by sushmita-m** [comment]
@pkit  this should be fixed now. Let us know if you still facing the issue.
