### ISSUE TITLE
The body of a review comment is no longer shown

### ISSUE THREAD

**Issue by helixbass** [integrations/slack#1386]
**Describe the bug**
Notifications for comments submitted as part of a PR review are no longer showing the actual comment, which is entirely unhelpful when scanning the notifications

**To Reproduce**
Presumably,
1. `github subscribe some/repo [...] comments`
2. submit a PR review to that repo that includes some comments
3. see that the Slack notification for those comments no longer includes the body of the comment

**Expected behavior**
The Slack notification corresponding to those comments should show the body of the comment as that makes the notification/scanning the notifications from a submitted PR review far more valuable

**Screenshots**
How it used to look (apparently as of just a couple days ago): 
<img width="534" alt="Screen Shot 2022-04-25 at 1 12 34 PM" src="https://user-images.githubusercontent.com/440230/165139484-6ec1a28f-a932-49be-81b8-3d136a908070.png">
How it looks now: 
<img width="573" alt="Screen Shot 2022-04-25 at 1 07 13 PM" src="https://user-images.githubusercontent.com/440230/165139559-32e040ea-3c24-4978-9722-8a561bd14a77.png">

**Desktop (please complete the following information):**
 - OS: MacOS v12.0.1
 - Browser: Chrome
 - Version: 99.0.4844.83

**Comment by prees1** [comment]
Can confirm we are also seeing the same change in behaviour.

ChromeOS / Chrome - Version 100.0.4896.133 (Official Build) (64-bit)
but same for my teammates on MacOS.

**Comment by emo-slido** [comment]
I'm not sure if this is related but notifications about releases are also missing body. They used to include **What's Changed** followed by the list of PRs being released and this is now gone.

**Comment by pjhjohn** [comment]
Same here.

But I've found some differences below:
- Reviews including Approve/Comment/Request Change are displayed
- Comments by GitHub Actions are displayed

**Comment by tachibanayu24** [comment]
Same here.
And It also occurs in releases.


![Screen Shot 2022-04-26 at 18 20 48](https://user-images.githubusercontent.com/23476543/165267930-ca78ae66-859e-428e-8663-0bfbae883b5f.png)

**Comment by daBack** [comment]
Same issue for us, the tag is shown, however the body from the release is missing.

**Comment by dardaiin** [comment]
Same issue for us as well..

**Comment by zxczoxc125** [comment]
same

**Comment by zxczoxc125** [comment]
same

**Comment by mkamioner** [comment]
This looks fixed to me! Anyone else seeing this?

**Comment by aasiddiq** [comment]
This should be fixed now. Please raise let us know if you are still seeing the issue
