### ISSUE TITLE
Can it mirror github notifications inbox?

### ISSUE THREAD

**Issue by wkjung** [integrations/slack#1402]
**Is your feature request related to a problem? Please describe.**
Is it possible to get slack notifications for all unread GitHub notifications in the inbox (in https://github.com/notifications) so that it's like mirroring the inbox?  

For example, when I comment on some other repo's issue I get a GitHub inbox notification but I see no slack notification, even with scheduled reminders being turned on for every check option, I mean all options under `Enable real-time alerts`. Is it possible to get notifications for such cases?

**Comment by ashokirla** [comment]
@wkjung if you are referring to get reminded about a slack message in your email inbox, we don't have that support in our app. The goal of GitHub app in slack is to enable users to track status updates real time and move away from overflowing email notifications.

**Comment by ayohdev** [comment]
I wanted to chime in to say pulling in all the GitHub users notifications from the inbox would be great.

My team and I are missing notifications because not everything comes through slack

**Comment by joeyaiello** [comment]
+1, just did a ton of work to clean up my watching / subscriptions / notifications in the UI, and now it looks like there's no way to take advantage of that work in the Slack app. 

> if you are referring to get reminded about a slack message in your email inbox, we don't have that support in our app. The goal of GitHub app in slack is to enable users to track status updates real time and move away from overflowing email notifications.

We're not talking about email inbox here, we're talking about the Notifications inbox here: https://github.com/notifications

**Comment by tinderryan** [comment]
+1 here. If the Slack integration can accurately mirror the GitHub inbox, email notifications can be turned off. However right now subscribing to a repo sends through all updates, regardless of whether it is relevant to you specifically (which is what GitHub notifications does)

**Comment by jawache** [comment]
Just to chime in, I thought this is what it would give us. Make slack the dashboard for all your work (this is how other integrations work for slack). So +1 to this request.

**Comment by fokot** [comment]
+1

**Comment by eqperes** [comment]
+1 
My criterion to pay attention to notifications are much more personal (if I am mentioned across multiple repositories) rather than by repository.

**Comment by joeddav** [comment]
+1. I had to set up email forwarding for Github notifications to a private slack channel so that I wouldn't miss things. It's crazy that email is still the only real way to get GH notifications in 2025.
