### ISSUE TITLE
Comments subscription does not work.

### ISSUE THREAD

**Issue by youngrok** [integrations/slack#1409]
**Describe the bug**
Our team has been using github subscription of comments successfully, but after github down a few days ago it does not work anymore. We've tried re-subscribe comments, but it doesn't work.

**To Reproduce**
1. In our slack channel, type this. `/github subscribe our_repo comments`
2. Comment on a commit.

**Expected behavior**
The comment should be notified in the slack channel, but nothing happens.

**Screenshots**
Nothing

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 102

**Smartphone (please complete the following information):**
None

**Additional context**
We suspect recent downtime of github may affect this problem.

**Comment by skeetmtp** [comment]
same here, was OK before github down

**Comment by danielschuetter** [comment]
we have the same problem

**Comment by aasiddiq** [comment]
@youngrok @skeetmtp @danielschuetter @josejbracho We have deployed a fix for this. Feel free to reopen if you still see this issue
