### ISSUE TITLE
GitHub to Slack app notifications are received with over 2 hours delay

### ISSUE THREAD

**Issue by etalaevsky** [integrations/slack#1411]
Hi,

Recently today we started to face some unexpected behavior with GiHub Slack app.

We're getting PR, merge, create branch and etc. messages from GitHub to Slack via the app with ~2 hours delay.

The scheduled reminders to the Slack affected as well.

This issue started just today around 5PM GMT+2 and still ongoing

Example (see attached screenshot):

There is some test event I triggered on GitHub. Looking at the timestamp when I actually created the issue - Today at 19:40

<img width="1120" alt="slack-notification" src="https://user-images.githubusercontent.com/100682996/171056960-c82b658c-1d0b-43d8-aef1-0856b3afd003.png">

Looking at the timestamp when I actually received notification on this event - 22:13 which is over 2 hours.

As we check with Slack support, apparently they received certain request from GitHub with delay - Monday, May 30, 2022 @ 19:13:09.708 UTC and this is basically when we see the notification on our channel.

Please advise.

**Comment by etalaevsky** [comment]
We still have this issue ongoing. @snankani Any thoughts?

**Comment by llcro** [comment]
+1 notifications are delayed. Beginning 30th May.

**Comment by etalaevsky** [comment]
Following the ticket with the GitLab support, it looks like the issue has been resolved.
