### ISSUE TITLE
Mention is not working

### ISSUE THREAD

**Issue by syossan27** [integrations/slack#1412]
**Describe the bug**

Mentions of some users do not work.
Mentions did not work after doing `/github signin` .

**To Reproduce**
1. Do `/github signin`
2. Click 'Connect GitHub account'
![スクリーンショット_2022-06-01_15_33_51](https://user-images.githubusercontent.com/910446/171599247-7c13ba1c-c890-4a42-818d-e5be076498d7.png)

<img width="599" alt="image__1_" src="https://user-images.githubusercontent.com/910446/171598670-45683717-c35a-4a08-b0c9-e928a50df9eb.png">

4. Comment on an Issue with a Mention.
5. See error
<img width="334" alt="スクリーンショット_2022-06-02_18_24_19" src="https://user-images.githubusercontent.com/910446/171599808-1db9d9cf-1c78-4691-ba60-12083901d036.png">

**Expected behavior**
Must be converted from a GitHub username to a Slack username.

**Desktop (please complete the following information):**
 - OS: macOS BigSur
 - Browser: Chrome
 - Version: 101.0.4951.64（Official Build）（arm64）

**Comment by jeetmehta13** [comment]
Hey @syossan27, thanks for reaching out. Just to ensure, the person that has been mentioned in the comment is signed in as well right? Also, does this happen every time or sometimes the GitHub username is converted to Slack username?

**Comment by syossan27** [comment]
@jeetmehta13 
Thank you for your reply.

> the person that has been mentioned in the comment is signed in as well right?

Yes, this user is also signed in.

> Also, does this happen every time or sometimes the GitHub username is converted to Slack username?

It was never converted.
By the way, all but this user have been converted.

**Comment by jeetmehta13** [comment]
@syossan27 can you ask the user to run `/github debug` command and send us the result?

**Comment by syossan27** [comment]
@jeetmehta13 

The following is the result of running `/github debug`.
Some information is hidden.

```
{
  "team_id": "T0C3PN65R",
  "team_domain": "[team_domain]",
  "user_id": "U02KQJ5RHQ8",
  "channel_id": "D0398N455MH",
  "channel_name": "directmessage",
  "text": "debug",
  "enterprise_id": "ECGMXES68",
  "enterprise_name": "[enterprise_name]"
}
```

**Comment by jeetmehta13** [comment]
@syossan27 Does this happen only for issue comments for the user, or do their username not get converted for any event

**Comment by jeetmehta13** [comment]
@syossan27 according to my investigation, it seems that the particular user's GitHub handle was not mentioned for any event that the app has been subscribed to, after they have signed in. 

Can you ask the user to follow these steps and so I can know with certainty they were signed in when the username was not converted:

1. Sign out by running `/github signout` command
2. Sign in by running `/github signin` command
3. Perform an event in the subscribed repo (like creating an issue or commenting) with a mention (`@`) to the GitHub user.

The resulting notification on Slack should convert their GitHub user id to Slack user id. If it does not, it will at least help me to investigate the issue better. 

Thank you for your assistance.

**Comment by syossan27** [comment]
@jeetmehta13 
Thanks for doing the research.
I did the `/github signout` and `/github signin` as you said, then I mentioned it in a GitHub issue comment, but it didn't convert.

Is there anything else we can do here?

**Comment by jeetmehta13** [comment]
@syossan27 just for clarification, did you do the sign out and sign in or the user who is not getting mentioned. Also, conversion will not happen for older messages.

**Comment by syossan27** [comment]
@jeetmehta13 
Sorry for being unclear.
The user who is not getting mentioned did `/github signout` and `/github signin` .

**Comment by jeetmehta13** [comment]
@syossan27 I am sorry but I do not see any at mentions for the particular GitHub user ID connected to the provided Slack user Id `U02KQJ5RHQ8`, I would need the GitHub username of the account that is being mentioned and not getting converted to be able to debug any further.

**Comment by syossan27** [comment]
@jeetmehta13 
Understood. Here is the GitHub username for the user not mentioned.
GitHub username: ayanoItoQA

Thank you for your patience and please continue to investigate.

**Comment by jeetmehta13** [comment]
@syossan27 Thank you for bringing this to our attention. I have identified the bug and will let you know when it gets fixed.

**Comment by syossan27** [comment]
@jeetmehta13 
Thank you for your research as well ! Please let us know when it has been corrected.

**Comment by jeetmehta13** [comment]
@syossan27 thank you for your patience, we have fixed the bug and `@` mentions should be working as intended.

**Comment by syossan27** [comment]
@jeetmehta13 
We have confirmed, @mentation is working as intended.
Thank you for your research and fixed!
