### ISSUE TITLE
Notification for comments & approval of PRs

### ISSUE THREAD

**Issue by Noy** [integrations/slack#1415]
**Is your feature request related to a problem? Please describe.**
Feature related

**Describe the solution you'd like**
Upon approving a PR, the slack integration should notify the desired chat that it has been approved and ready to be merged.
OR, when comments are made on the PR or a "review" has started, notifications should appear display this to the chat 

Thanks for considering!

**Comment by ashokirla** [comment]
@Noy We already have this support. These notifications are available as part of the feature 'reviews'. This is not a default enabled feature. However, you can enable it for your repo explicitly by running /github schedule <org/repo> reviews.
