### ISSUE TITLE
Mojibake in notifications

### ISSUE THREAD

**Issue by shogo82148** [integrations/slack#1416]
**Describe the bug**

I got [Mojibake](https://en.wikipedia.org/wiki/Mojibake) on notifications from 2022-06-20 10:42 UTC

**To Reproduce**

1. Go to a channel on Slack
2. Enter `/github subscribe shogo82148/psychic-tribble` to subscribe notifications
3. Go to the new issue page e.g. https://github.com/shogo82148/psychic-tribble/issues/new
4. Enter "こんにちは世界" into the title
5. Click on "Submit new issue"
6. Go to the channel and see the notification message

**Expected behavior**

I wanted "こんにちは世界" on the notification, however I got "ããã«ã¡ã¯ä¸ç".

**Screenshots**

The issue on GitHub:

<img width="928" alt="image" src="https://user-images.githubusercontent.com/1157344/174617073-b5655e90-21f8-41de-8ba9-d8f5855dfe05.png">

The notification on Slack:

<img width="378" alt="Notification on Slack" src="https://user-images.githubusercontent.com/1157344/174615721-5777be03-2db8-485b-8925-fc490c9184bc.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Firefox
 - Version: 101.0.1

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by techinpark** [comment]
same issue in korean

**Comment by ka2n** [comment]
it seems like:

```
>>> u"こんにちは世界".encode('utf-8').decode('latin-1')
'ã\x81\x93ã\x82\x93ã\x81«ã\x81¡ã\x81¯ä¸\x96ç\x95\x8c'
```

**Comment by yongsk0066** [comment]
same issue in korean too

**Comment by shogo82148** [comment]
It looks to be fine. Thank you for quick fix!

<img width="347" alt="image" src="https://user-images.githubusercontent.com/1157344/174735070-ea19a481-116f-4db3-92dc-b57e5892ea5d.png">
