### ISSUE TITLE
Slack integration showing private information in org

### ISSUE THREAD

**Issue by hanbollar** [integrations/slack#1418]
**Describe the bug**
Maybe this is a question as well if there's a way already to do this, but I couldnt figure out from the org settings how to clarify it for the slack integration.

We're using the slack integration to keep track of general org notifications, issue creations, etc.

repo A: private to all users in an org
repo B: private to select users in an org

Have an org with both A and B. 

When subscribing to the org using the slack integration, users who have access to the org get notifications from both A and B even if they dont actually hv access to B

**To Reproduce**
1. have an org where there's users in the org who dont have access to every repo
2. have the user subscribe to the entire org on the slack integration
3. try creating an issue in A and B and see that both notifications pop up for the user even if they dont have access to B

**Expected behavior**
A user who doesnt have access to B even if they have access to the org, should not be getting notifications about B

**Screenshots**

**Desktop (please complete the following information):**
 - OS: slack integration on mac, windows

**Comment by anuraag016** [comment]
Hi @hanbollar 
We do have a check for such a scenario where we don't post notifications from repos that the user does not have access to. We have tried to repro the scenario, but have been unsuccessful in the same. Could you provide more information to help debug this further.

**Comment by anuraag016** [comment]
> Hi @anuraag016 for sure! what other information would be helpful to assist with this?
> 
> Some screenshots for ref::
> 
> my slack (I have access to thinking cats) ![image](https://user-images.githubusercontent.com/19377312/176728555-972d561d-894b-4d55-aec6-ebcdaeeef5e1.png)
> 
> other user's slack (they dont have access to thinking cats though they do have access to the org as a whole)(time is bc theyre in a different time zone) ![image](https://user-images.githubusercontent.com/19377312/176728701-a97da2d3-5334-4141-bdd9-33cb20f99b2b.png)
> 
> And this only started happening once this other user subscribed to the whole organization on the slack integration

Hi @hanbollar 
This looks like a permission thing, there is a `Base Permissions` field under `Member Privileges` for an org, which if set to anything other than `No Permission` will allow all members of the org to access private repos as well. 
Can you confirm that the `Base Permissions` setting for your org is set to `No Permission`.
To check this admin/owner of the org can go to: Org Settings -> Member Privileges 
Screenshot for reference:
![image](https://user-images.githubusercontent.com/10517819/176853699-1315da25-c6f9-41ff-893a-a62d359856e2.png)
 
 If this is the case, setting the base permission settings to No permission should fix this, allow few minutes for the change to propagate after changing the setting to No Permission. 
 Do let us know if the issue still exists or if this does not help.

**Comment by hanbollar** [comment]
Hi @anuraag016,

Thank you for the insight - We currently have base permissions set to `read`

However, just to confirm for clarity of understanding before i change it over to `no permission`

- we want all users in the org to still be able to access private repos in the org _except_ for the one or two of those private repos that are additionally restricted to a select few members
- in the private repos that have the additional restrictions, i've confirmed that it just has `Collaborators and Teams` as just the specific people who need access to it
- in all other private repos in the org, i've confirmed that it has `Collaborators and Teams` set to every user in the org

Will this still work by switching the base member privileges over to `no permission` given that we still want all users in the org to be able to access all private repos _except_ the few that have the additional specified restrictions?

If this is the fix, as a question for future understanding when i'm setting up some of these permissions, why is the org permission taking precedent over the individual repo permissions for this? and/or should i always just revert to absolutely no permissions for the org and just go on a repo-by-repo case basis?

Thanks for the assistance ~

**Comment by anuraag016** [comment]
Hi @hanbollar 
> Hi @anuraag016,
> 
> Thank you for the insight - We currently have base permissions set to `read`
> 
> However, just to confirm for clarity of understanding before i change it over to `no permission`
> 
> * we want all users in the org to still be able to access private repos in the org _except_ for the one or two of those private repos that are additionally restricted to a select few members
> * in the private repos that have the additional restrictions, i've confirmed that it just has `Collaborators and Teams` as just the specific people who need access to it
> * in all other private repos in the org, i've confirmed that it has `Collaborators and Teams` set to every user in the org
> 
> Will this still work by switching the base member privileges over to `no permission` given that we still want all users in the org to be able to access all private repos _except_ the few that have the additional specified restrictions?

Yes, given the above conditions mentioned, it will still work as expected. 


> 
> If this is the fix, as a question for future understanding when i'm setting up some of these permissions, why is the org permission taking precedent over the individual repo permissions for this? and/or should i always just revert to absolutely `no permission`s for the org and just go on a repo-by-repo case basis?
> 
> Thanks for the assistance ~

The base permission of an org is the minimum possible access a member of the org would have, you can override the base permission only by giving a _higher_ access permission to members for repos or by adding them to certain teams or by changing their roles. Essentially, not having members in the `collaborators and teams`  does not take away the permission level they have due to the base permission. Admin can only provide higher permission than the base permission by adding or removing members from certain teams and/or changing their roles. For the use case described above, my suggestion would be to go on a repo-by-repo case basis.

Hope this helps. 
For further information on the same: https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/setting-base-permissions-for-an-organization

**Comment by hanbollar** [comment]
ooooh interesting, that's good to know

thanks for the help @anuraag016 that clears up my question

hope you have a good weekend ~
