### ISSUE TITLE
Improve UX of Slack deep link

### ISSUE THREAD

**Issue by wilhelmklopp** [integrations/slack#142]
Context: https://github.com/github-slack/app/pull/128#discussion_r153640532

>@bkeepers: What happens if the user doesn't have the desktop app installed? We don't necessarily need to solve that in this PR, but may want to open an issue about making this a better UX later since this could be the users first interaction with the app.

Options: 
- Redirect to app, as opposed to the channel, which is possible via regular http, as opposed to a deep link: https://api.slack.com/docs/deep-linking#app_or_bot
- Instead of redirecting straight away, render a page that explains that everything is ready to go and the user should return to Slack. This page can include an "Open Slack" button that folks who do have the desktop app installed can click, which will direct them back to the team and channel that kicked off the auth flow.

**Comment by bkeepers** [comment]
This was fixed by switching to this everywhere: https://api.slack.com/docs/deep-linking#slack_apps
