### ISSUE TITLE
amitmithila9 invited you to work together in Slack

### ISSUE THREAD

**Issue by a91896** [integrations/slack#1430]
👋 Let’s work together in Slack.

We can use the channel #g7cd104245b to discuss details, share files, and get work done.

Join here: https://join.slack.com/share/enQtMzgxMDkzNzQ2MDA1Mi1jY2MyNWY3YzM5YTNhNWJhNWJjMzE4NTg3NzFmN2Q3ZGI4ZTcxNzI1MmMzYTY0NTM1ZDM1MjBlZGEwMjA4MTc1

**Comment by aasiddiq** [comment]
Feel free to re-open the issue with more relevant details
