### ISSUE TITLE
What is the comment "1" that occurs every time a PR is merged?

### ISSUE THREAD

**Issue by heeseon87** [integrations/slack#1432]
**Describe the bug**
When a PR is merged, a comment of "1" is always displayed.

**To Reproduce**
1. Integrate github with slack.
2. open PR (using intelliJ ultimate 2022.1.4)
3. merge
4. See comment "1"

**Expected behavior**
I haven't commented, so I expect no comments.

**Screenshots**
<img width="463" alt="스크린샷 2022-07-21 오후 2 02 22" src="https://user-images.githubusercontent.com/3926609/180133760-512aef25-b063-44a0-bdc5-26ed8978e537.png">

**Desktop (please complete the following information):**
 - OS: mac 12.4
 - IDE: intelliJ ultimate 2022.1.4 (PR tool)

**Comment by nikhilgarg1047** [comment]
Hi @heeseon87 - We will look into it and update you.

**Comment by aasiddiq** [comment]
@heeseon87 the `1` mentioned below the `Comments` is the number of comments in the PR and no the actual comment text.

**Comment by heeseon87** [comment]
@aasiddiq Thank you.
