### ISSUE TITLE
Issue/PR links broken in Slack all of a sudden

### ISSUE THREAD

**Issue by archon810** [integrations/slack#1478]
**Describe the bug**
Out of the blue, at least on Windows Slack, github linkage is broken and shows up with broken formatting.

![image](https://user-images.githubusercontent.com/469543/192399159-c25ecede-bdbe-4b60-afc7-111aed19819f.png)

Did Slack break this or Github?

**To Reproduce**
Comment on an issue or PR, for example.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by archon810** [comment]
I also reported this to Slack in case they broke it.

**Comment by stefafafan** [comment]
This seems to happen for my Slack for Mac app as well, but not for the Web client ( https://app.slack.com/ ) via Chrome.

**Comment by mochadwi** [comment]
> This seems to happen for my Slack for Mac app as well, but not for the Web client ( https://app.slack.com/ ) via Chrome.
> 
> Nevermind, I reloaded the Slack App and now it seemed to be fixed for me.

after refreshing slack app in the mac also works for me, I thought this is issue in the github integration :pray:

**Comment by Machineric** [comment]
> This seems to happen for my Slack for Mac app as well, but not for the Web client ( https://app.slack.com/ ) via Chrome.
> 
> Nevermind, I reloaded the Slack App and now it seemed to be fixed for me.

I'm still getting the broken links even after reloading the Slack app (MacOS).
does anyone have any clue if this is about Github integration or just Slack acting up?

**Comment by archon810** [comment]
Looks like it's a Slack issue. https://status.slack.com/2022-09/ca18055bcf82c232

**Comment by sanjeev9160** [comment]
@archon810 I can see that the issue has been resolved. Can you please check if the issue has been resolved or not?

**Comment by blue-hope** [comment]
still has problem on Mac slack

**Comment by sanjeev9160** [comment]
> Still has problem on a Mac slack

@blue-hope Try force reloading Slack.

**Comment by blue-hope** [comment]
fixed, thanks
