### ISSUE TITLE
Failed integration authorization loop

### ISSUE THREAD

**Issue by KadeerAmin** [integrations/slack#1487]
**Describe the bug**
When I click the `Connect Github Account` button, I am redirected to a page with the following text:

> Error: The time window to connect your GitHub account has expired. Please return to Slack to re-start the process of connecting your GitHub account.

**To Reproduce**
1. Go to github app within slack
2. Click on `Connect Github Account`
3. See above error

**Expected behavior**
I expect to see a github page where I can give the github app permission

**Screenshots**
<img width="1811" alt="image" src="https://user-images.githubusercontent.com/21316846/194101360-261549fd-2634-4c1e-8886-a5af794d2e60.png">

**Desktop (please complete the following information):**
 - OS: iOS 11.2.3
 - Browser: chrome
 - Version: chrome version 104.0.5112.101

**Additional context**

**Comment by lucas-tumblbug** [comment]
I have same isuue too. Any news?

**Comment by tiffany-yang-stat-recovery** [comment]
@KadeerAmin @lucas-tumblbug I was having the same issue until I tried sending a `/github signin` command which worked for me. https://github.com/integrations/slack/issues/326#issuecomment-1185632204

**Comment by KadeerAmin** [comment]
Thanks @tiffany-yang-stat-recovery, this resolved it for me as well. Closing this issue!
