### ISSUE TITLE
Stop to mention to user who created or commented on issues

### ISSUE THREAD

**Issue by kyoh86** [integrations/slack#1501]
**Is your feature request related to a problem? Please describe.**
When I created issues or commented on them, slack app mentions to me.
But I know that I did them of course.
In addition, recently, issue comments are posted as thread posts of their issue creation post. It makes them more noisy.
I want to know about only anybody mentions to me on GitHub, but all comments will be notified.

**Describe the solution you'd like**
Don't mention to doer, but just describe it as plain-text.

Now: 
```
Created by @kyoh86
```

I want:
```
Created by kyoh86
```

**Describe alternatives you've considered**
If anybody needs those mentions, prepare an option to enable/disable it.

**Comment by ashokirla** [comment]
@kyoh86 Thanks for your feedback.

We have introduced threading for issues with two major objectives.
1. Introduce a collaborative issue experience where relevant users can see all the context and perform actions. 
2. Reduce the number of notifications posted to the channel as it is making the channels pretty much unusable for any other collaborative activities.

The reason we need to mention the user in the title (i.e. created or commented) is to ensure those who are part of the issue conversation get notified whenever a reply is added to the thread. If we don't mention the creator of the issue, slack threads will consider any updates happening in the thread not related to the user who created it. We believe, an issue creator should know what new comments or updates happened to the issue that he/she created. This logic is similar to what we see with 'watching' in GitHub.com. 

We are following up with Slack to findout if there is any way to suppress mentions for creator/commentor but still inform the user about the updates happening in the thread.

**Comment by ashokirla** [comment]
Okay, thanks for the feedback. We will look into it and get back to you with any alternatives.

**Comment by pastak** [comment]
I feel this is a too sudden and large breaking change 😨  I completely agree with @kyoh86 👍 

I cannot catch up with my teammates' discussions without accessing issues/p-rs one by one on github.com.

**Comment by pastak** [comment]
In my case, I read roughly all of posts on a channel by this integration to get an overview of current our repositories' status ( new issue/pr, hot discussion, finding words that concerned me ...etc). So this reducing( or putting together in thread ) is inconvenient for me.

I wish to disable threading...

**Comment by jackmcdade** [comment]
Yeah all the constant pings are going to get old FAST.

**Comment by ashokirla** [comment]
Hi 👋 ,

We have now made change to ensure the issue creator or commentor doesn't get mentioned in the notification. You will get mentioned only if you are assignee or someone mentioned you in the issue comment. If others want to track the updates in the thread, they can go to the thread and choose 'get notified about replies'

Thanks 🙏

**Comment by hampelm** [comment]
Hi team, Thank you for making this change! The notifications were distracting our whole team -- much appreciated. Some ability to turn notifications off would be very helpful.

**Comment by ashokirla** [comment]
Closing this issue for now.
