### ISSUE TITLE
Handling updates with breaking changes

### ISSUE THREAD

**Issue by erquhart** [integrations/slack#1511]
**Describe the bug**
Moving comments to threads was a breaking change for us. We rely on in-channel notifications whenever there's activity on an issue, and these notifications were removed without notice (I expect most users don't check this repo regularly for updates). This resulted in multiple day delays in customer conversations where we didn't know we were missing notifications.

More specifics on how this was breaking: before this change, every GitHub issue comment resulted in a Slack notification. After this change, the notifications were removed. This is because threads only notify if you're mentioned or have commented in the thread, and neither is generally the case for us.

**Expected behavior**
Breaking changes should be very well communicated and opt-in - in this case, making this configurable and leaving it off for existing installations would have worked.

I'm opening this to raise visibility around how certain changes to the GitHub Slack integration can have negative consequences that go beyond folks' preferences and optimization strategies. This had real impact for us. Any help to ensure against this in the future is appreciated.

**Comment by pombredanne** [comment]
For reference this is related to sea of negative feedback reported in https://github.com/integrations/slack/issues/1500

**Comment by ashokirla** [comment]
Hi 👋 ,

We have added a new feature that will enable you to also publish the comment notifications to channel. Refer to the documentation [here](https://github.com/integrations/slack/blob/master/README.md#threading).

You need to just run /github subscribe org/repo comments:"channel"
