### ISSUE TITLE
Please guide us to the private preview of GitHub Integration for Slack at GHES

### ISSUE THREAD

**Issue by s4ichi** [integrations/slack#1529]
Hi, We want to try the GitHub Integration for Slack with GHES support (I know it is a private preview).
We are currently using version 3.6.3 and are ready to use the integration.
https://github.com/integrations/slack#ghes---private-preview

**Comment by ashokirla** [comment]
@s4ichi Can you reachout to us at chatops@github.com

**Comment by s4ichi** [comment]
@ashokirla Thanks for the guidance. I sent an email to chatops@github.com on 12/15, and included this issue in the text. Have you had a chance to check it out?

**Comment by s4ichi** [comment]
I have upgraded to GHES 3.8 and the functionality is now available, so I have done what I wanted to do with this issue. Thank you for the guidance.
