### ISSUE TITLE
Merged PRs reported as Closed PRs to Slack

### ISSUE THREAD

**Issue by slkatsqsp** [integrations/slack#1533]
**Describe the bug**
Very occasionally (3 times so far this month), when a PR gets merged in our repo, the Slack integration reports it as having been Closed. Interestingly, when this happens, the colored status bar appears not as the expected merged-purple or closed-red but open-green.

**To Reproduce**
Unfortunately we haven't found any pattern to help reproduce the circumstances under which this happens, but happy to provide any additional metadata necessary for tracking this down.

**Screenshots**
Two PRs merged within minutes of each other, one reported correctly and the other not:
![Screen Shot 2022-11-14 at 2 49 29 PM](https://user-images.githubusercontent.com/63611908/201752257-9f8c9640-6f0d-46b0-b464-8b5abcad4a4f.png)

Corresponding action on the Github side:
<img width="591" alt="Screen Shot 2022-11-14 at 2 50 09 PM" src="https://user-images.githubusercontent.com/63611908/201752387-a3a61bce-12fb-46f7-84e3-537c908fc10c.png">

More recent occurrence:
![Screen Shot 2022-11-14 at 2 52 10 PM](https://user-images.githubusercontent.com/63611908/201752797-93a23583-9bdd-4839-adb6-b2c14cf860dd.png)
Github merge:
<img width="586" alt="Screen Shot 2022-11-14 at 2 52 44 PM" src="https://user-images.githubusercontent.com/63611908/201752914-b69967cd-5eb5-4e1a-81eb-96f4a7a8b17c.png">

**Comment by sanjeev9160** [comment]
@slkatsqsp Thanks for reporting the issue. `Was the PR reopened and closed immediately?` for such kind of PRs.
Also, I tried debugging the issue, but unable to repro the issue on our side. Gone through the code as well, which looks okay. There is only one way we can get this issue if we receive some inconsistent state in the payload which we receive to process the event. 
I am following up with pull_request team to  see if there is some issue in the generated payload which we use to post the notification card. Thanks.

**Comment by slkatsqsp** [comment]
> `Was the PR reopened and closed immediately?` for such kind of PRs.

@sanjeev9160 Nope, these PRs were simply approved and merged (and the branches automatically deleted, if that makes any difference). The close/reopen flow notification works just fine:
<img width="562" alt="Screen Shot 2022-11-15 at 11 56 55 AM" src="https://user-images.githubusercontent.com/63611908/201979965-115e505e-3ed4-432d-bed7-5cc475c35563.png">

Thanks for following up with the pull_request team... I figured the integration was basically just a passthrough and the problem lies upstream but wasn't sure where else to register the issue.

**Comment by slkatsqsp** [comment]
Thanks @sanjeev9160! Is there somewhere else I can follow along with the investigation?

**Comment by sanjeev9160** [comment]
@slkatsqsp There is an internal issue created for it as one other customer have faced this issue. I have added this problem also from our side. So it is being tracked internally. Also, pull_request team has mentioned that it is a rare race issue so impact right now is low. Feel free to reopen the issue in case if you again face this issue. That way it can help us to follow with the pull_request team to priortize it. Thanks.

**Comment by slkatsqsp** [comment]
Hey @sanjeev9160 it just happened again:

<img width="342" alt="Screen Shot 2022-11-22 at 9 51 25 AM" src="https://user-images.githubusercontent.com/63611908/203345000-1ad5aa2a-b0fb-4241-abbd-7e608e8f11ec.png">


<img width="547" alt="Screen Shot 2022-11-22 at 9 49 54 AM" src="https://user-images.githubusercontent.com/63611908/203344587-0a612832-273a-43d6-9236-c8e6aa5495aa.png">

**Comment by sanjeev9160** [comment]
Thanks @slkatsqsp for informing us. I have added logs on our side too and we notice this kind of issue. We will follow up with the pull_request team to look into it. Given that this week it is Thanksgiving it may take some time. Thanks.

**Comment by mauriciogracia** [comment]
I'm still seeing this issue, when a merged PR is notified it only says that it was CLOSED but never says it was MERGED

I believe is related to this feature that has not been implemented after 5 years of accepting it 
https://github.com/integrations/slack/issues/519
