### ISSUE TITLE
Links are not encoded

### ISSUE THREAD

**Issue by JarrodMFlesch** [integrations/slack#1539]
**Describe the bug**
Links do not encode pound signs.

**To Reproduce**
1. Create a branch called `fix/#1234-some-fix`
2. Push a commit to that branch
3. Click the link in the slack GitHub notification.
4. Opens browser with incorrect link, ex: https://github.com/org-name/project/tree/fix/#1234-some-fix

**Expected behavior**
Link should be https://github.com/org-name/project/tree/fix/%231234-some-fix

**Comment by sanjeev9160** [comment]
Thanks @JarrodMFlesch for informing us. We have resolved the issue. Thanks.

**Comment by JarrodMFlesch** [comment]
Awesome, thank you @sanjeev9160!
