### ISSUE TITLE
Issue template not displaying

### ISSUE THREAD

**Issue by sarahethompson** [integrations/slack#1540]
**Describe the bug**
Even though it's not documented, I thought it was possible to open an issue from slack and use a template from the repo. But no matter what I try I just get presented with the following form:

![Screenshot 2022-11-22 at 11 44 54](https://user-images.githubusercontent.com/9658518/203306055-311c4438-87d6-4465-af52-61f58aef2890.png)

**To Reproduce**
1. type - `/github open <org>/<repo> <template-name>`
2. or type `/github open <org>/<repo>` (should warn that the template name needs to be provided?)
3. Form opens with a blank description (see above)

**Expected behavior**
I had been able to do this previously and I see from other open issues that this should work

https://github.com/integrations/slack/issues/1135
https://github.com/integrations/slack/issues/1338

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by ashokirla** [comment]
@sarahethompson Adding support for choosing templates when creating an issue is currently in our backlog. 

The UI you are seeing now is the new enhanced issue create experience where you can dynamically select repos, labels, assignees, milestones etc. In the next phase of the improvements we want to introduce a way to dynamically select the template you want to use to create issues.

**Comment by sarahethompson** [comment]
@ashokirla that makes sense, thank you!
