### ISSUE TITLE
Slack integration no longer notifies

### ISSUE THREAD

**Issue by aericson** [integrations/slack#1548]
**Describe the bug**
The slack application no longer sends notification. Last notification I got was on November 30th. Another colleague also has the same issue.

When going to https://github.com/settings/reminders and clicking the "send a test reminder" it gives me a 502 Unicorn error page.

**Expected behavior**
A notification would arrive on slack.

**Additional context**
I've already tried removing access to the Slack integration and re-doing the oauth.

**Comment by ashokirla** [comment]
@anuraag016 can you take a look at this issue.

**Comment by bewuethr** [comment]
We see something similar: direct notifications are still coming through, but scheduled reminders for teams seem to be broken; the last successful notification was on Nov 24. Reminders set on org-level still seem to be working.

**Comment by aericson** [comment]
> We see something similar: direct notifications are still coming through, but scheduled reminders for teams seem to be broken; the last successful notification was on Nov 24. Reminders set on org-level still seem to be working.

Yea, we also have issues with the teams notification not working.

**Comment by aericson** [comment]
Seems resolved now. I tried to oauth again and this time it worked.

**Comment by bewuethr** [comment]
For what it's worth, the reason it broke for us was the GitHub app having been removed from the channel in question; adding it back fixed it. Maybe caused by a recent permissions update?
