### ISSUE TITLE
Github Slack integration causing unwanted direct notifications

### ISSUE THREAD

**Issue by AndrejMitrovic** [integrations/slack#1560]
Hello,

Since a recent update to the Github Slack integration app (https://slack.github.com/), the Github slack bot has started sending pull request updates (for example merges) as a thread response. For example:

- Pull request is opened. Github slack bot posts about it in our integration channel
- Pull request is merged. Github slack bot posts a reply as a thread to the previous message

This is causing unwanted Direct notifications in Slack due to the following problem:
- Github slack bot posts about the PR becoming open
- Then the github slack bot responds in a thread to this message when the PR is merged.
- This triggers a direct notification on Slack, likely because the user handle is visible. This is most probably triggered by the user handles in the list of reviewers for that PR.

Could you please make it configurable so the bot doesn't respond in threads? The direct notifications are causing unwanted distractions, and I do not wish to entirely mute our integration channel.

I'm attaching a screenshot of the slack conversation below.
<img width="327" alt="Capture" src="https://user-images.githubusercontent.com/15028641/206352756-7d8dce86-52de-4d91-ac34-33410a554217.png">

Cheers.

**Comment by pjhjohn** [comment]
@AndrejMitrovic You can see new documents about threading in [README#threading](https://github.com/integrations/slack#threading)

Seems you can opt-out this feature by sending `/github settings` and use `Enable threading for Pull Request and Issue notifications.` option. Following image is what I've gone through. Hope this helps

<img width="845" alt="Screen Shot 2022-12-08 at 1 31 32 PM" src="https://user-images.githubusercontent.com/2541685/206356984-beaf2487-b810-4625-abf9-a11da2154069.png">

**Comment by AndrejMitrovic** [comment]
Didn't realize it was there. I'll have a look, thanks!

**Comment by AndrejMitrovic** [comment]
Seems to work, thanks again~
