### ISSUE TITLE
Disabling threading does not actually disable threading

### ISSUE THREAD

**Issue by rickselby** [integrations/slack#1564]
**Describe the bug**
We disabled PR and Issue threading in our slack channel using `/github settings`. A new PR came in, and comments and reviews are still being threaded on the PR post.

**To Reproduce**
1. Send `/github settings` to a channel and disable threading
2. Create a new PR linked to the slack channel
3. Add a comment on the PR

**Expected behavior**
I would expect the comments and reviews to appear as new posts in the channel, not as threaded replies.

**Comment by ashokirla** [comment]
@nikhilgarg1047 Can you look into this issue.

**Comment by ojintoad** [comment]
Howdy, I know an answer earlier today probably would have helped but getting to this now.

1. I really do not know - my org does not use github issues as far as I'm aware and so can't confirm either way.
2. It is happening in both private and public channels. I do not have this operation in any app/bot channels, I'm not even sure I know what this.
3. It is happening in two total channels where I have attempted to have it disabled. One is private, one is public.

**Comment by ojintoad** [comment]
Just to be clear about what we are experiencing, here's a redacted screenshot with an example of the first cased in my steps to reproduce comment. You can see the same PR with a threaded response. 

The Jun 3 date is a little confusing but I think my team member renamed an old draft PR which caused it to get viewed as "opened" by the integration. The same thing is happening on fresh PRs too.

![image](https://user-images.githubusercontent.com/3084796/206806526-e670d827-a113-4d02-a765-6b46812b1e7c.png)

**Comment by kwolf-experian** [comment]
We're seeing this as well. We don't use issues, just PR's Private channel. `/github settings` reports threading is disabled.

I think for us this started early last week?

**Comment by ojintoad** [comment]
FWIW I was holding off trying to resolve by re configuring since I wanted to be able to help by confirming it still reproduces, but I'm going to see if disconnecting and reconnecting the repo resolves this today.

**Comment by ojintoad** [comment]
After unsubscribing and resubscribing the threading seems to now actually be disabled. Based on the implementation, is that a potential expected outcome?

I'm unsure if this is part of a larger change - I did have another channel where threading was still occurring that I didn't unsub/resub so until that one has PR events that reproduce the known bad behavior I'm still not entirely confident it's a workaround. It may be worth trying though for those looking for relief.

**Comment by ojintoad** [comment]
I intentionally confirmed that the behavior in the still previously subscribed thread was behaving as per the bug report still.

I'm going to unsubscribe and resubscribe that as well and see if things also look resolved there.

**Comment by ojintoad** [comment]
Confirmed unsubscribing and resubscribing also resolved the second thread.

I would encourage those seeing this to try the unsub/resub if this is affecting you and the developer investigating to consider if this behavior makes sense based on some setting caching or something else preventing the setting from getting picked up.

**Comment by Stericson** [comment]
Just want to surface that we are seeing the same issue. While unsubscribing and resubscribing may work...it's a potentially tedious process 👎

**Comment by nikhilgarg1047** [comment]
Hi @ojintoad - We have added the additional logging to troubleshoot this issue further. Can you please perform the below steps in the affected channel:

1. Run `github debug` command and share the result.
2. Try to toggle the threading settings using `github settings` command. Please note and share the timestamp of this step.
3. Try to trigger any action that will send notification in the affected channel. Please note and share the timestamp of this step.

The above steps will help us to analyse the logs for this issue. Please let me know in case of any questions.

**Comment by ojintoad** [comment]
@nikhilgarg1047 Respectfully, I no longer have the ability to fulfill your request because as far as I can tell I no longer have an affected slack channel. I realized that was a risk of creating this situation during my testing to confirm that an unsub/resub would repair which is part of why I was so noisy in this issue.

Possibly other parties who have commented such as @Stericson @kwolf-experian @rickselby have an affected slack channel?

I'm not sure what replay-ability slack/github integration maintainers have, but it seems like the full steps to reproduce are actually likely:

1. Have a workspace with a slack/github integration set up with a version from some time before the threading feature was introduced
2. Set up a subscription in a channel and confirm it works without threading by triggering a message
3. Upgrade the integration to a version that supports threading
4. Trigger a message again

I'm pretty ignorant here, so it's possible that it's important to upgrade through each individual version, but you all would know better what's likely.

If I do discover a channel that is affected in my company's workspace I will let you know.

**Comment by Stericson** [comment]
@nikhilgarg1047 

Debug info (10:04am)

`{
  "team_id": "T03HN4GQ7",
  "team_domain": "washpost",
  "user_id": "U0NGPJLEB",
  "channel_id": "GCPAY56ER",
  "channel_name": "privategroup",
  "text": "debug",
  "enterprise_id": "E03RQK5R73M",
  "enterprise_name": "The Washington Post"
}`

Enabled, then Disabled threading. (10:07am)

Created new PR, added comment. Thread created upon commenting (10:14am)

**Comment by nikhilgarg1047** [comment]
@Stericson - Thanks for sharing the information. Can you please check now if the issue is fixed or not?

**Comment by Stericson** [comment]
@nikhilgarg1047 Looks like it's fixed, thanks 👍
