### ISSUE TITLE
When using threading, add the ability to turn off "replied to a thread" notifications that go to the channel

### ISSUE THREAD

**Issue by wrouten-figure** [integrations/slack#1574]
**Is your feature request related to a problem? Please describe.**
Yes. The threading feature is supposed to cut down on traffic in the channel where users that aren't tagged in the PR do not get notified of activity for the PR. What I am seeing is that when an action happens on a PR, it posts in the thread, and also posts that update in the channel. If the whole point of adding threading is to reduce the channel noise why is it posting also to the channel. This is doubling the traffic that tagged PR reviewers see and makes the integration much worse.

**Describe the solution you'd like**
Either remove the "Also send to \<channel\>" functionality for thread responses, or add a configuration to turn off also posting thread responses to the channel.

**Describe alternatives you've considered**
None that I can think of

**Additional context**
If this is somehow a configuration problem that is not related to this integration please let me know, or if there is possibly a way to already turn this off. I checked the documentation around this feature and couldn't find anything regarding this.

**Comment by tonglil** [comment]
Dupe of https://github.com/integrations/slack/issues/1567

**Comment by wrouten-figure** [comment]
Per @tonglil, closing this issue as it's a dupe of https://github.com/integrations/slack/issues/1567
