### ISSUE TITLE
Slack and GitHub integration to create issues on GitHub

### ISSUE THREAD

**Issue by azaveri7** [integrations/slack#1585]

**Comment by aasiddiq** [comment]
@azaveri7 are you facing any issues while creating issues? If so, could you add some more details so I can attempt to help you out. You can also refer to the docs from [here](https://github.com/integrations/slack#readme)

**Comment by azaveri7** [comment]
@aasiddiq I am looking for python snippet code for the below task -

We have a slack channel where we get notifications from failures in production environment Airflow jobs. We want to automate the process to create an issue from these notifications and also check if similar issue persists, do not create a new one. 

Please share documentation regarding the same if you have any.

**Comment by aasiddiq** [comment]
@azaveri7 This seems to be different use case than what this repo is for, we handle the integration between GitHub and Slack to handle notification etc from GitHub and deliver it to the subscribe slack channel.

As I understand from your requirement you are looking to automate the process of issue creation, while this is outside the purview of my team you can leverage the [rest APIs](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#create-an-issue) in your workflow to create issues.

Feel free to open another issue if you need any assistance with Slack and GitHub integration
