### ISSUE TITLE
I have subscribed to to specific branch , but receiving notification for PR of other branches as well.

### ISSUE THREAD

**Issue by taman0753** [integrations/slack#1586]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aasiddiq** [comment]
@taman0753 Could you check what all features are you subscribed to by running the below command. 

```
/github subscribe list features
```
If you see `pulls` in the feature list it means you will get notification for any pull request that is opened for that repo.
If you are looking to get notification for any commits for a specific branch you could use the below command
```
/github subscribe <org/repo> commits:yourbranch
```

you can check more details on the other features and filtering in the documentation [here](https://github.com/integrations/slack#subscribe-to-an-organization-or-a-repository)

**Comment by aasiddiq** [comment]
Closing this since there is not activity on this. Feel free to reopen if you see any issue.
