### ISSUE TITLE
Workflow notifications not working when `run-name` present

### ISSUE THREAD

**Issue by dsantosmerino** [integrations/slack#1589]
**Describe the bug**
Workflows-related notifications are not updated with custom `run-name`.

**To Reproduce**
1. Set your subscription in Slack using the workflow name: `/github subscribe owner/repo workflows:{name:"your workflow name"}`
2. Define the `name` in your workflow with `your workflow name` and then a `run-name` like `Deploy by @${{ github.actor }}`
3. Trigger your workflow
4. Receive only the initial notification with no status nor job updates, stuck as "Queued" for ever.

<img width="537" alt="notification_with_run_name" src="https://user-images.githubusercontent.com/14283216/210360980-34e5e384-922e-458c-9726-3948b8e3286e.png">

**Expected behavior**
With no `run-name`, the Slack notification is updated after changing the status and it also sends new messages in the message thread to update any job status change.

<img width="533" alt="notification_with_name" src="https://user-images.githubusercontent.com/14283216/210361209-dd48edaf-cbf0-4736-9340-2b6d8a13f945.png">

**Additional context**
We tried removing the initial subscription, subscribing again, but same result.

**Comment by sanjeev9160** [comment]
@dsantosmerino By your issue description, I see that if you use a workflow name filter, then you receive an initial notification.  But you don't receive subsequent notification. Can you please try doing these steps:
1. Create a dummy channel for now or some other channel and create a subscription with the workflows and with name filter.
2. Create a subscription with workflows with no filter. 
3. Run the workflow.
4. See if both the workflows card are getting updated or not? Please share what happens when you do this step. Thanks.

**Comment by sanjeev9160** [comment]
@dsantosmerino Thanks for the information. I looked into it and it looks like a bug and we receive a workflow name as run-name in the payload. We will follow-up with the respective team and get it fixed.

**Comment by dsantosmerino** [comment]
Thanks @sanjeev9160! Let me know if you need anything else 😸

**Comment by dsantosmerino** [comment]
Hey @sanjeev9160, do you have any update on this? Thanks!

**Comment by sanjeev9160** [comment]
@dsantosmerino Thanks for the reminder. I will be following up on it and will make sure to get it resolved by early next week.

**Comment by sanjeev9160** [comment]
@dsantosmerino It looks like an issue on our side, we are working on a fix. Will keep you posted on it. Thanks.

**Comment by sanjeev9160** [comment]
@dsantosmerino We have resolved the issue. Please verify it. Thanks.

**Comment by dsantosmerino** [comment]
It works as expected now, thanks @sanjeev9160 🎉
