### ISSUE TITLE
Notifications for Repos Becoming Public Persist Despite Not Being in List of Features

### ISSUE THREAD

**Issue by yhakbar** [integrations/slack#1590]
When subscribed to an organization using a label filter, there doesn't seem to be a way to prevent notifications for certain events like repositories becoming public triggering notifications.

**To Reproduce**

1. Subscribe to an organization with a filter for only specific labels (remove all features that are not relevant to capturing events related to pull requests opened with specific labels). 
2. Run `/github subscribe list features` and see that there is no `public` feature to remove to prevent those notifications.
3. Make a repository public, and see that notifications continue to make their way to the Slack channel.

**Expected behavior**
`public` should be in the list of features that are active, and removable to prevent those notifications.

**Comment by sanjeev9160** [comment]
@yhakbar +label:"your label" is to - Filter issues, pull-requests and comments based on their labels. 
Changing the visibility of a private repo to public is a different event and we don't filter such event based on the `label`. It is only for events related to issues, pull-requests and comments in issues or PRs. 
So we notify the event when a private repo becomes public. Thanks.

**Comment by yhakbar** [comment]
> @yhakbar +label:"your label" is to - Filter issues, pull-requests and comments based on their labels. Changing the visibility of a private repo to public is a different event and we don't filter such event based on the `label`. It is only for events related to issues, pull-requests and comments in issues or PRs. So we notify the event when a private repo becomes public. Thanks.

Thanks for your reply @sanjeev9160 ! What would your recommended workaround be for users looking to subscribe to all pull requests with a particular filter within a Slack channel? I believe if there was a way to unsubscribe from `public` events, we'd be able to achieve this with existing functionality, but we don't know how to avoid notifications regarding visibility changes.

**Comment by sanjeev9160** [comment]
@yhakbar Currently we don't support filtering based on the visibility changes. I will add it into the backlog.
cc: @ashokirla
