### ISSUE TITLE
It's not possible to unsubscribe from workflow

### ISSUE THREAD

**Issue by doichev-kostia** [integrations/slack#1630]
**Describe the bug**
It's not possible to unsubscribe from workflow

**To Reproduce**
1. subscribe to workflows
2. unsubscribe from workflows
3. see no changes

**Expected behavior**
The channel should unsubscribe from the workflow notifications

**Screenshots**
<img width="604" alt="Screenshot 2023-02-15 at 21 01 22" src="https://user-images.githubusercontent.com/72884674/219140011-722ea062-5ae5-4a27-92f5-3d341f7cd2dd.png">

<img width="630" alt="Screenshot 2023-02-15 at 20 52 43" src="https://user-images.githubusercontent.com/72884674/219138709-66a4911e-a527-4053-95d9-6b5246e386ee.png">

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser: N/A
 - Version: MacOS 13.0.1. Slack app: Version 4.29.149
db99c903bf64716002f11fa17deb621f82249077@1676369243 (Production)
 - Device: MacBook Pro, 2021, Apple M1 Max
 
#### Workaround
`/github subscribe <org/repo> workflows:{branch: "non-existing"}

**Comment by aasiddiq** [comment]
@doichev-kostia Thank you for bringing this up, we have identified the issue and deployed a fix for this. Could you please try again and see if you are still facing the issue?

**Comment by doichev-kostia** [comment]
Thanks, working now!

The workflow feature is awesome🤩
