### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by RobQuistNL** [integrations/slack#1634]
**Describe the bug**
Messages don't appear.

**To Reproduce**

1. Type `/github subscribe repo/name` in chat
2. See ":white_tick: Subscribed to [repo/name](https://github.com/repo/name). This channel will receive notifications for `issues, pulls, commits, releases, deployments`"
3. Push new commit to branch which has a PR open
4. See no message

**Expected behavior**
See a message

**Desktop:**
 - Unrelated

**Smartphone:**
 - Unrelated

**Comment by sanjeev9160** [comment]
> 1. Type `/github subscribe repo/name` in chat
> 2. See ":white_tick: Subscribed to [repo/name](https://github.com/repo/name). This channel will receive notifications for `issues, pulls, commits, releases, deployments`"
> 3. Push new commit to branch which has a PR open
@RobQuistNL 
This commit is to the default branch which is usually main/master branch. So in case you are pushing the commit to some other branch then you will not receive the notification. Thanks. more information present in the [documentation](https://github.com/integrations/slack#customize-your-notifications)

**Comment by RobQuistNL** [comment]
But I subscribed to commits?

**Comment by RobQuistNL** [comment]
https://github.com/integrations/slack/issues/1615

**Comment by RobQuistNL** [comment]
Broken again;

/github subscribe repository

Response:
> Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
> Note: You need to be an organization owner to install the app (or ask one to install it for you).

I click "Install Github App" and see all my orgs / users / where i want to install
but it is already installed in the repo I'm trying to add
