### ISSUE TITLE
GitHub to Slack app notifications are delayed irregularly

### ISSUE THREAD

**Issue by longevitytina** [integrations/slack#1640]
**Describe the bug**
We have four team members on our github team, when some members post a PR it shows up immediately on slack, for others it  will not post unless there is an update to the PR

**To Reproduce**
1. Subscribe to organization with additional config `/github subscribe zebrafishlabs/kraken reviews`
2. Unsubscribe to some features: `/github unsubscribe zebrafishlabs/kraken releases, deployments, commits`
3. Configurations are complete with each team member signed-in
4. Posted PR and with assignees as `imgix-frontend` which uses github redrobin to auto select PR assignee from team
5. PR posted immediately for one member with slack mentions attached to the correct assignees, but another PR posted by another member did not post (until it was approved)
6. Sometimes we can make it trigger by closing PR and then reopening (but not always)
7. If I unsubscribe from the repo, resubscribe, close PR, then open PR it might force it post on slack - but not guaranteed.

**Comment by anuraag016** [comment]
Hi @longevitytina 
To help us debug this issue can you please share following details:
- Details about few of these missed/delayed pr notifications. Pr number, when it was opened, which notification was missed or delayed 
- can you also run the `/github debug` command in the channel where you are seeing this issue and provide the output here.

**Comment by longevitytina** [comment]
Hi @anuraag016, thanks for checking this out. Here is an example of delayed PR:

Pr number: https://github.com/zebrafishlabs/web-shared/pull/492#pullrequestreview-1331122786
when it was opened: March 7, 2023 2:44pm PST
which notification was missed or delayed: Pull request opened by ...

Update was added to slack 1 day later when PR was approved: March 8, 2023 9:25am PST

Let me know if you need any more details!

**Comment by anuraag016** [comment]
Hi @longevitytina, 
I looked into this, it seems for this channel and this repo the `pulls` feature is turned off, while the `reviews` feature is turned on, hence it will post only when a review is submitted and nothing will be posted when a PR is opened, closed, merged or reopened. There is an easy way to check if this is the case by running `/github subscribe list features` in the channel to check which all features the subscription contains. 
To add `pulls` feature for the existing subscription you can run the following command: 
`/github <owner>/<repo> pulls` 

Do let me know if this works for you.

**Comment by longevitytina** [comment]
Okay good to know! I feel like I was trying to debug the delay and tried turning off various subscribe settings to see if anything fixed it. I have have turned that setting on for all our repos and hopefully this resolves it. Thank you for looking into, I'll reopen issue if it doesn't resolve the delay 🙏 🤞
