### ISSUE TITLE
Dark square in preview title for a PR which has an ID larger than 100k

### ISSUE THREAD

**Issue by grigorem** [integrations/slack#1646]
**Describe the bug**
We recently passed the 100k number of PRs, and since then, all the Slack previews title shows a dark square between the PR ID and the title. Not sure if this is a bug or if this is the intended behaviour...

**To Reproduce**
Steps to reproduce the behaviour:
1. Have a PR with an ID larger (or equal) than 100k

**Expected behavior**
Have just a plain space between the ID and the title?

**Screenshots**
![Screenshot 2023-03-09 at 16 46 25](https://user-images.githubusercontent.com/6842987/224100360-888b6d18-9752-4797-b4fb-758573a20688.png)
![Screenshot 2023-03-09 at 17 03 50](https://user-images.githubusercontent.com/6842987/224101952-54d344db-bf29-4fda-9548-40e8f9665d67.png)

**Additional context**
It looks the same on the Slack desktop application, browser and mobile app, both in white and dark mode.
I attached two screenshots, one that shows what I mean and the browser inspect for those messages.

**Comment by anuraag016** [comment]
Hi @grigorem 
Thanks for reaching out.  
This display of a colour block is a setting in slack app, which can be turned off, Slack treats `#<6digit>` as hex color code and displays the corresponding colour next to it. 
If you wish to turn the setting off, you can follow these steps: 

https://slack.com/intl/en-in/help/articles/213893898-Change-how-messages-are-displayed
<img width="655" alt="image" src="https://user-images.githubusercontent.com/10517819/224298146-12421ca8-380e-405b-9c96-c30341428e51.png">

**Comment by grigorem** [comment]
![patrick-stewart-facepalm-gif](https://user-images.githubusercontent.com/6842987/224326804-0a9002fe-b87a-4a98-9b64-35776de03e1c.gif)

I knew this was a feature but I didn't make the link. Thanks for taking a look into it!
