### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by moritak40123** [integrations/slack#1694]
#URL
https://protospace-39115.onrender.com

**Comment by moritak40123** [comment]
#URL
https://protospace-39115.onrender.com/

#What
コメント表示対象の修正、ユーザーページの記載修正

**Comment by motomuun** [comment]
@moritak40123 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
