### ISSUE TITLE
Images attached to Github issues are not previewed.

### ISSUE THREAD

**Issue by fullness-java2023** [integrations/slack#1716]
In the past, when I submitted a Github issue with an image attached, the Slack notification would show a preview of the image, but now it does not. Is it possible to preview the image as before?

<img width="657" alt="image" src="https://github.com/integrations/slack/assets/135136917/65632c52-37f3-4f29-a409-d7abe75078b7">

**Comment by alistairholt** [comment]
It really sucks that this doesn't work anymore 😩

**Comment by fullness-java2023** [comment]
@alistairholt thank you. I will re-register this issue as a bug.
