### ISSUE TITLE
Slack link previews cannot be removed by clicking the 'x' on the preview

### ISSUE THREAD

**Issue by kbehlers** [integrations/slack#1799]
**Describe the bug**
When using the [Github Slack App](https://slack.com/apps/A01BP7R4KNY-github?tab=more_info) on Slack for Mac 4.35.126, [attempting to click the 'x' on a link preview ](https://slack.com/help/articles/204399343-Share-links-and-set-preview-preferences#remove-a-link-preview) does not respond. The search bar then also becomes unresponsive, along with other buttons like the workspace switcher.

**To Reproduce**
1. The Github Slack app must be installed, if it is not installed, clicking the 'x' on the preview will work as expected.
2. Paste any Github repo link (e.g. https://github.com/python/cpython) into a slack message and send.
3. Wait for the link preview to display
4. Hover over the link preview and click the 'x' to the left side of the link
  a. The link won't be removed, and no modal to confirm removing the link will appear.
5. Attempt to focus the search bar by either clicking on it directly at the top of page or by pressing `cmd+F` or `cmd+K`
  a. The search bar won't appear

**Expected behavior**
I would expect clicking the 'x' on the link preview to bring up the pop-up to remove the preview, just as it does when the Github Slack app is not installed, and just as Slack does with all other link previews for other sites. I would also expect clicking the 'x' to not disable other functionality within the app.

**Screenshots**
#### This is what happens when I click the 'x' and the Github Slack app is _not_ installed. Notice the darkened background behind the modal.
<img width="465" alt="Screen Shot 2023-11-08 at 10 04 31 AM" src="https://github.com/integrations/slack/assets/43154039/0b6e47de-7bb6-4c21-9db5-b82bb50f2ea1">

#### This is what happens when I click the 'x' and the Github Slack app _is_ installed.

https://github.com/integrations/slack/assets/43154039/1549c180-a5e9-4a10-9b05-d47b5d4996be

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6.8
 - Browser: N/A Slack for Mac desktop app
 - Slack for Mac Version: 4.35.126

**Comment by seredniy** [comment]
+1

**Comment by wayheming** [comment]
+1

**Comment by AndriiSmith** [comment]
+1

**Comment by kbehlers** [comment]
I had also opened a ticket with Slack. They told me it was a known bug and they would notify me as soon as a fix became available. They just notified me the fix had released and reloading Slack should resolve the issue. After reload, removing link previews is now working on my machine using the Github Slack app.

I'll leave this ticket open for a day or two in case anyone else is still impacted.
