### ISSUE TITLE
Not receiving notifications for pull request review comments

### ISSUE THREAD

**Issue by ihollander** [integrations/slack#1911]
**Describe the bug**

We recently stopped receiving notifications in Slack for line-level PR comments, and have noticed some other odd behavior with PR notifications:

- Responding to a PR review comment in a thread: ❌ no notification
- Adding a line-level PR review comment in a review: ❌ no notification
- Adding a line-level PR review comment outside of a review: ❌ no notification
- Adding a standalone (top-level) comment: ❌ duplicate notifications (the same notification sent twice in quick succession)
- Adding a "finish review" comment: ✅ received expected notification

We noticed this change in behavior today. While we didn't make any changes to the subscription settings for one of the repos impacted by this (potential) bug, we did make recent changes to subscriptions for _other_ repos within our organization, in case that information is helpful!

**To Reproduce**

We set up a totally new Slack channel and subscribed to the same repo with comments enabled, and saw the same behavior listed above. Here are the commands we used to configure comment notifications:

```
/github subscribe {repo}
/github subscribe {repo} comments
/github subscribe {repo} reviews
```

**Expected behavior**

- Responding to a PR review comment in a thread: one notification
- Adding a new line-level PR review comment: one notification
- Adding a standalone (top-level) comment: one notification
- Adding a "finish review" comment: one notification

**Screenshots**

Doubled notifications for single top-level comment, single notification for "finish your review comment":
<img width="858" alt="Screenshot 2024-06-10 at 4 13 35 PM" src="https://github.com/integrations/slack/assets/39830572/cb0d4c8c-88f6-4491-9373-12b504a63db9">

<img width="642" alt="Screenshot_2024-06-10_at_4_10_44_PM" src="https://github.com/integrations/slack/assets/39830572/af9f59c1-302b-4310-88c4-9e77f5f21a30">

**Desktop (please complete the following information):**

Using 

 - OS: macOS
 - Browser: n/a (Slack client)
 - Version: Slack version 4.38.125

**Comment by tehsven** [comment]
I also noticed these same issues today.

**Comment by ddellsperger** [comment]
seeing similar strange behavior, including duplication of messages coming to our slack channel and reviews that don't include all of the comments (or final review comment) as part of the review.

**Comment by archon810** [comment]
Same here, all of a sudden duplicate notifications in our channel.

**Comment by danielafcarey** [comment]
We are experiencing the same issue specifically with the `comments` subscription.

Previously:
- `comments` subscription sent Slack notifications for all PR comments including code-level comments/replies and PR-level comments

Now:
- PR-level comments notifications are sent to Slack twice (two identical notifications are sent at the exact same time)
- Code-level comments/reply notifications are not sent at all

Notes:
- We first noticed Monday June 10 around 8am Mountain Time
- We tried unsubscribing the slack channel from comments and resubscribing
- We tried unsubscribing the slack channel from the repo entirely and resubscribing

**Comment by deanylev** [comment]
Can we please get some sort of update on this? We are very reliant on this functionality

**Comment by ihollander** [comment]
This appears to be fixed as of today, we're now receiving the expected PR notifications with no configuration changes on our end - going to close this!
