### ISSUE TITLE
Comments on PRs are being counted as reviews

### ISSUE THREAD

**Issue by gregsdennis** [integrations/slack#1913]
**Describe the bug**
It appears that a recent change is causing comments on PRs to be counted as reviews.  So when I subscribe to both `comments` and `reviews`, I receive two messages per comment on PRs.

This doesn't appear to affect issues, which is what leads me to believe the comments are counted as reviews.

**To Reproduce**
1. Subscribe to a repo and add `comments` and `reviews`.
2. Find a PR in that repo and make a single comment.
3. Look in Slack.  Two messages should appear both indicating the single comment.

**Expected behavior**
Only one message should appear.

**Screenshots**
![image](https://github.com/integrations/slack/assets/2676804/f06222ca-f185-41fb-8990-fccd96d88451)

Note that the first message is a comment on an issue and only appears once.

The second and third comments are the same GH comment on a PR.  Interestingly, when I deleted the comment in GH, only one of the Slack messages updated.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 4.38.127

I doubt this is a client issue, so OS/version shouldn't matter.

**Comment by jlord** [comment]
@gregsdennis are you still experiencing this? A recent update should have fixed this issue.

**Comment by gregsdennis** [comment]
No. I haven't seen it for a while. Thank you.

**Comment by jlord** [comment]
@gregsdennis woo 🎉 thanks! I'll close this then but feel free to re-open if you catch it reoccurring 🙏

**Comment by I4473** [comment]
من نمیدونم اینجا چه خبر است
