### ISSUE TITLE
Scheduled Reminders and Personal Notifications not being received on 7/26

### ISSUE THREAD

**Issue by setu4993** [integrations/slack#1927]
**Describe the bug**

I have scheduled reminders enabled for myself and my team, none of which are flowing through since ~midnight PT on 7/26. The last notification I received was at 00:01am PT.

Our entire organization is not receiving any GitHub notifications.

Test notifications from GitHub => Slack are not being received, either.

My configuration and observation:
1. Scheduled reminders at 9am and 2pm PT to my Slack user's GitHub: Did not receive it this morning at 9am or 2pm PT.
2. Notifications for PR review requests, PR reviews, comments, etc.: None received since 00:01am PT (email notifications show up fine).
3. Scheduled reminders for our GitHub team to a Slack channel: Did not receive them at 8am PT or 2pm PT.
4. ~GitHub org activity subscription to a Slack channel: Intermittent and incomplete notifications till 10am PT, but none received since 10:16am PT.~ These restarted after removing + adding the app back from the Slack workspace and then doing `/github subscribe org <...>`.

I've tried resetting the GitHub app connection (~3 hours ago) by removing the app and adding it back, but that hasn't changed anything.

**Expected behavior**

Notifications received on Slack.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A
 - Version Version 4.39.88 1f0158a82406616854e850bdc393b0d084483b22@1721937750 (App Store)

**Additional context**

- Also reported by another user here: https://github.com/orgs/community/discussions/133677
- Verified [Slack Status](https://slack-status.com/) and [GitHub Status](https://www.githubstatus.com/) and nothing webhook / app related reported on either.

**Comment by glasser** [comment]
Seeing this as well.

**Comment by artemlive** [comment]
The same thing for me.

**Comment by somersby10ml** [comment]
same

**Comment by sfreydin** [comment]
The same for us

**Comment by yedidyar-ni** [comment]
same

**Comment by artemlive** [comment]
It seems they got fixed. At least we started to get notifications.

**Comment by setu4993** [comment]
We started to get notifications ~3 hours ago, too, but they are incomplete. A bunch of repos / types of notifications still aren't coming through.

**Comment by setu4993** [comment]
Closing because everything appears to be normal now and the update from @geramirez in https://github.com/integrations/slack/issues/1928#issuecomment-2258561009.
