### ISSUE TITLE
Subscriptions to "pulls" feature not working

### ISSUE THREAD

**Issue by lamontadams** [integrations/slack#1960]
**Describe the bug**
I'm not receiving notifications of PRs in a repo subscribed via `/github subscribe owner/repo pulls`. `/github subscribe list features` confirms the repo is subscribed to the `pulls` feature. Subscriptions to pulls in the same repo worked correctly in a different slack account - we have migrated to a new account due to acquisition and no subscriptions work on new slack account.

Unsure if dupe of https://github.com/integrations/slack/issues/1833 or not, please advise if so and will close.

**To Reproduce**
1. In a slack channel with the github app installed: `/github subscribe owner/repo pulls`
2. Confirm subscription via `/github subscribe list features`
3. Got to owner/repo in github, create a PR
4. Note no notification appears in the subscribed slack channel.

**Expected behavior**
Notification appears in the subscribed slack channel when a PR is created.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Noted in Mac, Linux and IOS
 - Browser: NA (Desktop App)
 - Version: Slack 4.40.128

**Comment by angeliquejw** [comment]
Here to report the same issue. Our team originally subscribed to a repo in June and things worked as expected. On 9/23, we attempted to subscribe to a second repo's pull requests and have not seen anything from the repo, despite the fact that `/github subscribe list features` shows the second repo.

**Comment by mfitz** [comment]
We're experiencing the same problem, both for PRs and issues.

Nothing unusual happened when subscribing to the repo from the Slack channel, and `list features` also looks normal:

```
/github subscribe list features

<group>/<repo>
issues, pulls, commits:'main', releases, deployments, reviews, branches, comments
```

We see notifications when new branches and releases are created but not when PRs or issues are created

**Comment by holyspectral** [comment]
Same here.  I setup a new integration this afternoon and it doesn't work at all.  Hope this can be fixed soon.

**Comment by tigris** [comment]
`:+1:` here, i have a hacky solution for those impacted.

I setup `/github subscribe org/repo issues pulls` and it wasn't working. However, if I setup `/github subscribe org/repo` to get all the defaults, and then do `/github unsubscribe org/repo commits releases deployments` it works.

Doing `/github subscribe list features` shows no differences in the above two scenarios, but the latter works for us at the moment.

**Comment by nnamacha** [comment]
Experiencing the same issue

**Comment by lamontadams** [comment]
This seems to have suddenly started working again for us on Wednesday 10/9. I'll leave the ticket open but it looks like this may be resolved?

**Comment by mfitz** [comment]
Same here, this is now working again for us.

**Comment by lamontadams** [comment]
Closing since it seems to be fixed, although I will say it's disappointing to have a bug report not even acknowledged by any maintainers.
