### ISSUE TITLE
Disable Subscriptions when a channel is archived or deleted

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#197]
Currently seeing [this error](https://sentry.io/github-integrations/slack/issues/421500015/) in production:

```
Response not OK:  is_archived
```

That is because I set up a channel to test some subscriptions and then archived it before removing the subscriptions.

**Comment by bkeepers** [comment]
This should also handle deleted channels:

https://sentry.io/github-integrations/slack/issues/412683738/

**Comment by wilhelmklopp** [comment]
One slightly neater way to achieve this if it gets implemented: https://github.com/slackapi/node-slack-sdk/issues/472
