### ISSUE TITLE
Showing details of commits

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#231]
Via https://github.com/github-slack/private-beta/issues/4#issuecomment-357059984:

> I don't like how almost no information is shown for pushes. Expecting a bit more meat there (commit message at the very least.)

I agree that we could probably show some more detail on pushes to master, especially if we roll up push/merge events in #164

**Comment by trentpolack** [comment]
I'd really, really love (at least as an option) the ability to show commit messages for pushes; potentially with an option to limit the number of commit messages to show in a given push?

**Comment by bkeepers** [comment]
I agree this would be great. If you're interested in taking a crack at it, here's the code that formats the notification for pushes: https://github.com/integrations/slack/blob/master/lib/slack/renderer/push.js

I think it'd be great if it show'd the message for up to ~5ish commit messages, and then just a "and 8 more…" type of message with a link to view all commits.

**Comment by staticred** [comment]
➕ The commit messages are what make the notifications useful, in terms of notifications.

**Comment by csvance** [comment]
This particular integration feature was the original reason I adopted Slack. It is extremely valuable for smaller teams because people can just look at the Slack feed and get a context of where discussed things stand. Showing the last few commits with the "X more" message would be more than adequate.
