### ISSUE TITLE
Error when subscribing to private repo in Org 

### ISSUE THREAD

**Issue by osowskit** [integrations/slack#260]
I've verified I get notifications on a public repository on my user account `osowskit`.

I've installed the **Slack** GitHub App to `https://github.com/GH4B` and selected two private repositories.

<img width="581" alt="screen shot 2018-01-31 at 10 08 43 am" src="https://user-images.githubusercontent.com/768821/35640049-edfdd20e-0670-11e8-8f9f-5beb77986d02.png">

When running the command `/github subscribe GH4B/pivatetest` I get the following error:

```
Could not find resource: _GH4B/pivatetest_
```

I've tried the following:
* Removing all GitHub App **Slack** integrations and only installed it on the **GH4B** organization
* Revoking access to the slack app and doing OAuth dance again. (Slack correctly prompted me to do this)

**Comment by hairyhenderson** [comment]
@bkeepers I'm hitting this error too, with private repos on an org that has SAML turned on - all my tokens are SSO-enabled, so I'm not sure what's up with that...

Is this a bug with this integration or something on my side?

**Comment by bkeepers** [comment]
@hairyhenderson It looks like this is a bug with GitHub Apps. The team is working on it, but for now the integration won't work with any org that has SAML.

**Comment by hairyhenderson** [comment]
@bkeepers ok, thanks for the clarification! Will wait patiently, and continue to use the legacy GitHub app until it's fixed 🙂

**Comment by jpeterson** [comment]
Hey guys, my team is seeing something similar, hoping to find out if its a symptom of this same bug. We (read: I) just installed the new GitHub App in our workspace, and this error message is popping up anytime I attempt to (re)subscribe to a repo from a Slack channel:

![image](https://user-images.githubusercontent.com/3399064/36622787-b05fc408-18bc-11e8-9aef-4eb79394c1ef.png)

When I click the **Install GitHub App** button, I'm taken here: 
https://github.com/apps/slack/installations/new/permissions?target_id=849935

^ which just displays the generic GitHub 404 page.

Note that **our workspace does use SAML**.

Thoughts?

**Comment by bkeepers** [comment]
> Resource protected by organization SAML enforcement.

A fix for this was pushed out today (thanks @mtodd), so anyone who was having subscribing on organizations using SAML enforcement should be able to now. Let us know if you see any issues.

> ^ which just displays the generic GitHub 404 page.

@jpeterson I think you're actually running into #316.

**Comment by akwa-peter** [comment]
I hand the same issue but resolved it using "/github signin" to reconnect my GitHub account. Thanks to @wilhelmklopp

**Comment by leepatrick-goop** [comment]
I'm seeing this with my org that uses SAML I connect the app and do a /github signin but any time I try to subscribe I get this:
![image](https://user-images.githubusercontent.com/36421292/82696953-f0ba9b00-9c1c-11ea-87ee-f05ffb5a6524.png)
would be great if this worked!
