### ISSUE TITLE
Migration: error 500 and question

### ISSUE THREAD

**Issue by jchuerva** [integrations/slack#281]
### 1: "500_service_error"
- Install the new GitHub App
- configure the subscription `/git subscribe XXXX/XXXX` (and `/git sign in`)
- Open GitHub account settings and Uninstall the Slack App
- Install it again

**Issue:**
-  `/git subscribe XXXX/XXX` -> 500_service_error with XXXX/XXXX

- if `/git signin` -> Account *successfully* connected and then `/git subscribe XXXX/XXX` -> 500_service_error with XXXX/XXXX

----------
### 2:: Two GitHub Apps displayed in Slack after migration is done
> not sure if a bug or the expected behavior  

- After migration is completed
![migration complete](https://cl.ly/381H192r0a1c/Image%202018-02-14%20at%2011.25.47%20AM.png)
- There still two GitHub Apps in slack.** Need to remove the old one manually?** 
![slack apps](https://user-images.githubusercontent.com/5942864/36199533-1bf1dc6e-117a-11e8-8bbf-cc6823e36760.png)

**Comment by bkeepers** [comment]
I think this was fixed in #313. Let me know if you can still duplicate it.
