### ISSUE TITLE
404 when clicking link to install GitHub App

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#316]
If you try to subscribe to a repository that doesn't have the GitHub App installed, and you are not an owner of the organization, the "Install GitHub App" link gives you a 404 error.

Steps to reproduce:

1. Given `orgname` is an organization that you are a member of (not an owner), and it does not have the the GitHub App installed
1. type `/github subscribe orgname/repo` for a repository that you have access to
1. Click the "Install GitHub App" link
1. See GitHub 404 page

Current workaround: ask an organization owner to manually [install the GitHub App](https://github.com/apps/slack).

cc @jchuerva @osowskit

**Comment by a-tal** [comment]
+1

this bug breaks all functionality of this integration for us

**Comment by bkeepers** [comment]
@a-tal if you could get someone that is an admin on the organization to [install the app on the organization](http://github.com/apps/slack), then it should work.

**Comment by a-tal** [comment]
@bkeepers while that would work, the workflow there is a little less than ideal. The organization has hundreds of mostly private repos that I would like to hook some (60ish today) up with this integration. Compiling that list, getting someone else to go through the select-a-repo funtimes to find them all, and then maintaining updates to that subset doesn't sound nearly as nice as issuing a slash command in slack.

I don't quite get why org admin is needed if I have repo admin on all the repos I want to enable.

**Comment by bkeepers** [comment]
@a-tal I agree with you. This is feedback that the GitHub Apps team is aware of and is actively working to improve.

**Comment by chrismessina** [comment]
404 isn't the right error code for this kind of issue too. Would be at least helpful to provide the information cited here... i.e. "You don't have sufficient privileges to do that. Please contact your org owner to complete this task."

I was able to install Github on Slack — but apparently don't have the right permissions to get it to actually send data...! Pretty confusing!
