### ISSUE TITLE
Sign in flow doesn't redirect to Slack - deep linking

### ISSUE THREAD

**Issue by osowskit** [integrations/slack#325]
### Overview

Running `/github signin` will generate a `Connect to GitHub` button and, selecting this, will open a window to GitHub. Upon completing the OAuth flow, the page redirects to a page asking me to log into my Slack workspace.

Desired behavior is to redirect me to the Slack App workspace rather than a new Browser tab.

### Steps

1. Add Slack Application
1. Run `/github signin`
1. Complete OAuth flow
1. Redirected to browser rather than Slack App

### Misc

Mac 
Google Chrome Version 64.0.3282.167
Slack Beta 3.0.5 (Around The World)

<img width="843" alt="screen shot 2018-02-20 at 2 17 18 pm" src="https://user-images.githubusercontent.com/768821/36498960-bbfa9f00-16f4-11e8-86ee-4b3820e4e3a8.png">

**Comment by bkeepers** [comment]
This was fixed somewhere between #334, #332, and some fixes to production configuration that was causing cookies to disappear.
