### ISSUE TITLE
Error message selecting old `Connect GitHub account` link

### ISSUE THREAD

**Issue by osowskit** [integrations/slack#326]
### Overview

The integration adds a `Connect GitHub account` button when running `/github signin`. After a long period of time (over a day), pressing this button will generate an error.

Redirect URL : `https://slack-integration-prod.herokuapp.com/github/oauth/callback?browser_session_id=[SANITIZED]&code=[SANITIZED]&state=[SANITIZED]`

`An unexpected error occured: f8b28b9aa34a40d2b1edc3badc79ee99`

Expected behavior would be to allow user to sign in. ❤️

### Steps

1. Install GitHub App
1. Press a `Connect GitHub account` button that is at least 24 hours old
1. Error redirect

My hunch is that the code has long since expired. 

### Options
* Handle OAuth flow errors by starting over
* Modify the `Connect GitHub account` button to generate a new URL + code every time
* Remove old `Connect GitHub account` messages

**Comment by armchairdeity** [comment]
Still happening to us to this day... can't integrate Slack and GitHub.

**Comment by leandro-lucarella-frequenz** [comment]
Same here

**Comment by leandro-lucarella-frequenz** [comment]
sending a new `/github signin` was enough to get a new link though.

**Comment by ChrisKulesza** [comment]
> sending a new `/github signin` was enough to get a new link though.

That didn't work for me. As described in the documentation, the following input in the GitHub chat window is sufficient:

`signin`

Docu:
https://github.com/integrations/microsoft-teams#command-reference
