### ISSUE TITLE
Prompt to re-authenticate user if token was revoked

### ISSUE THREAD

**Issue by jchuerva** [integrations/slack#341]
**Scenario**
- Install GitHub App in slack and successfully configure it for a channel(s)
  - `/github signin` & `/github  subscribe owner/repo`
- On GitHub user Settings / Applications, **revoke** autorized GitHub App
- Perform `/github subscribe owner/repo`

**Issue**
- Could not find resource: `owner/repo`

**Expected**
- Connect GitHub account button?

As a work-around, you can `/github signin` again

**Comment by Daz762** [comment]
yeah i am having the same issue. since i removed my token from GitHub i now get "Could not find resource" when i try and to resubscribe. I would expect it to prompt for re-auth but it doesn't

any ideas?

**Comment by jchuerva** [comment]
as a work-around, you can `/github signin` again... I think that solves the issue in the meantime

**Comment by Daz762** [comment]
yep, i just discovered this and was on my way back to post this! 

Thanks for the reply

**Comment by casperdcl** [comment]
> you can `/github signin` again

Just noticed this is buried in the README under https://github.com/integrations/slack#subscribing-and-unsubscribing.

Really when typing `/github help`, this command should be listed too.
