### ISSUE TITLE
First commit on a new branch posts two messages

### ISSUE THREAD

**Issue by bradslavin** [integrations/slack#346]
After pushing a commit to a new branch, I got two messages posted in Slack as follows:

![image](https://user-images.githubusercontent.com/5849182/36574093-d7aa403e-17f8-11e8-8efe-ad6b6a72c47c.png)

The first message isn't very helpful, so maybe it's not needed?

**Comment by bkeepers** [comment]
I have not been able to duplicate this.

@bradslavin @tobiaslinberg are you seeing it consistently?

**Comment by bkeepers** [comment]
Zero commits issue fixed in #375. I haven't seen any other reports of this.
