### ISSUE TITLE
Possible to remove all notification types from a subscription

### ISSUE THREAD

**Issue by bradslavin** [integrations/slack#347]
If you repeatedly use the `/github unsubscribe` command to remove notification types, it's possible to remove all of them and end up with no notification types.

![image](https://user-images.githubusercontent.com/5849182/36574230-7c5928d4-17f9-11e8-813d-40f4ba0a8559.png)

Maybe either prevent that last one from being removed, or just remove the subscription entirely.

**Comment by kzap** [comment]
did not know you could subscribe/unsubcribe to certain notification types
