### ISSUE TITLE
Clarify what happens when you activate

### ISSUE THREAD

**Issue by rmccue** [integrations/slack#350]
One thing that's not entirely clear from the docs is what happens to the existing integrations when the new one is enabled. The home page notes "Installing the new app will allow you to migrate subscriptions from legacy versions." The readme notes:

> When you install the new GitHub integration for Slack in your Slack workspace, you'll be prompted to reconfigure your old settings - so getting set up again is easy. Once you subscribe with the new app, the legacy app will be disabled but the legacy notification configurations will be migrated automatically.

There's a few questions this leaves me with:
* It's not clear (to me at least) whether activating the new integration will deactivate all our existing integrations. i.e. is it a wholesale switch, or a piecemeal switch?
* If you activate it, can you undo that if that somehow breaks someone's workflow?
* Do you get a list of all the existing integrations that need migration?

Would be 🙌 to clarify these in the README.

**Comment by bkeepers** [comment]
Thanks for the feedback, @rmccue! We'll work on making that more clear.

I'll start by answering those questions here:

> It's not clear (to me at least) whether activating the new integration will deactivate all our existing integrations. i.e. is it a wholesale switch, or a piecemeal switch?

It's piecemeal. You'll reactivate one subscription at a time with the `/github subscribe username/reponame` command, and as they're activated, they will be disabled in the old integration. 

> If you activate it, can you undo that if that somehow breaks someone's workflow?

Yep! The configurations will still be available if you go into the settings for the old app.

> Do you get a list of all the existing integrations that need migration?

Yes! When you install the new app, you'll see a message similar to [this one from the README](https://github.com/integrations/slack#migrating-from-the-legacy-github-integration-for-slack):

![](https://user-images.githubusercontent.com/3877742/36557399-ff8663c6-17bc-11e8-8962-d92088cf98a9.png)

**Comment by rmccue** [comment]
Thanks for the heads up, all makes sense.

Also, thanks for your amazing work on both this and Probot; the latter of which has transformed our entire workflow. 💖
