### ISSUE TITLE
Intro message is sent again if you click "Add to Slack" again

### ISSUE THREAD

**Issue by rmccue** [integrations/slack#353]
As far as I can tell, clicking "Add to Slack" a second time doesn't actually create a new integration, but it *does* cause the "Good news: ..." message to be resent to every channel that needs migration.

(Also, I am an idiot and clicked the button twice.)

**Comment by wilhelmklopp** [comment]
thanks for bringing this up @rmccue ✨ 

What do you think would be the right behaviour? I think currently this is actually a feature, not a bug :tm: for the case in which the new GitHub integration gets installed on Slack, and is then forgotten about/not all subscriptions get re-activated. Then, this second message represents a follow up reminder to re-active old subscriptions.

**Comment by rmccue** [comment]
That’s a good point, but potentially varying the message could help. Alternatively, giving the user the choice with a message like “GitHub is already active on this workspace. Resend welcome message?” would be handy.

In my case, I clicked the button twice without about 10 mins of each other, so all that did was spam a bunch of rooms directly after each other. :)
