### ISSUE TITLE
Wrong user information associated with error in Sentry

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#357]
The exception below is coming from a GitHub webhook, which shouldn't have a Slack user associated with it, but it includes user info.

https://sentry.io/github-integrations/slack/issues/468663816/events/14624963615/

My best guess is that there's something wrong with our [Sentry setup](https://github.com/integrations/slack/blob/master/lib/slack/middleware/sentry-context.js) and the context is getting carried over from a previous request.

**Comment by andymckay** [comment]
Still appears to be the case.
