### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#358]
Something in the `/github subscribe` command is attempting to respond to the request twice.

https://sentry.io/github-integrations/slack/issues/469405384/

```
Error: Can't set headers after they are sent.
  File "/app/lib/slack/commands/subscribe.js", line 22, in respondWith
    res.json(message);
  File "/app/lib/slack/commands/subscribe.js", line 52, in module.exports
    return respondWith(new AlreadySubscribed(command.args[0]));
```

**Comment by wilhelmklopp** [comment]
We haven't seen this error in a while, so closing this out. This occurs when we try to send another express response after we've already sent one.
