### ISSUE TITLE
Is it possible to self host it?

### ISSUE THREAD

**Issue by matheuss** [integrations/slack#361]
[We](https://zeit.co) would love to self-host it 😌

**Comment by philschatz** [comment]
The `CONTRIBUTING.md` file contains instructions for starting it up; I have been able to use them to get it running on my machine for development.

**Comment by bkeepers** [comment]
Hey @matheuss. As @philschatz said, check out the [Getting Started](https://github.com/integrations/slack/blob/master/CONTRIBUTING.md#getting-started) section of the contributing docs for instructions on running the app, which you could use to deploy your own instance.

So it's possible, but it's definitely a process to get set up right now, and it's not something that we will be supporting in the near term. We won't be doing official releases or offering much guidance for upgrading as new features come out. This may change as we look at supporting GitHub Enterprise, but that will likely be a while.

**Comment by wilhelmklopp** [comment]
@matheuss I'd love to also learn more about your use case. What do you want to do with the self hosted app that you can't currently do with the hosted version? Thanks 😃

**Comment by LukeSoldier** [comment]
Some people probably never heard about corporate espionage. No i do not suspect slack itself to do that, but if there is a trough, the swines are not far away.

**Comment by Isabaellchen** [comment]
Some people probably never heard about corporate espionage. Not saying slack itself is doing that, but if there is a trough, the swines are not far away.
