### ISSUE TITLE
Missing Commit ref, commit Message from posted Message

### ISSUE THREAD

**Issue by splinterific** [integrations/slack#363]
With the old Integration, the message contained the commit reference and also the commit message. This isn't currently displayed in the new app and you need to follow the hyperlink to get this information.

**Comment by csvance** [comment]
I have the same problem as well:
![screen shot 2018-02-24 at 8 29 12 am](https://user-images.githubusercontent.com/6805096/36631399-d13f127a-193c-11e8-997d-829b77bd7aa7.png)

**Comment by bkeepers** [comment]
Thanks for the feedback. This is being tracked in #231
