### ISSUE TITLE
Debounce rollups by event

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#372]
For repositories that have a _lot_ of status checks (*cough* github/github *cough*), opening a new Pull Request results in a lot of status events arriving at roughly the same time, which in turn triggers a lot of requests to GitHub to roll up the message.

I'm pretty sure that is the cause of [this error](https://sentry.io/github-integrations/slack/issues/473125081/):

```
HttpError: {
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
}
```

We should consider debouncing events that arrive in herds like this, at least for the status event.

**Comment by wilhelmklopp** [comment]
Also seeing status responses show up as a Server Error in Sentry: https://sentry.io/github-integrations/slack/issues/473125081/
