### ISSUE TITLE
"0 new commits pushed to $branch"

### ISSUE THREAD

**Issue by matheuss** [integrations/slack#375]
<img width="75%" src="https://user-images.githubusercontent.com/4721750/36673827-debfdb8a-1ae2-11e8-8249-b6dff6fe24d2.png">

It happened when I merged a PR and deleted its branch (all via the PR page).

**Comment by matheuss** [comment]
Hmm it's also happening when a tag is pushed 
<img width="50%" src="https://user-images.githubusercontent.com/4721750/36674100-d991c9d8-1ae3-11e8-921f-5479ddab6670.png">

**Comment by bkeepers** [comment]
Thanks for the report. Fix in #376.
