### ISSUE TITLE
Public code snippet and pull request URL unfurling issues

### ISSUE THREAD

**Issue by olivierlacan** [integrations/slack#381]
I used the code snippet demonstrated on https://slack.github.com in a channel that had been enabled with the GitHub Slack integration and after several minutes it seems like the unfurling isn't working. 

![image](https://user-images.githubusercontent.com/65950/36686886-2a25be9c-1b28-11e8-9323-be5656a06e32.png)

This didn't work with Pull Request URLs either so there might be a general unfurling issue.

Is there any way to debug this or provide some useful data to help debug it?

**Comment by bkeepers** [comment]
Hey @olivierlacan. I'm not able to duplicate this, are you? Unfurls should definitely be working for public activity, so if it's not, then it's a bug.

**Comment by olivierlacan** [comment]
@bkeepers It's definitely not working in any of the Slack channels I've added the GitHub integration to yesterday.

**Comment by olivierlacan** [comment]
@bkeepers It's important to note that I didn't allow the GitHub integration to see and access all channels, just two specific ones. You may be testing with a global integration.

**Comment by sjackman** [comment]
Code unfurling is not working for me either. I did enable all repos and channels.
https://linuxbrew.slack.com/ and https://github.com/linuxbrew and https://github.com/brewsci
