### ISSUE TITLE
Comment display regressed compared with legacy integration

### ISSUE THREAD

**Issue by brasic** [integrations/slack#383]
We tried switching to the new slack integration for our private repo but noticed that PR comments are not displayed.  Instead the entire content of the notification is "[USER] commented on pull request" with a link to the comment.  Any reason the comment body itself isn't present in the notification like it was in the previous integration?

**Comment by bkeepers** [comment]
Hi @brasic, full comments should be working. For example, here is the notification we got when [this comment](https://github.com/integrations/slack/pull/364#issuecomment-368580729) was posted:

<img width="453" alt="slack_-_github___slack" src="https://user-images.githubusercontent.com/173/36699731-351f2e60-1b13-11e8-99b9-3ccff5d762e9.png">

Check out the [docs on configuration](https://github.com/integrations/slack#configuration), and if you continue having issues, feel free to [get in touch](https://github.com/contact?form%5Bsubject%5D=Re:+GitHub%2BSlack+Integration) with details on which repo/account you're having issues with.

**Comment by bary822** [comment]
Comments on PR itself are cast to Slack perfectly though, those on discussion are not.
Any tips to turn it on? @bkeepers

**Comment by brasic** [comment]
@bkeepers Thanks for the confirmation that this is supposed to work, but this isn't a configuration issue, I'm confident that it's a bug in the integration.  Upwards of 90% of our comments work as expected but some do not, and there doesn't seem to be an obvious pattern.  Here's an example image  I just pulled from slack of two comments in a single discussion that didn't get any text:

<img width="715" alt="screen shot 2018-02-28 at 3 10 46 pm" src="https://user-images.githubusercontent.com/677224/36813302-bf6c1f88-1c99-11e8-84e6-360e68987b8b.png">

here are the comments in github that triggered those two notifications:

<img width="895" alt="screen shot 2018-02-28 at 3 04 53 pm" src="https://user-images.githubusercontent.com/677224/36813077-e9f04e74-1c98-11e8-8c34-382771841aae.png">

One interesting thing about the difference between notifications that include the comment body and those that do not is that the "working" notifications' primary link includes the `#issuecomment-1234567` anchor in the link, whereas the ones that include no content are a bare link to the PR with no anchor.

If I had to guess, this looks related to some asynchronicity on your side.  Perhaps the integration is reading from a lagging database slave before the data it needs is present?

**Comment by bary822** [comment]
Seems like this has been resolved by [a PR recently merged](https://github.com/integrations/slack/pull/409).

**Comment by bkeepers** [comment]
@brasic thanks for the report. AS @bary822 pointed out, everything should be all fixed up with review comments in #409.

**Comment by brasic** [comment]
@bkeepers I'm not sure if #409 changed this but we are no longer receiving comments not associated with a review, despite being subscribed to `comments`:
<img width="644" alt="screen shot 2018-03-02 at 1 02 06 pm" src="https://user-images.githubusercontent.com/677224/36916691-4ed316aa-1e1a-11e8-871a-1d716dfab680.png">

To reproduce this:

 - pick a random commit and open it via the `repo/commits/SHA` endpoint (as opposed to `repo/pulls/NUM/commits/SHA`
 - make an inline comment
 - email notifications go out, nothing shows up in slack.

This definitely works in the old webhook-based slack integration.

**Comment by bkeepers** [comment]
@brasic Commit comments aren't currently supported. I opened #432 to track it.

**Comment by brasic** [comment]
Thanks!
