### ISSUE TITLE
Subscribe to certain labels only

### ISSUE THREAD

**Issue by Viper007Bond** [integrations/slack#384]
I'm a member of a Slack channel dedicated to a specific feature of a repo that covers a wide variety of features. Right now we have an internal Hubot to filter down to a specific label and then post messages to the channel.

It'd be cool if this official integration could replace our internal by allow subscribing to only issues/PRs that have a specific label instead of the entire repo.

**Comment by pimearht220256** [comment]
บล็อก

**Comment by serhalp** [comment]
We would love this to be able to filter out Greenkeeper PRs from polluting our Slack channels.

A cursory glance at the code makes it seem like this would be fairly straightforward to implement. If I worked on a PR, would this feature be accepted? What would the preferred command syntax be? `/github unsubscribe owner/repo label:[label]`? Thanks.

**Comment by serhalp** [comment]
I have not started on this. But from glancing at the code, it seems that it already fetches the labels for PRs/issues [here](https://github.com/integrations/slack/blob/98ca6e08114c76329da7b603e141acbc86c94d17/lib/activity/pull-requests.js#L10-L19) and [here](https://github.com/integrations/slack/blob/5dc2d0ab70db5a6b5cd4250496afe4003ed49587/lib/unfurls/pull.js#L12) and includes them on the objects passed around. (I think this is just so they can be [included in Slack messages](https://github.com/integrations/slack/blob/5dc2d0ab70db5a6b5cd4250496afe4003ed49587/lib/messages/pull-request.js#L38-L41)).

So, roughly, I was imaging you'd pass in optional label filters to subscribe/unsubscribe [here](https://github.com/integrations/slack/blob/97ca3b528bd2b52e90de84614fbe603a7c44dfac/lib/commands/subscribe.js#L46-L53) and right around... [here](https://github.com/integrations/slack/blob/97ca3b528bd2b52e90de84614fbe603a7c44dfac/lib/activity/pull-requests.js#L88) (and in the analogous spot for issues) you'd exit early (not send a message) if the PR matches blacklisted labels?

People may want both the ability to whitelist labels and to blacklist labels... Hrm.

**Comment by RealAndyLawton** [comment]
^ Bump this.  When working on a monorepo type project it's useful for feature teams/pods to only subscribe to their specific labels.

**Comment by zetbrush** [comment]
@serhalp any news on this? how to subscribe to PRs with Specified Label only?

**Comment by steipete** [comment]
Monorepo here as well. This currently makes GH Slack Notifications unusable because of the traffic. 

Even for our other repos, a more fine-grained selection of notifications would me this immensely useful, for example only post if a certain tag is set (e.g READY FOR REVIEW) We currently deploy our own bot to work around this limitation: https://pspdfkit.com/blog/2018/reviewbot/

(We cant run our own bot for filtering - that’s too complex)

**Comment by DeMarko** [comment]
I've got a similar issue, we have a monorepo for our API/web but we label PRs for our the API that concern our internal tools, it'd be great to have them emit into a specific channel

**Comment by shaunkawano** [comment]
Same here, we have monorepo as well.

It would be cool to be able to setup something like this on Slack:
`/github unsubscribe owner/repo label:[label]`

**Comment by ffMathy** [comment]
We really need this too.

**Comment by johanatan** [comment]
Also need.

**Comment by allendewilzin** [comment]
This will be cool

**Comment by hatched-anthony** [comment]
Also need.

**Comment by zubhav** [comment]
Would be very helpful for a monolithic codebase where you want to filter front-end/back-end PRs seperately

**Comment by repi** [comment]
Would love this, both for monorepo use cases but also to filter out automatic/bot PRs that become too noisy in some projects (and that all have a specific label)

**Comment by mistercrunch** [comment]
Our use case is for our designers to be informed on their slack channels when we label an issue with `needs:design-review`

**Comment by murphymi** [comment]
+1 we also need this....any update as to whether this will be provided?

**Comment by ewdave** [comment]
+1 for this feature.

**Comment by joegesualdo** [comment]
+1 This would be extremely helpful and make this integration work better with our teams' workflow.

**Comment by alex-polunochev** [comment]
This is a great idea and my team will definitely benefit from having this option! Bump ^

**Comment by justportillo** [comment]
+1!

**Comment by envato-daniellucas** [comment]
➕ 1️⃣

**Comment by DjCedrics** [comment]
This would be great to have. +1

**Comment by bb220** [comment]
Looks like @cou29 has an open pr for this https://github.com/integrations/slack/pull/797

**Comment by cou929** [comment]
Yes, I'm also one who strongly wants this function. So a month ago I created a pr #797 .
I would be glad if yougive any feedback.

**Comment by scepticulous** [comment]
Hey everybody 👋,
thanks for all your input. That is super valuable to help us see the existing demand and to make a good decision about how to implement this feature

First off: It would be great if everybody would upvote the OP instead of adding new comments. When prioritizing potential features, we only take the reaction count of the OP into consideration.

I took a look at @cou929 's PR and the comments above and here are my thoughts:

## Whitelist

I think the most requested feature here is about only receiving updates for certain labels only. So it fits nicely into the realm of `subscribe`. I already mentioned it to @cou929 in the PR, but we hesitate using a JSON-like array syntax and to treat this as JSON, which opens the security risk around `deserializing untrusted input`. 
The PR was already updated and either adding multiple `label:xxx label:yyy` entries or something similar to that looks like a good approach to me.
I will take a look at the PR soon and then decide what the best path forward is so that we can ship the first iteration of this feature as soon as possible.

## Blacklist

There is also a theme around blacklisting like 'everything except X'. (E.g. https://github.com/integrations/slack/issues/384#issuecomment-376593013)
I would like to move that conversation into a dedicated issue so that we focus this issue on what the OP was asking for. If the demand for blacklisting (Use cases like ignoring dependabot/greenkeeper, etc) we can take a look into it too. 

Generally, the use case makes a lot of sense to me, but we have to prioritize the requested features.

**Comment by scepticulous** [comment]
Hi everybody.
I picked up the work that @cou929 started in #797 and I will push my changes to the existing PR very soon. It should not take much longer to ship the first version of this label feature.

Here is a quick checklist for myself to make sure we covered everything.

* [x] Subscribe works
  * [x] `/github subscribe label:foo` command is accepted accepted
  * [x] `/github subscribe label:foo` settings are stored correctly
  * [x] `/github subscribe label:foo` settings are viewable
* [x] invalid labels have test coverage
* [ ] invalid labels cause a proper error message
* [ ] handle mixture of valid and invalid labels?
* [ ] label presentation is pretty
* [ ] Label filters work for incoming issues
* [ ] Label filters work for incoming PRs
* [ ] Filtered content is logged
* [x] Unsubscribe works
  * [x] `/github unsubscribe label:foo` command accepted
  * [x] `/github unsubscribe label:foo` command persisted
  * [x] `/github unsubscribe label:foo` command idempotent
* [ ] Issues are accepted after removing filter
* [ ] PRs are delivered after removing matching filter
* [ ] Issues that do not match existing filters are delivered
* [ ] PRs that do not match existing filters are delivered
* [ ] Easy way to flush all filters. `/github unsubscibe org/repo label` without args?

**Comment by cou929** [comment]
Thank you for your work.

I agreed with @scepticulous ‘s comments. (https://github.com/integrations/slack/pull/797#pullrequestreview-270838189 and https://github.com/integrations/slack/issues/384#issuecomment-520708832 )
I am looking forward to the first version of label feature 😄

**Comment by scepticulous** [comment]
Everybody who is interested in sharing their thoughts about a future filter syntax that allows AND/OR combinations, feel free to add your two cents in #913

**Comment by scepticulous** [comment]
Filtering by a "required-label" is now possible 🎉 .
I removed the support for AND/OR combinations and multiple labels for now.
As documented in PR #911, the new syntax for adding a required label is:
```
# Notify events which have `todo` label
/github subscribe owner/repo +label:todo

# You can specify labels which have spaces when enclosed in quotes
/github subscribe owner/repo +label:"help wanted"

# Unsubscribe
/github unsubscribe owner/repo +label:"help wanted"
```

**Comment by scepticulous** [comment]
> I'm currently running into issues subscribing to labels with whitespace. I'm getting this error
> `+label:"help is not a valid argument.`

I assume there is a problem with the quotes or the whitespace. Can you try typing the double quotes `"` or a single quotes `'` manually?
I am planning to add support of all well-known and typical unicode-quotes very soon, but for now we use standard ascii quotes.

Here is my example:

Command
`/github subscribe integrations/test +label:"help wanted"`

Visual
<img width="823" alt="labels-with-quotes" src="https://user-images.githubusercontent.com/3408791/63865884-9ef92300-c9b2-11e9-9d9e-338fae93ab26.png">

**Comment by scepticulous** [comment]
@DeMarko Thanks for sharing your exact command. Your example is actually not using the standard double-quotes (ASCII 34) I was referring to. 

Here is the difference:
`/github subscribe owner/repo +label:“System Integrity”`
`/github subscribe owner/repo +label:"System Integrity"`

However, that is hard to spot, confusing and annoying.
So I 🚢 a change that adds supports for the quotes that you are using (and others). PR: #927

In addition to `'` and `"` we now support:
```
✓ supports '«'
✓ supports '»'
✓ supports '“'
✓ supports '”'
✓ supports '„'
✓ supports '‟'
```

**Comment by DeMarko** [comment]
oh woah! Thanks for spotting that, I had no idea Slack (or maybe my OS?) was doing "smart" Unicode quotes

**Comment by omarreiss** [comment]
Hey there, thanks for this awesome feature. Just wondering. Is it entirely impossible to subscribe to multiple labels?

When I run 
`/github subscribe owner/repo +label:"label a"`
`/github subscribe owner/repo +label:"label b"`
I expected to see both labels added to my subscription. But that didn't work.

Then I tried
`/github subscribe owner/repo +label:"label a" +label:"label b"`
But that didn't work either. Am I doing something wrong? Is this still on your list?

I would very much like to filter issues on multiple labels. Should I open a new issue to propose this and describe my usecase?

**Comment by efung** [comment]
I would expect to get a notification if the required label I'm filtering on, was **added** after the issue was initially created, e.g.:

- Configuring a filter for a required label, say, `Foo`
- Creating a new issue with no labels set. I don't expect to get a notification (and I don't).
- Updating the issue by adding the label `Foo`. I expect to get a notification, **but I don't**

I am only subscribed to the `issues` event. But I don't see any other events that would represent the issue metadata getting updated, or a label changed event.

**Comment by pwxn** [comment]
@efung Did you ever find a workaround for this? I am finding the same issue with our workflow. 

We're using a github action to set the labels automatically, so they aren't set until after PR creation.

**Comment by efung** [comment]
> Did you ever find a workaround for this?
No, I haven't.

**Comment by Tankard** [comment]
> I would expect to get a notification if the required label I'm filtering on, was **added** after the issue was initially created, e.g.:
> 
> * Configuring a filter for a required label, say, `Foo`
> * Creating a new issue with no labels set. I don't expect to get a notification (and I don't).
> * Updating the issue by adding the label `Foo`. I expect to get a notification, **but I don't**
> 
> I am only subscribed to the `issues` event. But I don't see any other events that would represent the issue metadata getting updated, or a label changed event.

It seems that `labeled/unlabeled` events are not triggered at all. For issues and for PRs as well.

**Comment by seanmunson** [comment]
> Filtering by a "required-label" is now possible 🎉 .
> I removed the support for AND/OR combinations and multiple labels for now.
> As documented in PR #911, the new syntax for adding a required label is:
> 
> ```
> # Notify events which have `todo` label
> /github subscribe owner/repo +label:todo
> 
> # You can specify labels which have spaces when enclosed in quotes
> /github subscribe owner/repo +label:"help wanted"
> 
> # Unsubscribe
> /github unsubscribe owner/repo +label:"help wanted"
> ```

Does this support multiple labels, or just one?

**Comment by taw123** [comment]
Any progress here? I hate adding a"me too" tag here but...

I'm trying to track new issue related to a Repo I DON'T own so I can't add the GitHub Action I found elsewhere that runs at label creation and allows for notice on label if added to the repo [issue-label-notifier)](https://github.com/marketplace/actions/issue-label-notifier). This was actually found in a similar request for label subscription in GitHub, that is still open tracing back to 2016... [Automatically subscribe to an issue by label or a set of labels](https://github.com/isaacs/github/issues/581)

Using the command described HERE I would like to follow ONLY specific label(s) in the Home Automation repo that are associated with the integrations I use....  

Sounds simple enough... but to date after searching and reading this thread, I don't see a way to subscribe/follow say home-assistant/core +label:"integration: shelly" +label:"integration: apple_tv"  The following command would seem like it SHOULD work IF the command would actually provided notification of ALL NEW AND MODIFIED issues with label(s) found in list...
`/github subscribe home-assistant/core +label:"integration: shelly" +label:"integration: apple_tv"  `

Additional, WHEN this DOES (hopefully) work, can one make changes in the future by simply adding/removing labels from a potential CURRENT/pre-existing subscription list? (i.e. will the following result in 1 or 3 subscribed labels?)
 `/github subscribe home-assistant/core +label:"integration: shelly" +label:"integration: apple_tv" `
 `/github subscribe home-assistant/core +label:"integration: additional_new_label"  `

IDEALLY the result of the 2 separate commands above would be a subscription to the repo home-assistant/core for the 3 labels: integration: shelly, apple_tv, additional_new_label

Correspondingly then, one would hope that the 2 commands: 
 `/github subscribe home-assistant/core +label:"integration: shelly" +label:"integration: apple_tv" +label:"integration: additional_new_label" `


`/github unsubscribe home-assistant/core  +label:"integration: additional_new_label" `

SHOULD produce a subscription list for home-assistant/core to just 2 labels  labels: integration: shelly and integration: apple_tv. Correct?

Thanks for any help here.
--Tom

**Comment by thetaiter** [comment]
I'd also like to know if multiple labels are supported. This is a quite simple and extremely useful feature.

**Comment by patrickracicot** [comment]
Any news on the multi-label ?

**Comment by namolnad** [comment]
Plus one on the multi label question -- this and or a custom query would be a huge help for me

**Comment by dk03** [comment]
At my day job we use a **mono-repo** structure too and getting bombarded with notifications for all pulls has stopped us being able to use this plugin too. 

I decided to fix the problem myself and created [https://www.pullmate.io/](https://www.pullmate.io/) 🎉  which lets you subscribe to notifications for pulls only from specified sub-directories:

e.g. running `/sub-path repo/sub/directory/repo-1` will only get notifications for pulls opened in the **repo-1** path

I was wondering if this helps mitigate the need to filter by label? or is that still required?

**Comment by ytvnr** [comment]
On my side, I am not allowed to filter on label with an `_` in it :(

**Comment by mrmanc** [comment]
This feature seems really really useful. Is there any plan to make this available for GitHub Enterprise Server users?

**Comment by aequasi** [comment]
> At my day job we use a **mono-repo** structure too and getting bombarded with notifications for all pulls has stopped us being able to use this plugin too.
> 
> I decided to fix the problem myself and created [pullmate.io](https://www.pullmate.io/) 🎉 which lets you subscribe to notifications for pulls only from specified sub-directories:
> 
> e.g. running `/sub-path repo/sub/directory/repo-1` will only get notifications for pulls opened in the **repo-1** path
> 
> I was wondering if this helps mitigate the need to filter by label? or is that still required?

What happened to pullmate?

**Comment by codingtony-candid** [comment]
Is it possible to filter out when a label is present?
I.e subscribe to all pulls **except** the ones that contain a specific label.

**Comment by devinschumacher** [comment]
when i run it it just subscribes me to... everything. as always

<img width="743" alt="Screenshot 2023-11-19 at 22 01 54" src="https://github.com/integrations/slack/assets/45643901/90cec28c-f170-46c1-a139-e4402b6fbeec">
