### ISSUE TITLE
List enabled features on subscribed repositories

### ISSUE THREAD

**Issue by daneah** [integrations/slack#386]
It is interesting to know not only which repositories a channel is subscribed to, but also which features of each of those repositories are enabled for notifications. This minimizes people running redundant commands "just to make sure" a feature is enabled.

`/github subscribe list` could potentially do this by default, or `/github subscribe list features` or similar could be added.

**Comment by cainlevy** [comment]
We initially disabled the new GH bot due to a lack of insight into its features. This would help considerably.

**Comment by Relequestual** [comment]
Does the colsure of the associated milestone mean this is no longer priorities work?

**Comment by kaanchan** [comment]
This feature is working :)

**Comment by megagreg72** [comment]
`/github subscribe list features` now exists and works as expected 👍
