### ISSUE TITLE
Subscribing randomly fails with "Could not find resource"

### ISSUE THREAD

**Issue by wilhelmklopp** [integrations/slack#387]
Experienced this morning:
![image](https://user-images.githubusercontent.com/7718702/36722232-e4bbfc90-1ba4-11e8-9fdd-5bee3e8beec3.png)

Didn't change anything about the state of the installation of `integrations/test`, so this seems kinda weird.

**Comment by opus131** [comment]
Probably related: I see messages being missed randomly as well. I created several test issues and commits, saw only some of them in the subscribed channel while others were not shown.

**Comment by wilhelmklopp** [comment]
@opus131 thanks for confirming.
This seems to be an issue with the GitHub API timing out for a certain input. We're investigating

**Comment by wilhelmklopp** [comment]
Hey folks! I've deployed a change that should stop message deliveries being missed. 

The app will continue to be a little slow until the fix in the GitHub API goes out.

**Comment by devprodoctor** [comment]
We started using Slack yesterday (2018-02-26) and this was already happening. After many many tries, we get a repo to subscribe. All of our repos are private.

**Comment by wilhelmklopp** [comment]
@devprodoctor thanks, that's very useful info! Are you still seeing this problem now?

**Comment by devprodoctor** [comment]
yes

**Comment by wilhelmklopp** [comment]
A fix has gone out for the GitHub API, and we haven't seen this error for the past 15min.

@devprodoctor if you're still having problems, could you open another issue on this repo? 🙇

**Comment by gorlak** [comment]
I've been seeing this again today, with my public repos

**Comment by gorlak** [comment]
Thanks for the quick reply, signin fixed it!! Thanks!

**Comment by tomgarciap** [comment]
> @gorlak would you mind opening a separate issue for this, and if possible add some steps to reproduce it? You could also try doing `/github signin` to see if that fixes it.

Saved my day
