### ISSUE TITLE
Allow subscribing to an entire organization's collection of repos?

### ISSUE THREAD

**Issue by rbonestell** [integrations/slack#391]
I have recently upgraded from the old GitHub slack plugin to the new one, and my organization has almost 80 repositories. I don't want to have to copy/paste the link and subscription type for each of my repositories into each channel I want the bot in. Additionally, consider auto-subscribing to new repos in an organization given a specific configuration?

**Comment by erydo** [comment]
@bkeepers — As an additional data point, our org also has >80 repositories. We previously had a single Slack/GitHub webhook set up at the org level. It was very easy.

Since the new plugin doesn't even let you subscribe to multiple repositories in the same message, e.g.:
```
/github subscribe foo/bar
/github subscribe foo/baz
```

The message for each of those had sent individually. (First, I had to figure out how to list all our repositories…). It was an extremely annoying migration, and now I'm not confident we'll see messages on newly created repositories.

**Comment by DuBistKomisch** [comment]
This is desperately needed. Just migrated almost 30 repos with copy pasta and then found out I have to go back through and enable all the PR notifications for each one!

**Comment by vbezruchkin** [comment]
Hey guys,

Thanks for the integration.

Also 80+ public repositories for our organization.. And it's not easy to subscribe to each one separately. 
We would like to use this app instead of hook for an organization.
Any ETA?

Thanks

**Comment by danrademacher** [comment]
A halfway point that would help would be to allow an array of repos to be submitted with one command. At least then one could construct a single command to batch subscribe to repos.

**Comment by bkeepers** [comment]
> Any ETA?

Sorry, not yet. I know the pain because I have a couple organizations that have tons of repos. We'll be switching into new feature mode soon and will take this into consideration when planning.

**Comment by chriszs** [comment]
To do this with the old integration, I set a webhook for my organization under organization Settings -> Webhooks. This still works for now, but I don't see any benefits of the new integration, so I assume I'm still on the old one.

**Comment by weisjohn** [comment]
Is there a way to migrate from the new integration to the old?

**Comment by esaruoho** [comment]
+1 for proper migration from old-legacy-github to nu-github without losing comments/pullrequestreviews etc.

**Comment by chriszs** [comment]
(My ideal is that you'd be able to do /github subscribe <organization> and then get a similar functionality to the old integration, e.g. every notification from the organization gets sent. If you wanted to pick and choose, you'd subscribe to repos singly. I suspect given the pre-existing webhook functionality this could be way easier than trying to subscribe to a user to every repo in an organization, or creating rules for which ones auto-subscribe in the future.)

**Comment by farski** [comment]
I'd recommend that the README and docs get updated, at least, until this happens. There are a [number](https://github.com/integrations/slack/blame/master/README.md#L42) [of](https://github.com/integrations/slack/blob/master/lib/commands/subscribe.js#L6) [places](https://github.com/integrations/slack/blame/master/README.md#L72) where it makes it seem like this is already something you can do.

**Comment by tgmcguire** [comment]
Agreed, @farski – I spent a while trying to figure this one out, thinking it was possible.

**Comment by laceysanderson** [comment]
Just want to add my voice to the others. I need this feature desperately and will not be using the GitHub-Slack integration at all until it is available. It's just not worth my time to add each one individually and try to remember to do so each time we create a new module.

Also adding a specific +1 to @chriszs suggestion of

> you'd be able to do `/github subscribe organization` and then get a similar functionality to the old integration, e.g. every notification from the organization gets sent. 

This would also be my ideal :-)

**Comment by bmcclure** [comment]
We have a constantly-growing list of repositories in our organization, up to a couple hundred now and not slowing down anytime soon. It's _such_ a hassle having to manually subscribe each repository, and even worse, it's incredibly easy to forget one (since a bunch of different people are creating the repositories) and not realize that it isn't being tracked in Slack.

**Comment by ronert** [comment]
We really need this as well

**Comment by hugovk** [comment]
(See https://github.com/integrations/slack/issues/557 for a feature request to allow subscribing to multiple repos.)

**Comment by n1ywb** [comment]
I found a practical workaround. This script (https://github.com/dazlious/slack-cmd-trigger) uses an undocumented slack API to execute slash commands from a shell. You can combine it with a BASH one-liner or xargs or something to loop over and subscribe to all your repos programatically. Note you need to regisiter yourself as a Slack app and request a LEGACY Slack API key, which they are thankfully still handing out if you look hard enough for it.

**Comment by taiidani** [comment]
I would love this as well. My organization has 201 repositories, and we maintain `#development` (for all commits/PRs) and `#deployment` (for all releases) channels to track the activity of the org. Doing this manually is an unpleasant thought.

**Comment by freemarmoset** [comment]
I would love this as well.  There really needs to be a way to easily manage subscriptions.  slash commands only is a very unpleasant and tedious way to manage settings for this integration.

**Comment by manossaratsis** [comment]
+1

**Comment by hugovk** [comment]
There's no need to comment "+1", it just spams everyone else. Just add a thumbs IP on the first comment, and/or subscribe to the issue. 

Thanks!

**Comment by philiparthurmoore** [comment]
I'm not familiar with this repository's labels. Does `feature:activity` mean that it's actively being worked on or something else? While I agree that simply adding +1 to the conversation isn't great for the noise to signal ratio, I would like to be able to follow this closely, as we spin up repos nonstop and subscribing to each one manually just isn't practical. Thanks.

**Comment by philiparthurmoore** [comment]
Thank you @farski. I'm a bit baffled why the legacy version of the app is only available to Enterprise versions of Slack, given how lacking this new version is. Guess we'll have to start manually adding/removing repos in the meantime. Thank you again.

**Comment by bendpx** [comment]
+1. 300+ repositories on our organization 😞

**Comment by bkeepers** [comment]
> …but the fact that GitHub more-or-less abandoned the project so quickly makes me very hesitant to invest too much time, in case they just shut the whole thing off some day relatively soon.

Just to clarify, this project is still being maintained by our team at GitHub and we currently plan to support it as long as GitHub and Slack are vital tools for developers (or until the heat death of the universe, which some days honestly seems like a more likely scenario). We're not actively prioritizing new features this quarter while we we work on another integration and a few foundational features for GitHub Apps that we wished existed while we were developing this Slack integration.

Thanks for continuing to voice your support for this feature. If someone wanted to take a crack at implementing it, we'd be happy to talk through ideas for implementing it and review a pull request.

**Comment by kingdango** [comment]
It concerns me the time scale you're using here includes "the heat death of
the universe".  😂   Entropy is real man...

**Comment by walkafwalka** [comment]
I was to impatient and created a script.
1. Create a legacy token. See https://api.slack.com/custom-integrations/legacy-tokens.
2. Install slack pip package. `pip install --user slacker`
3. Run the following:
```
#!/usr/bin/env python
repos = [
    "User/Repo1"
    "User/Repo2"
]
from slacker import Slacker
import time
slack = Slacker("YOUR_SLACK_TOKEN")
channel_id = slack.channels.get_channel_id('YOUR_SLACK_CHANNEL_NO_HASHTAG')
for repo in repos:
        call = slack.chat.command(
                channel=channel_id,
                command='/github',
                text='subscribe ' + repo
        )
        print call
        time.sleep(1)
```
I highly suggest not removing the sleep unless you want to get your account throttled or potentially banned.

**Comment by Daemoen** [comment]
I know it's a silly/tiny oversight, but don't forget the ',' after each repository in the list in the script above.

**Comment by gimenete** [comment]
I'm happy to announce that we have just deployed this feature through https://github.com/integrations/slack/pull/709

Use:

> /github subscribe Org-name

Be aware that if you are already subscribed to repositories in that org you will get duplicated notifications depending on what you are subscribed to in those repositories and the organization. Remember that you can subscribe just to certain things (pulls, commits, issues, etc). Example:

Subscribe to everything
> /github subscribe owner/repo

Then unsubscribe for everything except for issues
> /github unsubscribe owner/repo commits,pulls,deployments,statuses,public,releases

You can list your current subscriptions with

> /github subscribe list

Enjoy it! 🎉

**Comment by DuBistKomisch** [comment]
now we need a way to bulk unsubscribe from all of the old individual subscriptions! :man_facepalming:

**Comment by kzidane** [comment]
@DuBistKomisch try that https://gist.github.com/kzidane/60f02ac348a74a2a661e38b68f551409

```
$ pip install slacker
$ path/to/unsubscribe -t SLACK_TOKEN -c SLACK_CHANNEL -o GITHUB_ORG -r REPO ...
```

You could do the following to unsubscribe all repos in a GitHub org:

```
$ pip install PyGitHub
$ path/to/unsubscribe -t SLACK_TOKEN -c SLACK_CHANNEL -o GITHUB_ORG -r `python -c 'from github import Github; print(*[repo.name in Github("<ACCESS TOKEN>").get_organiztion("<ORG>").get_repos()], sep=" ")`
```

**Comment by philiparthurmoore** [comment]
@DuBistKomisch I uninstalled and reinstalled the app. Took less than a minute and wiped the slate clean.

**Comment by bendpx** [comment]
is it possible to subscribe to the organization and exclude specific repos?

**Comment by danrademacher** [comment]
Answered my own Q by doing another `/github subscribe greeninfo-network comments` and now comments are coming thru too. Did have to do that separately

**Comment by gimenete** [comment]
@bendpx you can install the github application on specific repos instead of installing the application in the whole org. That way the application will only receive notifications from those repos.

**Comment by bendpx** [comment]
@gimenete thanks! that will not help my use case. I have an org with 300 repositories, I want 299 of them to report and just one that is very noisy and gets automatic updates from the script is flooding the channel. currently, after subscribed to the org, I cannot ignore this one

**Comment by Jessicawatsonmiller** [comment]
@gimenete when I subscribe to the whole organisation, and then try to unsubscribe from a specific repo, I get an error saying I'm not subscribed to those repos. 

`/github subscribe Org-name`
`/github unsubscribe Org-name/repo`

> You're not currently subscribed to `Org-name/repo`
Use `/github subscribe Org-name/repo` to subscribe.

It happens with multiple repos in the org. I am not even sure from these errors whether I'm subscribed to any of the repos in the org. When I try:

`/github subscribe list`

I get:

>Subscribed to the following accounts
Org-name

And the only repos listed as subscribed are the ones I've listed manually. I am trying to subscribe to the whole org to catch newly created repos, and exclude non-dev repos.

**Comment by gimenete** [comment]
Hi @Jessicawatsonmiller 

Org and repo subscriptions are handled individually. When you subscribe to an org you are not actually subscribing to the list of individual repos. That's why subscribing to the whole org and then unsubscribing to one repo doesn't work, because you were not subscribed to that individual repo.

**Comment by Jessicawatsonmiller** [comment]
@gimenete what am I subscribed to then, when I'm subscribing to an org? And how do I subscribe to 'all repos within an org, including newly created ones'?

**Comment by bendpx** [comment]
@gimenete hey - any plan to support repo exclusion? 
the scenario where my org has 300 repos which I dont want to add repo by repo, but one of them is very noisy. it floods my channel and I'd be happy to ignore it

**Comment by iLemon** [comment]
Appreciate this. Had to make a script to subscribe to each individual repo previously haha

**Comment by cristianmtr** [comment]
> @gimenete hey - any plan to support repo exclusion?
> the scenario where my org has 300 repos which I dont want to add repo by repo, but one of them is very noisy. it floods my channel and I'd be happy to ignore it

Any update on whether this can is doable? Just ran into the same problem

**Comment by smariano88** [comment]
> @gimenete hey - any plan to support repo exclusion? the scenario where my org has 300 repos which I dont want to add repo by repo, but one of them is very noisy. it floods my channel and I'd be happy to ignore it

Any updates on this one?

**Comment by esaruoho** [comment]
@gimenete could this at least be reopened?

**Comment by farski** [comment]
@esaruoho I think repo exclusion should be a new issue. This feature has been working as described on the box for several years now.

**Comment by gimenete** [comment]
@esaruoho I'm sorry but I no longer work for this project.

**Comment by smariano88** [comment]
In our case, we have subscribed the whole organization to listen for changes in the develop branch of every repo, so in order to avoid notifications, I just push to a different branch. Really silly of me not to think about this before but I hope it helps someone else.

> @esaruoho I think repo exclusion should be a new issue. This feature has been working as described on the box for several years now.

Agree
