### ISSUE TITLE
help for subscription settings

### ISSUE THREAD

**Issue by cainlevy** [integrations/slack#392]
There's no mention of features in the `/github help` command, on https://slack.github.com/, or on https://empaticoorg.slack.com/apps/A8GBNUWU8-github. This makes them hard to discover for newcomers who find the default settings to be noisy.

**Comment by bkeepers** [comment]
Thanks for the feedback. I added this to our list of things to get fixed up soon.

**Comment by wilhelmklopp** [comment]
> who find the default settings to be noisy.

@cainlevy out of curiosity: what settings do you use that result in an acceptable level of noise?

**Comment by cainlevy** [comment]
@wilhelmklopp Ahh, so, I later discovered that our subscriptions all had `commits:all` enabled. I think it's the migration process: https://github.com/integrations/slack/issues/395

**Comment by esaruoho** [comment]
I actually bothered @izuzak about this via email, demanding to know why "GitHub Legacy Enterprise" shows comments and why "nu-GitHub" doesn't, and why proper help is missing from `/github help` - having something that lists all the subscription possibilities is _important_.
or at least introduce a link to https://github.com/integrations/slack#configuration ! geez guys!

**Comment by esaruoho** [comment]
The help was so hidden away that I thought nu-GitHub didn't even _have_ integration for dumping comments to Slack.
