### ISSUE TITLE
"trouble with your request" when subscribing to unknown feature

### ISSUE THREAD

**Issue by cainlevy** [integrations/slack#393]
There are only a few valid features. Attempting to subscribe or unsubscribe with a typo will return:

> Sorry, we had trouble with your request, but we're looking into it! If this is interfering with your work, please get in touch!

Ideally, this failure case would instead return a list of valid features.

**Comment by bkeepers** [comment]
Thanks @cainlevy, this is definitely something we need to fix up.

**Comment by bkeepers** [comment]
This has been fixed in #402. Let us know if you see any other issues related to this.
