### ISSUE TITLE
subscribing to new feature on existing channel returns noisy message

### ISSUE THREAD

**Issue by cainlevy** [integrations/slack#394]
When subscribing to a new feature on an existing channel, I consistently get:

> Only visible to you
> You're already subscribed to `organization/repository`

**Comment by bkeepers** [comment]
@cainlevy I'm not able to duplicate this. Could you [contact us here](https://github.com/integrations/slack#questions-need-help) with the name of the organization you are trying to subscribe to so we can dig into the logs?

**Comment by cainlevy** [comment]
Sent!

Also, I meant to say "existing repository". I've got websockets on the brain today.

**Comment by bkeepers** [comment]
Thanks for the report. Fixed in https://github.com/integrations/slack/pull/402
