### ISSUE TITLE
Comment on new issue via thread reply

### ISSUE THREAD

**Issue by henningko** [integrations/slack#400]
When an issue is created, I want to be able to use Slack's thread reply to comment on the issue in GitHub.

E.g. from here:
![image](https://user-images.githubusercontent.com/5890910/36773950-ebde6c8a-1c10-11e8-824d-ef139e8c0638.png)

... add a comment to the GitHub issue by replying in a thread: 
![image](https://user-images.githubusercontent.com/5890910/36774003-2281bc06-1c11-11e8-92fe-4d2341d48c0c.png)

Additionally, it'd be tremendous if one could run `/github comment #35 @user Have you tried XYZ?`

**Comment by isaachui** [comment]
I've been looking for something similar to this. Any update or any suggestions?

**Comment by nir0s** [comment]
I think this should be reopened.

**Comment by tarwich** [comment]
Duplicate of #660 which is still open and has more 👍 votes.
