### ISSUE TITLE
Comment notifications still active after unsubscribe

### ISSUE THREAD

**Issue by danahartweg** [integrations/slack#403]
I've unsubscribed our channels from `comments` on each repository (which leaves the remaining subscriptions as: `issues`, `pulls`, `statuses`, `branches`, `reviews`), but we're still receiving comments on pull requests.

In looking through the documentation, there doesn't seem to be a distinction between the type of comment and / or where it originates. Have there been any issues with these settings being cached or persisting incorrectly? Or have I completely misread the documentation regarding the `comments` setting?

**Comment by wilhelmklopp** [comment]
@danahartweg 👋 I'm in the process of fixing this up with #407 and #409 which should go out later today

Could you post an example of a comment activity message you received with these current settings?

**Comment by danahartweg** [comment]
@wilhelmklopp that's excellent news, and thanks for the quick turnaround! Here's a screenshot of one of the messages:

![screenshot 2018-03-01 14 44 13](https://user-images.githubusercontent.com/2279230/36865972-06e100c0-1d5f-11e8-9f5b-3709bfbf6454.png)

**Comment by wilhelmklopp** [comment]
@danahartweg thanks! #407 should fix this bug
