### ISSUE TITLE
Markdown code blocks tagged with a language don't render correctly

### ISSUE THREAD

**Issue by nwalters512** [integrations/slack#404]
For GitHub flavored markdown, I can write ```javascript to enable syntax highlighting:

    ```javascript
    await question.save()
    await question.reload()
    res.status(201).send(question)
    ```

This is rendered on GitHub as the following:

<img width="350" alt="screen shot 2018-02-28 at 4 50 50 pm" src="https://user-images.githubusercontent.com/1476544/36817661-91118372-1ca7-11e8-91ef-be727844de96.png">

However, in a Slack message corresponding to a comment/PR containing a code block, the `javascript` is included as part of the rendered code:

<img width="317" alt="screen shot 2018-02-28 at 4 51 19 pm" src="https://user-images.githubusercontent.com/1476544/36817697-ba199930-1ca7-11e8-8993-3c37dcc3bcda.png">

The language of a Markdown code block should be ommitted when rendering a Slack message.

**Comment by bkeepers** [comment]
Thanks for the feedback @nwalters512. We're tracking that over here: https://github.com/integrations/html-to-mrkdwn/issues/3

**Comment by nwalters512** [comment]
Gotch, didn't know that repo existed. Sorry for the duplicate!

**Comment by bkeepers** [comment]
@nwalters512 no problem at all! Thanks again for reporting the issue. Let us know if you see anything else awry!
