### ISSUE TITLE
Markdown in pull request notifications not always rendered

### ISSUE THREAD

**Issue by daneah** [integrations/slack#408]
Pull request notifications coming in seem about 50/50 split between rendered and raw markdown. Most of our pull request descriptions start with a link followed by a heading, so we see a mix of the properly rendered markdown along with notifications that look like:

```
[the link](https://the-url.com)

### The heading

...
```

**Comment by daneah** [comment]
@bkeepers @wilhelmklopp it's possible this occurs when updating an existing message with pull request statuses and the like. Haven't been able to watch it happen live just yet 😄

**Comment by wilhelmklopp** [comment]
@daneah yeah that's pretty much spot on! We've identified the cause for the bug and are figuring out a solution.

Some investigation is going on in #425

**Comment by pklingem** [comment]
this has been happening for our team for PR descriptions or replies containing images.  We rely on these images for morale!  Many of them are of squirrels!

**Comment by olivierGM** [comment]
We have noticed that markdown is not rendered on our repos that have continuous integration
![image](https://user-images.githubusercontent.com/1952240/37103507-691e32d8-21f8-11e8-84dc-8d754f211242.png)

And when there is no hook for the CI its fine:
![image](https://user-images.githubusercontent.com/1952240/37103557-841e27e6-21f8-11e8-8236-ac78cf6e18ad.png)

**Comment by daneah** [comment]
@olivierGM I think that is more evidence for the hypothesis above:

> it's possible this occurs when updating an existing message with pull request statuses and the like.

**Comment by stevesuh** [comment]
This is happening on issues as well for us as well as PR.

**Comment by wilhelmklopp** [comment]
> this has been happening for our team for PR descriptions and replies containing images. We rely on these images for morale! Many of them are of squirrels!

@pklingem the issue that tracks images is here: https://github.com/integrations/html-to-mrkdwn/issues/2

> This is happening on issues as well for us as well as PR.

@stevesuh Could you open a separate issue for this with steps to reproduce? Thanks 🙇

**Comment by cbeams** [comment]
I see that this issue has been closed as resolved, but I am still seeing the reported behavior in comments, as seen below, from https://bisq.slack.com/archives/C7UHH8UQM/p1521038700000431:

![image](https://user-images.githubusercontent.com/301810/37409818-881a695c-279f-11e8-8b68-e5aeb1c913b8.png)

Shall I open a separate issue for this?

**Comment by nickbouton** [comment]
Images don't seem to be showing up in GH comments:

![image](https://user-images.githubusercontent.com/169988/37417150-c7115e28-276c-11e8-9aa6-1673550ecded.png)

**Comment by bkeepers** [comment]
@nickbouton that'd be great, thanks!

**Comment by daneah** [comment]
^ @cbeams, that is 😛
