### ISSUE TITLE
Missing comments on some repo events

### ISSUE THREAD

**Issue by Roach** [integrations/slack#412]
When a PR is closed with a comment, the `closed` event gets posted to channel, but the comment is missing. The older app showed the comment, but not the closure event 🤷‍♂️ 

Old vs new:

![image](https://user-images.githubusercontent.com/32463/36875771-58edd3be-1d66-11e8-8438-90a96bfd5bb1.png)

**Comment by wilhelmklopp** [comment]
@Roach If you'd like comments to show up you need to subscribe to them explicitly. It's not enabled by default. You can do that with `/github subscribe slackapi/python-slackclient comments`

Unless you've already done that, in which case feel free to re-open the issue :)
