### ISSUE TITLE
Search issues feature

### ISSUE THREAD

**Issue by moul** [integrations/slack#419]
List issues matching a query: `/GitHub search <query>`

I don’t know how the slack API works, but the Giphy bot is really well done, it suggests multiple results that only the asker can see, then the clicked result is shared with the rest of the channel

**Comment by bkeepers** [comment]
Thanks for the feature request @moul. I think that'd be really cool.

**Comment by moul** [comment]
Hello **stale bot**, yes, this issue is still relevant.

The action of:
1. leaving slack to open chrome
2. type the address of the repo in the bar
3. type a search
4. click on the issue
5. copy the URL in the bar
6. close the tab + come back to slack
7. paste the link

is still one of the actions I do the most during working days :)

**Comment by fharper** [comment]
No stale bot, it is still relevant! I would very much like it!
