### ISSUE TITLE
No notification for push

### ISSUE THREAD

**Issue by mathieug** [integrations/slack#421]
I have multiple repositories in my organization which has the integration with slack.
I cannot see any event for one of my repository which is well subscribed on one of my channel (let's call it #tech-activities).

**Comment by mathieug** [comment]
Note that I can see the repository in the listing of `/github subscribe list`

**Comment by bkeepers** [comment]
@mathieug check out the docs on [configuration](https://github.com/integrations/slack#configuration) and make sure you have the `commits:all` setting enabled, which is disabled by default.

Let me know if that doesn't fix it and I'll reopen this issue.

**Comment by mathieug** [comment]
Thank you, I didn't know about the configuration.

Maybe you should talk about it in:
![image](https://user-images.githubusercontent.com/951183/36980740-7cf14da4-208b-11e8-9a64-61617210d411.png)
and also in:
![image](https://user-images.githubusercontent.com/951183/36980773-96cfbe90-208b-11e8-917a-4000b0ce8702.png)
