### ISSUE TITLE
All upgraded repos are left with a failing webhook for the old integration

### ISSUE THREAD

**Issue by xt0rted** [integrations/slack#428]
I upgraded to the new integration last week, and just now while reviewing some webhook changes I noticed all of my repos that were setup with the old integration still have the `https://hooks.slack.com/services/...` webhook setup with failing request. Should these be getting removed as part of the upgrade process? It's easy enough to go through and remove them, but I didn't see anything documented about needing to do so when I upgraded.

**Comment by wilhelmklopp** [comment]
@xt0rted Thanks for opening this issue! We came across this last week and I believe the legacy integration now automatically removes hooks when subscriptions are re-enabled in the new app.

If you're still running into this problem for new subscriptions that you're re-enabling, feel free to re-open this issue :D
