### ISSUE TITLE
Notification: push on pull request

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#43]
Fired on the `pull_request.synchronize` event

**Estimate:** 0.5 weeks

This should be in a thread for x minutes

**Comment by lochel** [comment]
When will this be implemented?

**Comment by bkeepers** [comment]
We don’t know yet but would welcome a pull request!

**Comment by DamienDennehy** [comment]
This would be a welcome addition. 

Every time a developer pushes to an open PR on my team they have to put a comment on the PR to the effect of "PR updated" or similar to push a Slack notification.
