### ISSUE TITLE
Custom Avatar/Name Feature

### ISSUE THREAD

**Issue by shnhrrsn** [integrations/slack#431]
With the previous Slack app we were able to setup custom names/app icons for each repo:

<img width="362" alt="screen shot 2018-03-06 at 4 31 12 pm" src="https://user-images.githubusercontent.com/42901/37059571-ce29fdee-215b-11e8-92ad-94f250ca0ef5.png">

With the new app, all repos appear with the standard GitHub avatar/name making it more challenging to identify different repos by a quick glance.  Being able to configure this on a per-repo basis would be great, either through the settings panel or the inclusion of a file the repo itself.

**Comment by bkeepers** [comment]
Hi @shnhrrsn, thanks for the request. We don't currently have plans to add support for custom icons, but we are considering including the organization avatar in #424.

Would you that solve your use case?

**Comment by shnhrrsn** [comment]
@bkeepers This wouldn't really help since we're using all private repos in the same org.

The larger problem here though IMO (and perhaps this belongs in a different issue) is that it's far too hard to determine the repo the action is taken on.  The slack notifications themselves just say "user pushed to branch" with no indication as to what repo that was on, and even when you open the app the repo is really minimized in the overall message:

<img width="425" alt="screen shot 2018-03-09 at 10 13 59 am" src="https://user-images.githubusercontent.com/42901/37214297-9c1f2814-2382-11e8-9d17-f264ea8ebb92.png">

There's a lot of information given, in a much larger font size, before you find out what repo this has even occurred on (and can be terrifying when you get it on mobile with no context at all)

**Comment by shnhrrsn** [comment]
Just a follow up of what this looks like on mobile:

<img width="618" alt="screen shot 2018-03-09 at 10 18 41 am" src="https://user-images.githubusercontent.com/42901/37214497-4c6987be-2383-11e8-828f-41d15f7ccb6d.png">

**Comment by nkbt** [comment]
Still missing this lovely feature, bot, keep it open please ;)

**Comment by nkbt** [comment]
I'm not sure it is a great idea for bot to auto-close feature requests =(

**Comment by Egorand** [comment]
Bumping this issue, our team would very much like to have this feature too. Any chance to see it in future releases?
