### ISSUE TITLE
Commit comments

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#432]
Since commit comments are used so infrequently, we didn't implement them in the initial version. A few people have requested them, so I'm opening this just so people can track them.

This isn't a priority for us right now, but someone else is welcome to try implementing them.

cc https://github.com/integrations/slack/issues/383#issuecomment-370021318

**Comment by TizocFranco** [comment]
My organization uses commit comments heavily. Is there a time frame for when this will be complete? Also, is there a way to uninstall/revert to the previous Github/Slack integration for the time being?

**Comment by mattbenic** [comment]
My org also uses these commits heavily (via the API from SmartGit) for code review purposes, and we're really keen to have them back. The previous version _did_ support them.

**Comment by MikeBadescu** [comment]
Code comments are important - the code provides context to the comment, helping with team communication (which is one of the purposes of GitHub and Slack). We would also like to have the code comments back.

This feature regression was not documented.

**Comment by atopiler** [comment]
Our team also uses commit comments quite heavily.  It was very unexpected to see that these are no longer supported, given that they worked flawlessly in the legacy integration.

**Comment by KingBrewer** [comment]
Same here. Our team would love to have this functionality back.

**Comment by freemarmoset** [comment]
Would also like this functionality back.

**Comment by rcaracaus** [comment]
Commenting was and still is a critical feature

**Comment by jonathancounihan-sage** [comment]
+1. We use the comments to communicate with the team on specific lines on each commit. The emailing is sometimes hit and miss, but the pings in slack were easy to find and highly visible.

**Comment by dominic-miglar** [comment]
+1

**Comment by mfonda** [comment]
Another +1 -- our team makes heavy use of comments and would love this functionality.

> This isn't a priority for us right now

@bkeepers is this still the case, or are there any plans in the works to implement this?

**Comment by shesternin0** [comment]
We need it feature too

**Comment by thornycrackers** [comment]
+1

**Comment by stephenbrady** [comment]
+1

**Comment by ouquoi** [comment]
+1

**Comment by jblanchette** [comment]
@bkeepers can you please reconsider priority; how did you classify that code review comments are "used so infrequently"?

it seems to me like this is one of the major reasons people use slack integrations and also one of the main purposes of a remote repository.

**Comment by mattwynne** [comment]
@bkeepers I missed the too, and I'd be interested in having a crack at implementing it I can get some pointers.

**Comment by bobgodwinx** [comment]
When is this feature going to be ready? Do we have a timeline?

**Comment by bkeepers** [comment]
>  I'd be interested in having a crack at implementing it I can get some pointers.

Thanks for being willing to explore this, @mattwynne.

See https://github.com/integrations/slack/blob/master/CONTRIBUTING.md#activity for docs on adding new activity messages.

Here's where the app listens for existing comment activity:

https://github.com/integrations/slack/blob/master/lib/activity/index.js#L43-L48 

You can subscribe to the [`commit_comment`](https://developer.github.com/v3/activity/events/types/#commitcommentevent) event and either update the existing comment message formatting to account for commit comments, or add a new one.

Feel free to CC me on the Pull Request and I'd be happy to give feedback.

**Comment by bkeepers** [comment]
Happy Monday! Thanks to @artnez, notifications for commit comments are now supported! Run `/github subscribe owner/repo comments` to turn them on.

See it in action in https://github.com/integrations/slack/pull/666#issuecomment-419984380

**Comment by mattwynne** [comment]
Thanks @artnez!

**Comment by sunandabansal** [comment]
Thanks a lot @artnez
