### ISSUE TITLE
Subscribe to file modifications on a branch

### ISSUE THREAD

**Issue by axos88** [integrations/slack#437]
I would love to see a feautre where it is possible to subscribe to specific CHANGES to a file, when pushed to a branch.

We have a CHANGELOG.md file in the root of our repository, and would love to automatically push notifications to slack when that file changes (with a diff for example, but just the fact that it happened would be awesome as well.)

**Comment by Redsandro** [comment]
I'm looking for this exact feature! I keep getting this result in Google when searching for tricks to notify myself when a certain file was changed.

**Comment by Roeefl** [comment]
+1 on this request

**Comment by dw2kim** [comment]
+1 on this request

**Comment by alice-engi** [comment]
Reposting from #1062:

If you need notifications about a changed file, you can use [NotiFunction App](https://github.com/apps/notifunction) and create notification with this code:

```javascript
// If this file is changed - it will trigger the notification
const FILE_TO_WATCH = 'README.md'

// This is where notification will go to
// could be a channel or a person's email.
const CHANNEL = '#test'

// Reacts to "push" event
// https://docs.github.com/developers/webhooks-and-events/webhook-events-and-payloads#push
exports.handler = async (input) => {
    let changedFiles = []
    
    // Iterate over commits in a push and collect modified files
    input.commits.forEach(c => {
        changedFiles = changedFiles.concat(c.modified)
    })

    // If our file is modified - send a notification
    // otherwise do nothing
    if (changedFiles.includes(FILE_TO_WATCH)) {
        return buildMessage(input)
    }
}

// Function that generates a Slack message
function buildMessage(input) {
    return {
        to: CHANNEL,
        text: `${FILE_TO_WATCH} was changed by ${input.sender.login}: ${input.compare}`
    }
}
```

Then connect it to the "push" event from github to send notifications like this:

<img width="819" alt="notification-example" src="https://user-images.githubusercontent.com/70848579/94835774-1e3ffe00-03e0-11eb-85b3-d1710aa823cd.png">
