### ISSUE TITLE
Emojis do not render inside labels

### ISSUE THREAD

**Issue by petetnt** [integrations/slack#439]
Github got [emojis in labels](https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/) ❤️ a short while ago. Sadly these labels don't render inside the Slack messages. Emojis do work in the comment bodies though

Expected

Pull request opened by petetnt
petetnt
#193 Emojis do not render inside labels
Github got [emojis in labels](https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/) ❤️ a short while ago. Sadly these labels don't render inside the Slack messages
...
Labels
Priority 1 :shipit:

Actual:

Pull request opened by petetnt
petetnt
#193 Emojis do not render inside labels
Github got [emojis in labels](https://blog.github.com/2018-02-22-label-improvements-emoji-descriptions-and-more/) ❤️ a short while ago. Sadly these labels don't render inside the Slack messages
...
Labels
Priority 1 :![image](https://user-images.githubusercontent.com/7641760/37157660-131effac-22f2-11e8-896d-accab3a74921.png):

**Comment by wilhelmklopp** [comment]
@petetnt I just tried to reproduce this, but emoji in labels seem to work for me?

![image](https://user-images.githubusercontent.com/7718702/37158125-82b9b682-22e2-11e8-80c0-fbadecbe4d00.png)

Could you share a screenshot of what you're seeing and also double check that the `:shipit:` emoji exists in your Slack Workspace?

**Comment by petetnt** [comment]
Hah, I think we just got terribly unlucky there, we had labels with emojis with names that don't exist in Slack with the same name like `:no_good_woman:` on GitHub is `:no_good:` on Slack.

Thanks for the quick response 👍 I love the new integration!
