### ISSUE TITLE
subscribe list not showing all

### ISSUE THREAD

**Issue by TimGurney** [integrations/slack#440]
It seems that the subscribe list command only shows 5 of the repos that you are linked to.

This isn't helpful if you are managing 50+ projects across 4 different orgs and want to ensure you have all of them linked in.

**Comment by wilhelmklopp** [comment]
@TimGurney `/github subscribe list` should definitely show all subscriptions, not just 5. Could you share a screenshot of the output of `/github subscribe list` you're seeing?

**Comment by TimGurney** [comment]
@wilhelmklopp ok, when taking the screenshot I spotted something I missed before.

By 'default' the list is shortened to 5 - but there is a 'show more' text link however this text link is at the end of the  5th repo name so I missed it, might be worth moving this onto a line underneath same as the 'show less link'

**Comment by TimGurney** [comment]
However it might be nice to have the list 'alphabetical' as it would make finding something I missed a lot easier.

**Comment by wilhelmklopp** [comment]
> @wilhelmklopp ok, when taking the screenshot I spotted something I missed before.

> By 'default' the list is shortened to 5 - but there is a 'show more' text link however this text link is at the end of the 5th repo name so I missed it, might be worth moving this onto a line underneath same as the 'show less link'

Thanks. We don't actually have control over the behaviour of "show more". This is natively done by Slack. I've made a note to raise this with Slack

**Comment by wilhelmklopp** [comment]
> However it might be nice to have the list 'alphabetical' as it would make finding something I missed a lot easier.

I do agree the list should be sorted. I'm currently thinking that sorting them based on the creation date  ascending would be most useful

**Comment by TimGurney** [comment]
Maybe multiple ways with different options?

Alphabetical would be ideal for me as I have multiple organisations and this would group them

**Comment by TimGurney** [comment]
As for show more that's fair enough maybe add it to the docs?

**Comment by wilhelmklopp** [comment]
> Alphabetical would be ideal for me as I have multiple organisations and this would group them

👍 I'm going to look into this now :)
