### ISSUE TITLE
Subscribe to a public repository

### ISSUE THREAD

**Issue by saveman71** [integrations/slack#454]
I tried to subscribe to an external dependency I use, which I'd like to follow closely for a few weeks until a particular bug is resolved.

I cannot figure out if this is supposed to be supported or not, as I get an error message asking me to add the app, which I did, to my account, assuming that it would use a token related to my account to pull the info from that particular public repo.

However, even after connecting my account, I still get the 'Unauthorized' error message.

**Comment by bkeepers** [comment]
Hi @saveman71, thanks for opening an issue.

You can only subscribe to a repository if the owner of that repository has installed the [Slack app on GitHub](https://github.com/apps/slack), which sends GitHub activity to Slack. Installing the app on your own account will only send activity from repositories you own.

This constraint is inherent in the design of [GitHub Apps](https://developer.github.com/apps/), so I don't see it changing in the foreseeable future. I know that's a bummer for this use case of subscribing to activity on open source projects you use.

Do you think you could ask the repository owner to install the app?

**Comment by saveman71** [comment]
No, I have absolutely no relations to that repository, it's just a dependency as any (e.g. angularjs). Thanks for answering my question. I figured this could work as the "watch" button in some way. I'll find another way!

**Comment by charlypoly** [comment]
@saveman71, as a workaround, you can use the RSS Slack app in combination of `https://github.com/:owner/:repo/releases.atom` 👀
