### ISSUE TITLE
Include link to branch with push notifications

### ISSUE THREAD

**Issue by chrisxaustin** [integrations/slack#456]
The `pushed to` notifications have a clickable commit message link, but not a clickable branch link.

Current format from push.js `summary()`:
```
`<${this.push.compare}|${noOfCommits} new ${commits}> ${pushed} to ${branch}`;
```

This should use a url similar to the one from push.js `commits()`:
```
      return `<${commit.url}|\`${sha}\`> - ${message}`;
```

**Comment by bkeepers** [comment]
Thanks @chrisxaustin. I agree this would make sense. This should be pretty easy for someone to implement if you want to submit a PR. Here are some pointers:

1. Here's the [push](https://github.com/integrations/slack/blob/master/test/fixtures/webhooks/push.json) payload we get from GitHub. It doesn't have a link to the branch, so we'll have to construct one.

1. You'll be updating [this function](https://github.com/integrations/slack/blob/master/lib/messages/push.js#L24-L31) in `lib/messages/push.js`

1. The link will be something like:
    ```js
    const branchUrl = `${push.repository.html_url}/tree/${branch}`
    ```

1. You'll then use this in the message:

    ```diff
    -    … new ${commits}> ${pushed} to ${branch}`;
    +   … new ${commits}> ${pushed} to <${branchUrl|${branch}>`;
    ```

If someone wants to open a pull request to get this started, I'd be happy to help push it over the finish line.

**Comment by agisilaos** [comment]
Since #515 is now merged, this issue should be closed, right? cc: @bkeepers

**Comment by bkeepers** [comment]
Yes, thanks!
