### ISSUE TITLE
Enable notifications on reviewer assignment for PR

### ISSUE THREAD

**Issue by cybairfly** [integrations/slack#459]
Reviewers assigned after the submission of a PR should be notified of the updated review request so that pull requester can check the PR first before assigning a reviewer or change the reviewers later on.

**Comment by bkeepers** [comment]
Thanks @cybairfly for the feedback. I agree that this would be a great feature. This is a duplicate of #382, so we'll track this there.

Thanks!

**Comment by yuqil725** [comment]
We are also looking for this feature, any update?
