### ISSUE TITLE
Markdown in comments does not get rendered

### ISSUE THREAD

**Issue by cbeams** [integrations/slack#461]
As originally posted at https://github.com/integrations/slack/issues/408#issuecomment-373049194, Markdown syntax in comments does not get rendered on the Slack notification side as expected:

From https://bisq.slack.com/archives/C7UHH8UQM/p1521038700000431:

![image](https://user-images.githubusercontent.com/301810/37409818-881a695c-279f-11e8-8b68-e5aeb1c913b8.png)

**Comment by stevesuh** [comment]
Still not rendering screenshots.

<img width="687" alt="screenshot 2018-03-22 14 34 38" src="https://user-images.githubusercontent.com/5025518/37790923-37f75fc6-2dde-11e8-9ae7-15ba803ab6de.png">
