### ISSUE TITLE
Configurable stale PR watcher

### ISSUE THREAD

**Issue by jandeschuttere** [integrations/slack#462]
Having information on new PRs and some activities on them are already useful.

Having the possibility to configure an amount of days a PR remains open before it is resolved could improve flows and follow up. Having this integrated in the bot itself would remove the requirement on added bots (and configuration management)

**Comment by bkeepers** [comment]
Hey @jandeschuttere, thanks for the feedback. Check out the [stale](https://probot.github.io/apps/stale/) app. It's built by the same team that built the Slack integration and should be able to do exactly what you want.

**Comment by jandeschuttere** [comment]
Thanks @bkeepers for the reference, I'll have a closer look at the app you mention and its features. I was merely hoping on getting a CTA through notifications in Slack, and have the ability to list up PRs within Slack to accommodate that CTA. But the primary question is indeed answered with the mentioned app it seems. Thanks again.
