### ISSUE TITLE
Unfurl Slack links on GitHub

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#477]
Often a discussion happens in Slack about work on GitHub, and that discussion includes valuable context that should be visible on GitHub.

One common way people accomplish this currently is to copy a link to a slack message and share it in a GitHub discussion. It would be super if those links were unfurled on GitHub

![unfurl slack links](https://user-images.githubusercontent.com/173/37624466-434ed3da-2b96-11e8-9017-4c8f2ff5ff06.png)

Dependencies:

- [ ] Ability to request read permission on specific messages from Slack since read access to all messages is a dangerous permission
- [ ] GitHub API for unfurling links

Estimate: 3 weeks (depending on implementation details of dependencies)

**Comment by philschatz** [comment]
I was looking at implementing this and was wondering... where should the confirmation message show up?

1. Should it show up as an ephemeral message in the channel if the Slack User can be determined (they linked their GitHub user account with their Slack account) or as a DM to the User?
1. What if the Slack User cannot be determined? Should it show as a public message in the channel that anyone can `[Accept]` or `[Cancel]`?

Also, I was thinking of adding it to `lib/activity/comment.js`; would that be an appropriate place?

**Comment by frank-tran-tm** [comment]
Is it possible to reopen this issue? It sucks that you can't get a preview of a discussion topic when sharing the url in slack 😕
