### ISSUE TITLE
Preserve context of Slack conversation as a GitHub comment

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#479]
Often a discussion happens in Slack about work on GitHub, and that discussion includes valuable context that should be visible to people on GitHub.

We don't know how it will work, but we want to figure out a way that a user can select a message or span of messages and sync them back to GitHub.

Ideas:
- Unfurl links to Slack on GitHub #477
- Comment on a new issue via issue threads #400
- Add emoji reaction to a comment to sync it back to GitHub?
- … ?? …

How else could we preserve context? Especially when a conversation spans multiple messages?

**Comment by xt0rted** [comment]
Trello's [slack integration](https://trello.com/platforms/slack) has something like this where you can click an `Attach Conversation` button. I've never tried it out though.
