### ISSUE TITLE
/github subscribe/signin default to github.com 

### ISSUE THREAD

**Issue by ssadasivuni** [integrations/slack#482]
It looks like the /github subscribe/signin default to https://github.com even though a custom url is specified.

`/github subscribe https://github.<company>.com/owner/repo`
`/github signin https://github.<company>.com`

**Comment by bkeepers** [comment]
Hi @ssadasivuni, thanks for opening an issue. GitHub enterprise is not supported by this new integration yet. See https://github.com/integrations/slack#requirements for more information.

**Comment by ssadasivuni** [comment]
Thanks @bkeepers.
