### ISSUE TITLE
Feature subscriptions aren't channel-specific

### ISSUE THREAD

**Issue by farski** [integrations/slack#483]
Since subscribing to repos is independent of channel (eg, channel A can be subscribed to repo M, and N; channel B can be subscribed to repo X and Y; channel C can be subscribed to repos M and X) it would be very beneficial if the features for each subscription were also channel-specific. I may only want channel A to get **commit** notifications about M, and channel C to only get **issue** notifications about M. At the moment, though, even if I `/github subscribe acme/M commits` channel A, as soon as I `/github subscribe acme/M issues` in channel C, channel A also starts getting notifications for issues.

A more realistic example is that I want `#github-issues` to get issue notifications for all my repos, and `#github-commits` to get commit notifications for all my repos. As it is right now, that doesn't seem possible because the there's no way to prevent both channels from getting both types of notifications, since their subscription lists always match.

**Comment by bkeepers** [comment]
Hey @farski, thanks for the report. This does not sound like intended behavior. I know I've subscribed to the same repository with different settings in each channel before. Could you contact us at support@github.com with more information on which repositories you're subscribing to and which channels and we can dig in to see if there's something weird going on here?

fyi @izuzak

**Comment by farski** [comment]
Based on what was said in #484 this is likely just a case of being subscribed to more features by default than expected. I will do some testing and report back.

**Comment by farski** [comment]
Can confirm this is simply a result of weird/confusing defaults, and the fact that subscribing to a specific feature doesn't actually do that.

**Comment by bkeepers** [comment]
Ok, thanks for the update. We'll get #484 resolved. Thanks again for taking time to report issues!
