### ISSUE TITLE
Slack fallback text doesn't include repo information

### ISSUE THREAD

**Issue by knolleary** [integrations/slack#485]
The slack app uses the `fallback` property of the received message as the text of any desktop/mobile notifications it triggers.

I appreciate the intention to keep the notification text brief, but without the repo information I find I get a series of `1 commit pushed to master` notifications without the context of which repo it's related to.

In our project we have a single #github channel subscribed to all the project's repos. Some I care about more than others.

Having just upgraded from the old github slack app, I find I can no longer mentally filter the notifications I care about at a glance - I have to go look at slack to get that small bit of extra detail.

Would you consider a PR that adds the repo name to the name of the notification text?

I think the simple change would be to add the appropriate bit just to the `fallback` property of the slack message: https://github.com/integrations/slack/blob/master/lib/messages/push.js#L38

**Comment by bkeepers** [comment]
Hi @knolleary, thanks for opening the issue. I agree that this would be great to include.

> I think the simple change would be to add the appropriate bit just to the fallback property of the slack message: https://github.com/integrations/slack/blob/master/lib/messages/push.js#L38

Yep, that's right. We should probably include `repository.full_name` in the fallback text on all notifications.
