### ISSUE TITLE
Extraneous escaping of dash in unfurled issue content

### ISSUE THREAD

**Issue by aoberoi** [integrations/slack#488]
I linked to [this issue](https://github.com/slackapi/node-slack-sdk/pull/519) and the unfurl mysteriously had a slash (`\`) before the dash (`-`) that isn't in the issue body. Screenshot:

![extraneous_escaped_dash](https://user-images.githubusercontent.com/494795/37804560-0bc58cca-2df2-11e8-977d-60362fade0db.png)

**Comment by bkeepers** [comment]
Thanks for reporting. This was fixed by #504
