### ISSUE TITLE
Regression with rendering @mentions

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#491]
There's currently an issue with rendering @mentions:

<img width="469" alt="slack_-_github" src="https://user-images.githubusercontent.com/173/37856673-ba0468f2-2ec3-11e8-8874-1ccb66130267.png">

This appears to be caused by a change in how GitHub renders the `body_html` property, which used to include an absolute URL, and now is only a relative URL.

**Comment by iancanderson** [comment]
@bkeepers we deployed a fix for this that went out on Friday. Could you confirm that this is now behaving as expected? Thanks for reporting!

**Comment by wilhelmklopp** [comment]
@iancanderson Thanks! This is working again 🤘
