### ISSUE TITLE
Not seeing organisation

### ISSUE THREAD

**Issue by macmule** [integrations/slack#492]
This Github account is part of our companies GH organisation: https://github.com/dataJAR

But I cannot see that organisation when adding this new integration, maybe a rights issue?

**Comment by wilhelmklopp** [comment]
@macmule 👋 Would you mind reaching out to [GitHub support](https://github.com/support) with this issue? 
They'll be able to assist you with this problem.

Unfortunately, it doesn't look like this is something we can influence as part of this integration
