### ISSUE TITLE
Markdown code block language hint is visible in Slack

### ISSUE THREAD

**Issue by will123195** [integrations/slack#505]
Github supports language hints to enable syntax highlighting.

For example, this markdown:

    ```js
    return foo
    ```

is rendered like this on github:
```js
return foo
```

However, the language hint unexpectedly appears in slack:

<img width=200 src="https://user-images.githubusercontent.com/242760/38216013-b738e04c-3686-11e8-9aaa-12327cec9f46.png" />

**Comment by bkeepers** [comment]
Thanks @will123195, this should have been fixed in #504. Are you still seeing issues?

**Comment by will123195** [comment]
I observed this behavior after making a comment on Github about 30 minutes ago.

**Comment by bkeepers** [comment]
@will123195 thanks. I see you're talking about comment notifications, which weren't being properly rendered yet. Should be fixed now: https://github.com/integrations/slack/pull/481

**Comment by will123195** [comment]
Yep it's fixed now!
