### ISSUE TITLE
Private Unfurl Feedback issue

### ISSUE THREAD

**Issue by wilhelmklopp** [integrations/slack#507]
Today we early-access shipped private unfurls. It's limited to only a select group of channels because the current implementation requires you to click a button every time you share a link, so it's quite annoying.
The current implementation is captured by the two gifs below:
Rich preview demo:
![show rich preview](https://user-images.githubusercontent.com/7718702/38211992-281168c0-36b4-11e8-9302-2b611590d173.gif)

Dismiss demo:
![dismiss](https://user-images.githubusercontent.com/7718702/38212000-2dc7e06e-36b4-11e8-885b-7bb4bd423a03.gif)

## What's next for private unfurls?
- [x] A proper flow for when you don't yet have your GitHub account linked
- [x] Settings
   - [x] To indicate that you always want to automatically show rich previews for this repo in this workspace
   - [x] To indicate that you always want to automatically show rich previews for all repos in this workspace?
   - [x] To say you never want to get prompted about private resources
   - [x] /github settings to change settings

## Please put feedback in this issue

If you're part of a channel where private unfurls are currently enabled, please put all relevant feedback in this issue. If you're sharing screenshots please make sure to obscure any information you don't want to be publicly visible.

**Comment by bkeepers** [comment]
Might have been a fluke, but saw this:

<img width="735" alt="slack_-_github" src="https://user-images.githubusercontent.com/173/38269688-cc58251c-3746-11e8-80b9-c26bf1c669c5.png">

The message unfurled (which you can see in the top of the screenshot, but the prompt was never dismissed, and slack showed a Timeout error.

**Comment by eosrei** [comment]
I'm sure many people like this, but don't want any unfurls at all. They take up far too many pixels.

**Comment by bkeepers** [comment]
The prompt for unfurling a private link appears in the main channel when the link is shared in a thread.

<img width="972" alt="slack_-_github" src="https://user-images.githubusercontent.com/173/39316604-281c7452-493f-11e8-8a1b-fbd5fd62cb72.png">

**Comment by wilhelmklopp** [comment]
@irvin thanks for the bug report! Did you also only see one unfurl prompt for both links?

**Comment by wilhelmklopp** [comment]
@irvin I just tried to reproduce this and I don't seem to be able to. Is it possible that pull 1294 was already unfurled in the channel in the previous 30 minutes? In that case it would not have been unfurled again

**Comment by irvin** [comment]
@wilhelmklopp yap, I couldn't reproduce now either. 
(But I was able to on 3 days ago, verified with some really old PR links that time...)

Maybe it's some random internet issues ;P

**Comment by tcbyrd** [comment]
This is a Private unfurl of a markdown document. If the link contains a `#` parameter to a sub-section of the document, I'm seeing this error:

![image](https://user-images.githubusercontent.com/13207348/40329339-37a576ee-5d17-11e8-862f-055bd10d5e4d.png)

Public unfurls work, but just unfurl from the top of the README.md file, not the section that's being referenced. Private unfurls work if you just post the url without any hash parameters.

**Comment by hiimbex** [comment]
<img width="1685" alt="screen shot 2018-06-08 at 1 02 57 am" src="https://user-images.githubusercontent.com/13410355/41139787-de3be508-6ab7-11e8-95d4-a7058ea43993.png">

I get the prompt when attempting to share this link: https://github.com/topics/probot-plugin which is to a GitHub topics page.

**Comment by rsyring** [comment]
It just doesn't work for me:

![image](https://user-images.githubusercontent.com/109467/41330301-ae5d93e4-6ea0-11e8-855a-b1ba12a89b50.png)

But the bigger issue is that I can't turn off the prompt.  That's what I would like to do as I don't really want this feature and don't want the distraction of having it always ask me whenever I post a link to a private repo (which you can imagine happens quite often).  

Thanks.  :)

**Comment by wilhelmklopp** [comment]
@rsyring you may have github unfurls disabled on your workspace, and that's why you're seeing the error. [More information here](https://get.slack.help/hc/en-us/articles/204399343-Share-links-in-Slack#turn-off-link-previews-for-specific-sites). 

Better error message for that is coming soon: https://github.com/integrations/slack/pull/617

In terms of disabling private unfurls, you will get a message with an option to do that after you've dismissed the prompt 5 times.

**Comment by rsyring** [comment]
@wilhelmklopp you are correct, I have unfurls disabled.  

> In terms of disabling private unfurls, you will get a message with an option to do that after you've dismissed the prompt 5 times.

Would love to see that prompt be an option on the first "ask".  It's not intuitive at all that ignoring five times would eventually get the prompt to ignore.  This is honestly been a very frustrating experience for me, to the point that I was considering removing the GH bot from our Slack (mostly because I thought the prompts were never going to go away).

**Comment by wilhelmklopp** [comment]
@rsyring thanks for the feedback! I like the idea of adding a "Don't prompt me again" option in the initial prompt. Would you mind opening a separate issue for that on this repo? Thanks!

**Comment by rsyring** [comment]
@wilhelmklopp sure, here you go: https://github.com/integrations/slack/issues/620

**Comment by jaller94** [comment]
I suggest to add a button that offers users to mute rich preview suggestions for the repository.

My employer has a some private repos and I don’t want to grant access to those to the Slack integration.
GitHub on Slack asks me if I want to add a rich preview when posting links for those. I dismiss those each time.

Currently my only option to mute the rich preview suggestions for those private repos is the global mute option.

<img width="783" alt="GitHub asking on Slack if I get too many prompts. I can then mute the integration for 24 hours, forever or get asked every time I send a link." src="https://user-images.githubusercontent.com/10872136/41689544-ecb8e0c0-74a5-11e8-85bd-40902d776f3f.png">

I wish there was an option for me as an individual user for individual repos to be excluded.

**Comment by wilhelmklopp** [comment]
@jaller94  thanks for the feedback! ✨ 

Would you mind opening this as a new issue on this repo, so that we can keep track separately?

**Comment by wilhelmklopp** [comment]
Closing this generic feedback issue that was intended only for the early-access period of private unfurls which concluded several weeks ago. 

Please post any feedback for private unfurls (or any other part of the slack integration) in a new issue on this repo. Thanks ❤️
