### ISSUE TITLE
Table formatting is lost between Github and Slack

### ISSUE THREAD

**Issue by tedivm** [integrations/slack#509]
Tables that look great in Github comments are coming through really badly now- every element is put on it's own line.

**Comment by hzoo** [comment]
Example of this https://github.com/babel/babel/pull/8016 since we use a table in our PR template

<img width="397" alt="screen shot 2018-05-23 at 4 03 06 pm" src="https://user-images.githubusercontent.com/588473/40448200-d48dff62-5ea2-11e8-894f-c41f46ded4b1.png">

**Comment by tedivm** [comment]
This is completely relevant and the "wontfix" label is inappropriate. I think if you're going to replace existing integrations that work with new ones you should do your best to actually match the functionality from the first.

**Comment by wilhelmklopp** [comment]
👋 We removed tables from showing up in Slack here: https://github.com/integrations/html-to-mrkdwn/pull/30 because of the problems described here and because we didn't see a great way to get tables to format nicely in Slack.

If y'all have any ideas for how to make tables render nicely in Slack, we'd love a contribution over on the html-to-mrkdwn repo 🙏

**Comment by tedivm** [comment]
The old slack integration for Github had working tables that looked great. If it worked then why can't you make it work now?

This whole new integration has been pretty terrible, and it's disappointing that you're settling issues by simply removing features that used to work.

**Comment by wilhelmklopp** [comment]
Just took a quick look and it seems like in the old integration tables were just showing up as plaintext as opposed to any kind of rendered version?
![image](https://user-images.githubusercontent.com/7718702/53353961-baa94100-391d-11e9-8b9e-2720a39f3981.png)

@tedivm to confirm, even though the table shows up like this, you would still prefer to see it in Slack as opposed to it being filtered out?

>This whole new integration has been pretty terrible

I'm sorry to hear this! If you have any specific feedback you'd like to share feel free to open another issue 🙂

**Comment by tedivm** [comment]
Here's my use case. I run a Github App called [GitConsensus](https://www.gitconsensus.com/), which is used by a few "self running" projects.

The output of the old extension- while not perfect- was at least readable. Here's an example of how it looks in slack-

<img width="632" alt="screen shot 2019-02-25 at 10 32 32 am" src="https://user-images.githubusercontent.com/121709/53359812-d7775180-38e8-11e9-9885-094c9cfbc846.png">

**Comment by tedivm** [comment]
Here's the actual issue that prompted that slack notification - https://github.com/ScreepsQuorum/ScreepsAutoSpawner/pull/6#issuecomment-466231127
