### ISSUE TITLE
Pull request approvals or change requests displayed as comments

### ISSUE THREAD

**Issue by mikiest** [integrations/slack#512]
Since yesterday 04/05/2018, pull request approvals or change requests are displayed as comments, e.g.:

`mikiest commented on other_user pull request`
instead of 
`mikiest approved other_user pull request`

GitHub preview colour is also incorrect (matches the "comment" event).

Has a new version been published around that time?

**Comment by wilhelmklopp** [comment]
Thanks for reporting this! Fix is coming within the next couple of minutes :)
