### ISSUE TITLE
Unfurl: private links

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#52]
A user sees an ephemeral prompt to verify that the private link should be unfurled (always, this time, never)
A user sees an unfurl of a private link.

**Estimate:** 2 weeks

## Private unfurls are available via EARLY ACCESS
Read through this comment to find out how to get early access: https://github.com/integrations/slack/issues/52#issuecomment-387410861

## Road to private unfurls
Things that need to be done before general availability:
- [x] Persistent user settings #528
- [x] Better flow in case a user has not yet linked their GitHub account (building on top of #536)
- [x] Let users change settings using `/github settings`
- [ ] dm user if chat.ephemeral doesn't work because app is not in channel
     - [ ] ~Can we prompt users via additive permissions to add GitHub to the channel?~ Nope, not really :/
- [ ] Remove early access for private unfurls :tada:

**Comment by olivierlacan** [comment]
I was a bit surprised when after subscribing a channel to a private repo, private URLs to code from that same repo weren't unfurled. That seemed like what this suggested: 

![image](https://user-images.githubusercontent.com/65950/36686685-815f01f6-1b27-11e8-80b6-3a0ebb75cb40.png)

It seems like until this feature is developed, the site should be updated to say "Public code snippets" to clarify. I wouldn't surprised if a lot of people made the same assumption I did and show up here to complain. 😄

**Comment by brennaheaps** [comment]
@olivierlacan Hi! 👋

**Comment by bkeepers** [comment]
Thanks @olivierlacan. The copy did say "public" at one point, but it must have gotten dropped in one of the iterations.

Private unfurls are coming very soon.

**Comment by krumware** [comment]
+1 for confusing language, expected private repos to work. 
Regardless, excited about this coming feature, thanks folks!

**Comment by bradical** [comment]
I had a question about how this will ultimately function. Will Private Repository unfurls depend on being subscribed to that repository in the channel or will it just use the perms of the authorizing user to determine access to the URL and could use any URL for any repo regardless of channel subscriptions?

**Comment by wilhelmklopp** [comment]
> Will Private Repository unfurls depend on being subscribed to that repository in the channel or will it just use the perms of the authorizing user to determine access to the URL and could use any URL for any repo regardless of channel subscriptions?

It will most likely be based on the access of the user who posts the link. So any URL for any repo will work, but there may be an additional step where you need to confirm that you do want the link unfurled.

**Comment by bradical** [comment]
Thank you! Looking forward to this.

**Comment by micahstubbs** [comment]
this would be incredibly useful.  can't wait for this feature to land

**Comment by kooshywoosh** [comment]
+1

**Comment by micahstubbs** [comment]
would really like to see this land soon.  is there anything that the community can do to help?

**Comment by deybhayden** [comment]
#522 looks to have been opened in the past 24 hours

**Comment by donbecker** [comment]
The PR referenced here was merged, has this been fixed/released?

**Comment by micahstubbs** [comment]
just tested this by pasting a private repo PR link into a slack channel with the github integration enabled.  no unfurl for me, so doesn't seem to have been released widely yet.

**Comment by wilhelmklopp** [comment]
# Early Access for Private Unfurls
![show rich preview](https://user-images.githubusercontent.com/7718702/38211992-281168c0-36b4-11e8-9302-2b611590d173.gif)

Hey folks 👋 
We're ready to open up the early access for private unfurls to anyone who is interested
@olivierlacan @krumware @bradical @micahstubbs @deybhayden @donbecker 

## What you need to do to be included
1. Agree to the [pre-release agreement](https://github.com/prerelease/agreement)
2. Decided whether you want your entire Slack workspace early access enabled or only one channel
3. Provide us with your slack user id and either your team id or your channel id and [contact support using this template](https://github.com/contact?form[subject]=GitHub%20Slack%20Integration%20Private%20Unfurls%20Early%20Access&form[comments]=I%20have%20signed%20the%20early%20access%20agreement%20and%20would%20like%20to%20be%20included%20in%20the%20early%20access%20for%20private%20unfurls.%0D%0A%0D%0Aslack%20team%20or%20channel%20id:%0D%0Aslack%20user%20id:)
    - You can find out your Slack channel or team id using `/github debug`
4. We'll confirm via email when you're added
5. Post a private link in Slack and see it in action 🎉 

## Feedback
Have feedback for private unfurls? Please post it in this issue: https://github.com/integrations/slack/issues/507

**Comment by krumware** [comment]
Thanks!!

**Comment by borekb** [comment]
Is this still invite / early access only? [This announcement](https://blog.github.com/2018-05-17-new-improvements-to-slack-and-github-integration/) makes it sound like the feature is generally available but I'm not getting private repo previews even after removing and re-adding GitHub integration.

**Comment by rmccue** [comment]
@borekb You may need to `/invite @github` to the room as well.

**Comment by wilhelmklopp** [comment]
As of last week, private unfurls are now generally available! 

Thanks for your participation and feedback ✨

**Comment by iDVB** [comment]
@wilhelmklopp "generally available" meaning we need to follow the pre-release steps above or need only approve the default app? 

I've only just approved the default app and `/github subscribe blah/blah` in our channel and we are **not** getting private unfurls. Which is how my googling brought me here.

**Comment by wilhelmklopp** [comment]
@iDVB that's correct. This should work automatically now. Could you double check that you're not encountering any of the things mentioned [here](https://github.com/integrations/slack#link-previews) and then write in at https://github.com/contact with the details of the problem you're seeing?

**Comment by wilhelmklopp** [comment]
Hey!

Yep, that's correct. We don't have previews for commit links yet. If this is something you want to work on, we'd be more than happy to accept that contribution :)

**Comment by billybooth** [comment]
Basically just set up the integration using the instructions in the [readme](
../blob/master/README.md), sign in to GitHub via the integration as a user with access to the private repo, and attempt to post a link and unfurl it when prompted.  IIRC, you’ll be redirected to GitHub and prompted to grant access to your repo.  It’s pretty self-explanatory if you just try it.

**Comment by lacostenycoder** [comment]
@billybooth I did all of the above.  We had had a github slack app installed for over 2 years. But I did the steps anyway.  Still  no unfurl.  It works, and already did, with public repos.  What am I missing?

**Comment by lacostenycoder** [comment]
Figured it out... it was a bit tricky, but I hacked it! LOL

**Comment by ninja-** [comment]
any plans for mattermost integration?
