### ISSUE TITLE
Invite new members via slash command

### ISSUE THREAD

**Issue by abinoda** [integrations/slack#529]
Hope this makes sense as its own issue – it is related but out of the scope of [Take action via slash commands](https://github.com/integrations/slack/issues/474).

It would be great to be able to invite some to an org via a command like:
```
/github invite myorg/team username
```

**Comment by wilhelmklopp** [comment]
I'd love if this was possible! Especially if `username` could also be a Slack handle. 

I wonder if the org admin permissions you'd need for this are going to make this challenging for us to implement

**Comment by abinoda** [comment]
I think so
