### ISSUE TITLE
Marketplace app management via slash commands

### ISSUE THREAD

**Issue by abinoda** [integrations/slack#530]
I think it'd be very cool to be able to discover and manage Marketplace Apps with slash commands.

I think it could be designed similarly to existing package managers/CLIs (ie. `gem list`, `npm install`). Another example would be how the GUI in Sublime Text works for finding and installing packages.

Here are some ideas:
```
# List all available Marketplace apps
/github apps discover

# List installed GitHub apps
/github apps list

# Install app
/github apps install pullreminders
```

**Bonus:** how cool would it be if the GitHub bot listened for certain types of messages and suggested the `/github apps discover` command? This could be triggered if a user types a certain term or invalid command and display a message like.

**Comment by abinoda** [comment]
I think so

**Comment by andymckay** [comment]
That would be great for free apps. If it was a paid app and the user would have to agree to some billing flow, then we'd probably have to bounce the user to the relevant github page.

Is there an existing search command for the Slack API? Maybe we could use that command to search for Marketplace items.
