### ISSUE TITLE
The `/github subscribe [repository name]` Command Fails To Subscribe In A New Channel

### ISSUE THREAD

**Issue by codebymark** [integrations/slack#559]
The GitHub app returns the following message when using the `/github subscribe [repository name]` command _"Either the app isn't installed on your repository or the repository does not exist. Install it to proceed."_ despite supplying a valid repo URL and having already installed the GitHub app on the Slack Workspace.

This message is returned when attempting to subscribe to a repo in a channel you have not previously granted access to either at during the initial install flow or via the **GitHub Settings** page here - https://slack.com/apps/A8GBNUWU8-github

**Steps to reproduce**
1. Install the GitHub app (https://slack.com/apps/A8GBNUWU8-github) Select the **No channels** option or install in a single channel.
2. Invite the GitHub app to a public or private channel or type `/github` and Slackbot will post an **Add to this conversation** button.
3. Try to add a new repo using the `/github subscribe [repository name]` command.
4. The repo is not added. Clicking the **Install Github App** button results in a GitHub `404` page.

**Comment by wilhelmklopp** [comment]
@codebymark I can't seem to reproduce this. Would you mind writing into support at https://github.com/contact and include details such as the URL of the repository, and the URL of the 404 page?

**Comment by codebymark** [comment]
Thanks @wilhelmklopp I've sent thought the details and some screenshots via the contact form. Cheers.

**Comment by codebymark** [comment]
Resolved via ticket. Thanks.

**Comment by siddharthgopi** [comment]
Hey @codebymark, mind sharing what worked or you? Facing this same issue.

**Comment by codebymark** [comment]
Hi @siddharthgopi,

I think my GitHub auth was stale. I cleared the cache, reopened the browser and once I signed in again everything started working as expected. I hope this helps.

**Comment by BradySheehan** [comment]
@esetnik  I am currently experience the same issue as you with the same error message.

**Comment by RoryMcCrossan** [comment]
Same issue here. If anyone has solved this, please share exact steps.

**Comment by joanrodriguez** [comment]
Has the same problem, turns out the link was wrong.

Visiting https://github.com/apps/slack/installations/new solved it for me.

Stumbled upon the link here: https://github.com/portainer/portainer/issues/1955

**Comment by esetnik** [comment]
@wilhelmklopp can we get this issue reopened?

**Comment by esetnik** [comment]
@joanrodriguez That worked for me. The invalid url seems to be coming from https://github.com/integrations/slack/blob/0cfaabaa04fe5db6a4d8c33d5d71ad1760a2f32a/lib/github/index.js#L25

**Comment by gimenete** [comment]
The wrong URL was due to a change on github.com. It is fixed now so you should always be redirected to the right URL: https://github.com/apps/slack/installations/new

**Comment by webcat12345** [comment]
https://github.com/integrations/slack/issues/559#issuecomment-424722613

This saved my life. @joanrodriguez You are a lifesaver :+1 :)

**Comment by klickparkdominik** [comment]
I am slack org owner and installed this app.

When I try to subscribe to `/github subscribe directus/directus` an error occures as provided above.
_Either the app isn't installed on your repository or the repository does not exist. Install it to proceed._

When I try to subscribe to `/github subscribe shopware/platform` it does work though.

Both are public repositories not owned by me or my org.

I can't seem to find the issue.
Can anybody confirm this?

**Comment by ArturSmiarowski-Schange** [comment]
I have the same issue as @klickparkdominik 
Was able to subscribe to spring-projects but unable to spring-projects/spring-boot
I was able to subscribe to elastic/elasticsearch
But I can't subscribe to stripe/stripe-java

It seems that the integration works only on some public repos. I have the message:
`Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.
Note: You need to be an organization owner to install the app (or ask one to install it for you).`

But when I enter the link, the app is installed.

**Comment by ar5000** [comment]
Having the exact same issue- trying to subscribe to a private repo owned by an organization.  I've installed Slack in GitHub and GitHub in Slack.

**Comment by natedunn** [comment]
I have a feeling this is a private repo related issue. Same issue here.

**Comment by manoadamro** [comment]
same issue here, can't subscribe to a private repo, owned by me. I have installed github on slack, slack on github and given slack access on github.

**Comment by JunjieLeiCoe** [comment]
> Has the same problem, turns out the link was wrong.
> 
> Visiting https://github.com/apps/slack/installations/new solved it for me.
> 
> Stumbled upon the link here: [portainer/portainer#1955](https://github.com/portainer/portainer/issues/1955)

This works

**Comment by Temurin** [comment]
Just adding that I was getting this error because I was using the Clone link copied from my GitHub repo page (ie. https://github.com/org/repo.git) as my repo URL. Eventually found a clue in #679 that it might work without the .git on the end, and it did.

That is, /github subscribe https://github.com/org/repo
