### ISSUE TITLE
Configuration: /subscribe owner

### ISSUE THREAD

**Issue by bkeepers** [integrations/slack#56]
`/github subscribe owner` to subscribe to notifications for an account

**Estimate:** 0.5 weeks

**Comment by anowlcalledjosh** [comment]
This would be awesome to have, and a clear improvement over the "legacy" GitHub integration :)

**Comment by anowlcalledjosh** [comment]
As before, this would still be a lovely feature to have.

**Comment by wilhelmklopp** [comment]
This has shipped!
