### ISSUE TITLE
Slack is requesting updated permissions

### ISSUE THREAD

**Issue by nikmolnar** [integrations/slack#588]
According to the docs, this integration only needs read permissions to GitHub resources, and we've had it installed for a while now without problems.

However, it just requested write permissions, with no action from our end. Any ideas about what's going on?

<img width="526" alt="screen shot 2018-05-17 at 10 12 54 am" src="https://user-images.githubusercontent.com/2422416/40193107-2d89811e-59bb-11e8-9c32-94fe727e65e5.png">

**Comment by bkeepers** [comment]
We just rolled out some new features! https://blog.github.com/2018-05-17-new-improvements-to-slack-and-github-integration/

Doc updates are in #586

**Comment by nikmolnar** [comment]
Ah ha! Thanks, @bkeepers

**Comment by andymckay** [comment]
That page has been updated, so it doesn't throw a 404, but a helpful message saying "The Slack app github is already up to date."
