### ISSUE TITLE
Configuration information is missing from the help command and integration homepage

### ISSUE THREAD

**Issue by magroski** [integrations/slack#592]
There's nowhere besides [here](https://github.com/integrations/slack#configuration) saying that you can pass [features] to the subscribe/unsubscribe command

**Comment by steveoh** [comment]
I would like to see that information in the help of the slash command

**Comment by webOS101** [comment]
For cleanup purposes, there is a note about this in `/github` help, but #718 should be considered a followup to make it more useful.
