### ISSUE TITLE
Raw links to binary files spew a lot of garbage into a channel

### ISSUE THREAD

**Issue by r4v5** [integrations/slack#593]
Steps to reproduce:
Link the following two URLs in a channel that has the new GitHub For Slack integration turned on, such that GfS is doing the link expansion of the first link:
1) https://github.com/jenkinsci/emotional-jenkins-plugin/blob/master/src/main/webapp/images/sad-jenkins.png?raw=true
2) https://raw.githubusercontent.com/jenkinsci/emotional-jenkins-plugin/master/src/main/webapp/images/sad-jenkins.png

The url for 1) is obtained by doing a "right-click" / "copy image address" from the repository listing https://github.com/jenkinsci/emotional-jenkins-plugin/blob/master/src/main/webapp/images/sad-jenkins.png. We would assume it would be served up as an image, but instead it renders as though somebody threw the text content of the file into a ``` block.

![screen shot 2018-05-22 at 4 53 38 pm](https://user-images.githubusercontent.com/789416/40392335-e2983db0-5de0-11e8-8118-9cb5ef8b9633.png)

It'd be great if some kind of logic was used to avoid trying to render binary files as text here.
(I've also seen this trigger for links to PDFs and SVGs, to give other examples of filetypes commonly both stored in GitHub repositories and linked in Slack.)

**Comment by r4v5** [comment]
Sure seems to still inline them as gibberish.

**Comment by bkeepers** [comment]
Thanks for reporting the issue.

If someone wants to try fixing this, I think it it _Should Be Easy™_.

You'll want to update the [blob unfurl](https://github.com/integrations/slack/blob/master/lib/messages/blob.js) to check if the file is binary and avoid unfurling it if it is. Unfortunately the [contents API](https://developer.github.com/v3/repos/contents/#get-contents) doesn't return any meta data about what GitHub thinks the file is, so we'll have to do our own binary detection. [isbinaryfile](https://www.npmjs.com/package/isbinaryfile) looks like it would do the trick.

**Comment by gimenete** [comment]
Whoops, I've just seen that there was already a PR open to fix this. The implementation is almost identical #676 and #685

**Comment by doms** [comment]
@gimenete Sounds good! Just waiting from further feedback from @bkeepers !

**Comment by R-Campbell** [comment]
@gimenete I looks like because of how #676 was merged into master through #705 this issue didn't get closed out properly.

**Comment by gimenete** [comment]
@R-Campbell oh, thanks! I'll close it now then 😄
