### ISSUE TITLE
What are the ramifications of write access to pull requests?

### ISSUE THREAD

**Issue by jverkoey** [integrations/slack#604]
I'm interesting in enabling these new integrations for our Slack workspace, but am concerned about the requirement for write access to pull requests. Does this authorization enable the Slack app to make changes to pull request code?

**Comment by andymckay** [comment]
It cannot change the actual code, just things in the pull request. A full list of the permissions enabled is here: https://developer.github.com/v3/apps/permissions/#permission-on-pull-requests.
