### ISSUE TITLE
Slack loading stealing focus

### ISSUE THREAD

**Issue by pcvandamcb** [integrations/slack#619]
OS: MacOS 10.13.5
Slack: 3.2.0

Whenever I start Slack, it will steal focus for the loading animation, which is annoying and also pointless. It will steal focus again when the actual window is loaded.

Preferred outcome: Slack can be started without stealing focus. You can start Slack, open another program and Slack will continue to open in the background.

**Comment by wilhelmklopp** [comment]
👋This repo is specifically for the GitHub Slack integration, and it looks like you're reporting a bug for the Slack desktop application. I suggest you get in touch with Slack at feedback@slack.com :)
