### ISSUE TITLE
Add shortlink to issues/prs

### ISSUE THREAD

**Issue by SUPERCILEX** [integrations/slack#621]
For example, if I type `#442`, it'd be nice for that to pop up an issue/pr card. Or maybe I could type `/issue/442`. Whatever works so that we don't have to add the full GitHub url or be left link-less.

**Comment by wilhelmklopp** [comment]
@SUPERCILEX Heads up that this isn't something we can realistically implement unless Slack adds some sort of other API that lets us subscribe to whenever someone mentions something like "#442". 


If we wanted to implement this now we would have to ask for read permissions to all your Slack messages, which is not something that we want to do.

**Comment by pedrojuk** [comment]
How about leveraging off the existing feature to put a comment on an issue as one of the message editing functions? Similar UI, but the action would just be to put a shortened link to the issue in the text, showing #442 or whatever as link short text as in github itself.
