### ISSUE TITLE
Optional @here and @everyone tags

### ISSUE THREAD

**Issue by filipetedim** [integrations/slack#624]
I've tried giving it a search here and also on uncle Google but to no avail. If duplicate and I was bad at scavenging, please let me know and close it.

Is there a way to optionally trigger a notification with `@here` tag? On my current project we're on-boarding a lot of non-tech people who seem to miss the PR they are meant to take a look at, mostly because they fail to understand a bold font'ed channel is new content there.

Would love to have this option as to be sure everyone in the channel will get the notifications for newly created PRs.

**Comment by wilhelmklopp** [comment]
@filipetedim thanks for the feature request! 

This seems like quite a niche feature that I don't think would make it into the codebase, so I'm closing this issue. Of course, feel free to create a fork of this repository :)
