### ISSUE TITLE
Github Bot doesnt fair well with replies sent by email

### ISSUE THREAD

**Issue by Seluj78** [integrations/slack#629]
![image](https://user-images.githubusercontent.com/4641317/41920285-afe7a1f8-7960-11e8-8791-074171d15bc9.png)

![image](https://user-images.githubusercontent.com/4641317/41920318-c196adcc-7960-11e8-9897-2d7b5b908958.png)

**Comment by bkeepers** [comment]
Ooph, that's rough. I'm guessing this will just require some changes in
https://github.com/integrations/html-to-mrkdwn, but I'll investigate.

(replying via email to test this out myself)

**Comment by Seluj78** [comment]
Yes it is

**Comment by Seluj78** [comment]
Yeah it still is, see https://github.com/integrations/html-to-mrkdwn/pull/23 on what to do next
