### ISSUE TITLE
Add custom icons for notification type

### ISSUE THREAD

**Issue by maya** [integrations/slack#631]
I'd like to be able to quickly understand the notification type at a glance. Adding some helpful icons will go a long way in making the notifications clear and recognizable.

On the legacy GitHub Slack integration, I was able to add custom icons for each notification type. I did this by adding in a custom integration for each notification and changing the default icon. 

Is this still possible with the new integration?  Thanks! 

<img width="622" alt="screen shot 2018-06-28 at 4 54 48 pm" src="https://user-images.githubusercontent.com/5249443/42066169-1205fa12-7af4-11e8-90e2-56e47dfecdef.png">

## Updated
The icons used in GitHub projects are nice too ([Octicons](https://styleguide.github.com/primer/components/octicons/)). I'd be happy if it defaulted to those. You could even add it inside the content if you don't want to change the default icon.
![issue example](https://user-images.githubusercontent.com/5249443/42067343-9aa95674-7afa-11e8-97a3-75bc125e1098.jpg)

Alternate example:
![github](https://user-images.githubusercontent.com/5249443/42105147-27679470-7b84-11e8-9ae5-af1ce7246ad2.jpg)

**Comment by wilhelmklopp** [comment]
@maya thanks for the feature request!

I don't think we have the option for setting different icons for each message we post. I believe this used to be possible with Slack apps but it no longer possible with the "workspace app" model that this integration is a part of.

With respect to octicons, I really love that idea! We can do that once Slack provides a way for apps to add their own emoji sets to workspaces and then we'd be able to use octicons as emojis.

**Comment by farski** [comment]
@wilhelmklopp I believe I've worked on some Slack apps using the new workspace tokens, and they're handling of the `icon_emoji` property of messages was the same as the old way. I don't really ever use the `icon_url` property, so I can't speak to that, which is likely what would be needed for something like this. Also I could be misremembering.

**Comment by mediavrog** [comment]
Any update on how to achieve the custom look/icons?

**Comment by farski** [comment]
As an edit/update to my [previous comment](https://github.com/integrations/slack/issues/631#issuecomment-408675136), workspace tokens never came out of preview, and I believe I was mistaken about them supporting the `icon_emoji` property anyway. Only the old, deprecated, ad hoc Incoming Webhooks (those not associated with an app) allowed for this.

The current way to handle this would probably be with a [context element](https://api.slack.com/reference/messaging/blocks#context) from the Block Kit system, which does allow for a small image icon to be set.
