### ISSUE TITLE
Notifications about new commits in pull requests

### ISSUE THREAD

**Issue by vlad-timofeev** [integrations/slack#635]
Is it possible to get notifications about new changes made in the existing PRs?

**Comment by yuri-sakharov** [comment]
I think you need to subscribe to `/github subscribe owner/repo pulls comments`

**Comment by vlad-timofeev** [comment]
@yuri-sakharov 
thanks for your suggestion
both of these notification types are turned on
but it seems like notifications about new commits in the existing PRs are not included

**Comment by wilhelmklopp** [comment]
There's no option to subscribe just to new commits in existing PRs but you _can_ subscribe to all new commits with `/github subscribe owner/repo commits:all`

**Comment by vlad-timofeev** [comment]
@wilhelmklopp 
does `all new commits` here is supposed to include `new commits in existing PRs`?
currently the `commits:all` subscription is on, but only direct commits to the owner's repo trigger notifications, no notifications for commits to the existing PRs

**Comment by wilhelmklopp** [comment]
@vlad-timofeev that's correct. All new commits including commits to branches for which a PR is open.

If you're not seeing those that sounds quite odd. Could you share an example with screenshots and so on of what you're seeing?

**Comment by vlad-timofeev** [comment]
@wilhelmklopp 
This is the current output for `subscribe` command
![image](https://user-images.githubusercontent.com/11474041/43393610-f5e3b99a-9421-11e8-9b31-e5ce8d1ef368.png)
As a result we see all of the notifications we need with one exception:
when someone pushes new commits to their fork of the main repository to the branch that corresponds to some existing PR - there's no notification at all

**Comment by vlad-timofeev** [comment]
Maybe the reason is that that this commits happen not in the main repo but in the fork?
We expect to get notifications for this scenarios too though. It means that the existing PR was updates, and it might be as important as that it was created (the case for which notifications work fine)

**Comment by wilhelmklopp** [comment]
> Maybe the reason is that that these commits happen not in the main repo but in the fork?

Ah! Yep, that would be the reason. If you would like to see commits for forks you would have to subscribe to the fork separately. 

The GitHub + Slack integration wouldn't receive the "push" webhook event if the [GitHub App](https://github.com/apps/slack) is not installed on the fork repository as well 😄.

**Comment by vlad-timofeev** [comment]
@wilhelmklopp 
Okay, thank you for making things clear!
