### ISSUE TITLE
Subscribing to commits also subscribes to pulls

### ISSUE THREAD

**Issue by bendavies** [integrations/slack#636]
We have 2 separate channels I'm trying to subscribe different events to
1. Commits channel: `/github subscribe org/repo commits:all`
2. PR channel: `/github subscribe org/repo pulls`

now, pushing a commit will correctly post a notification only to the commits channel, but opening a PR will trigger a `Pull request opened` notification trigger in both channels, where as i would expect it to only post to the PR channel.

Am i misunderstanding the notifications or is this a bug?

Thanks!

**Comment by bendavies** [comment]
it seems to me that first `subscribe` you do subscribes to everything, regardless of which features you specify. i fixed this by unsubscribing from the features i didn't want after the first subscribe.

**Comment by wilhelmklopp** [comment]
Yep exactly -- this is intended behaviour at the moment 😃
