### ISSUE TITLE
Support GitHub Enterprise (self-hosted) and Slack Enterprise Grid

### ISSUE THREAD

**Issue by seangates** [integrations/slack#643]
Per the README:

>This app officially supports GitHub.com and Slack.com but the team plans to support GitHub Enterprise and Slack Enterprise Grid in the future.

I'm posting this issue in order to request the feature. As I support a very large Slack Enterprise Grid instance (one of the first), I would very much like to utilize the new features herein.

Thanks for the great stuff so far! Looking forward to how this shakes out.

**Comment by bkeepers** [comment]
Thanks @seangates.

We're tracking this in #565. We're not actively working on it but feel free to subscribe to that issue for updates.

**Comment by seangates** [comment]
Ah ... I searched and couldn't find one. Thanks!

**Comment by davidcelis** [comment]
The linked issue appears to be centered around GitHub Enterprise, but it looks like @seangates may have been talking about Slack Enterprise Grid specifically?

HashiCorp recently moved to a Slack Enterprise Grid and we were surprised when the GitHub integration broke. We still use github.com.

**Comment by seangates** [comment]
@davidcelis Neither regular Slack nor Slack Enterprise Grid work with the integration when using GitHub Enterprise. My title might have been misleading.

**Comment by erikr** [comment]
I am surprised this integration does not yet support Slack Enterprise Grid. Would be great to have that.
