### ISSUE TITLE
GitHub slack bot not showing subscribe list

### ISSUE THREAD

**Issue by pintodossantos** [integrations/slack#646]
Recently our GitHub bot in slack is not able to show the subscribed repositories.
`/github subscribe list` produces the following message:
>Sorry, we had trouble with your request! If this is interfering with your work, please get in touch!
Unfortunately there is no additional information available. How can I try to debug this? Your help would be much appreciated.

Thank you!

**Comment by bkeepers** [comment]
@pintodossantos thanks for the report. Could you click the `get in touch` link in the error message and contact our support team? That way we have a link to the exact error you're running into and can trace it back to the root cause.
