### ISSUE TITLE
"Show rich preview?” prompt is sent to the main channel even if GitHub link was posted in a thread

### ISSUE THREAD

**Issue by PranayAgarwal** [integrations/slack#653]

**Comment by wilhelmklopp** [comment]
@PranayAgarwal I just tried to take a look at this, but to me it looks like there are two problems:
- You cannot use `chat.postEphemeral` in a thread
- There is no information present in the `link_shared` event about whether the link was shared inside a thread

Please correct me if I'm wrong 😄 -- would love to fix this bug!

**Comment by PranayAgarwal** [comment]
Hmm.. thanks, I'll take a look at what we can do on our end

**Comment by PranayAgarwal** [comment]
Hi @wilhelmklopp, you should be unblocked on both of these now
