### ISSUE TITLE
Clarifications on how the integration works on 3rd-party repos

### ISSUE THREAD

**Issue by AkA84** [integrations/slack#658]
I am a bit confused by how this integration is supposed to work with 3rd-party repos (= repos neither I or my organization own), so I hope to get some clarifications here!

As far as I understood it, I can subscribe (`/github subscribe <user>/<repo>`) to _any_ repo, as long as the owner/organization that owns that repo has the [Slack](https://slack.github.com/) app installed, is that correct?

For example, i took an educated guess and i tried `/github subscribe github/opensource.guide` and it worked. Then i tried `/github subscribe lodash/lodash` and it didn't, replying

> Either the app isn't installed on your repository or the repository does not exist. Install it to proceed.

does that mean that if I wanted to get notifications from that repo, I should ping the lodash's owner and ask him to install the Slack app?

Another thing I'm not sure I understood is the permissions for github actions like opening/closing an issue, or closing a PR.

Am I supposed to be able to open/close an issue and close/reopen a pull request on _any_ repo I'm subscribed to, even if I don't own them, as long as the owner has accepted the "Read and write access to issues and pull requests" permission?

I tried to open an issue on a repo that I didn't own once and It worked, but then on subsequent tries i would simply get this error

<img width="400" alt="issue-error" src="https://user-images.githubusercontent.com/6400898/44140668-0c1518a2-a07b-11e8-8394-ffb865f988fc.png">

or i would get this

> Sorry, we had trouble with your request! If this is interfering with your work, please get in touch!

when trying to close/reopen a PR. So I don't know if this is the integration having an hiccup or not allowing me to do any of those actions because I'm not the owner (although i _did_ manage to open an issue once)

Thanks!

**Comment by AkA84** [comment]
thanks @wilhelmklopp for the quick response!

I think I then figured out the reasons for this generic error message:
1. When I got "Sorry, we had trouble with your request!", it was because I didn't open the PR i was trying to close
2. When I got "We had trouble connecting", it was apparently because that particular repo wasn't in the whitelist that the github user (who owned that repo) set up for the slack app

Overall your reply clarifies my doubts, much appreciated! The error handling though I think could be a bit improved so that it doesn't leave people guessing what happened

Thanks again!

**Comment by wilhelmklopp** [comment]
> When I got "We had trouble connecting", it was apparently because that particular repo wasn't in the whitelist that the github user (who owned that repo) set up for the slack app

Ah gotcha! Yeah repo/org owners have the option to install the app either on all repos or only some repos.

> The error handling though I think could be a bit improved so that it doesn't leave people guessing what happened

Agreed! Would you mind opening a separate issue for improvements to error handling on this repo?

**Comment by AkA84** [comment]
@wilhelmklopp 
> Agreed! Would you mind opening a separate issue for improvements to error handling on this repo?

Yep, there you go! https://github.com/integrations/slack/issues/659

**Comment by AkA84** [comment]
@wilhelmklopp one last thing: what if for whatever reason the owner/organization of the repo i need notifications from don't have the Slack app and can't/doesn't want to install it? Is there some other way to get notifications in that case?

**Comment by wilhelmklopp** [comment]
@AkA84 unfortunately, there is not at the moment. The app needs to be installed on the repo you're subscribing to :/
This is due to the architecture of GitHub Apps. The integration only receives webhooks for repositories that it is installed on

**Comment by AkA84** [comment]
got it, thanks you very much again @wilhelmklopp !
