### ISSUE TITLE
Showing the deployment cycle

### ISSUE THREAD

**Issue by sayduck-daniel** [integrations/slack#662]
In my deployment workflow I'm using currently Github, Slack and Herku. It seems to me that something is off and I can't for sure figure out if it is from the updates on this integration.

I always had this workflow:
1. Edit my app
1. Push changes to Github
    - then a message appears on slack "1 new commit pushed to master" in black
1. Heroku (linked to GitHub) detects the change
    - then a message appears on slack saying "building the app"
1. Heroku builds the app (and notifies Github)
1. Heroku deploys the app
    - then a message appears on slack saying "successful deploy"
1. ... or fails to deploy
    - then a message appears on slack saying "failed deploy"

It seems to me that this integration somehow during its development lost the `pending notification` at first and now it seems to not display the `failed deploy`.

Any idea how to add it again?

**Comment by wilhelmklopp** [comment]
@sayduck-daniel 👋 

I'm not sure I fully understand your question. Are you saying that "pending" and "failed" deployment status events no longer show up in Slack for you?

**Comment by sayduck-daniel** [comment]
Exactly.

**Comment by wilhelmklopp** [comment]
@sayduck-daniel I just double checked, and those deployment statuses are definitely still showing up for us:
![image](https://user-images.githubusercontent.com/7718702/44464165-f59a8700-a611-11e8-93fc-2e03a2fb4a25.png)
I created this one just now (also uses Heroku)

Is it possible that something else in your setup changed?

**Comment by sayduck-daniel** [comment]
I think I figure out one of the problems here. We just added Heroku CI to our pipeline. 

Apparently, if the CI fails, Heroku does not attempt to deploy, therefore nothing is shown.

I check on our repo and it seems GitHub receives events when it starts testing and once is done (success and failure):



1) Would it be possible to implement “Testing … on staging” perhaps?

I just tried to deploy with passing tests and I can confirm it does not show the orange state, it only shows this at the end:


This screenshot demonstrates heroic deploying and the message not there.


Any idea where it could come from?

**Comment by sayduck-daniel** [comment]
I think I figure out one of the problems here. We just added Heroku CI to our pipeline. 

Apparently, if the CI fails, Heroku does not attempt to deploy, therefore nothing is shown.

I check on our repo and it seems GitHub receives events when it starts testing and once is done (success and failure):
<img width="320" alt="screen shot 2018-08-22 at 5 02 08 pm" src="https://user-images.githubusercontent.com/38907720/44468340-a7937c80-a62d-11e8-9290-ec05b4cc9b37.png">

1) Would it be possible to implement “Testing … on staging” perhaps?

I just tried to deploy with passing tests and I can confirm it does not show the orange state, it only shows this at the end:
<img width="438" alt="screen shot 2018-08-22 at 5 03 23 pm" src="https://user-images.githubusercontent.com/38907720/44468351-acf0c700-a62d-11e8-8d19-efd1727d1f0d.png">

This screenshot demonstrates heroic deploying and the message not there.
<img width="473" alt="screen shot 2018-08-22 at 5 01 25 pm" src="https://user-images.githubusercontent.com/38907720/44468364-b5490200-a62d-11e8-855c-fe144d9dc71e.png">

Any idea where it could come from?

**Comment by wilhelmklopp** [comment]
@sayduck-daniel Heroku creates those deployment status events via the GitHub API. This integration just forwards them to Slack. But it sounds like Heroku may not create those deployment status events if you use Heroku CI?

It might be a good idea to double check with Heroku as it seems like the bug you're seeing is on their side?
