### ISSUE TITLE
Ability to display PR description in slack notification for merged PRs

### ISSUE THREAD

**Issue by shwin** [integrations/slack#663]
Currently, the merged PR notification looks like:
<img width="822" alt="screen shot 2018-08-22 at 10 37 22 am" src="https://user-images.githubusercontent.com/1700973/44480852-2de19b80-a5f9-11e8-8926-f4cfdde1855d.png">

What we'd really love, is if it displayed the PR description (like it does when a PR is opened, eg: <img width="806" alt="screen shot 2018-08-22 at 10 41 04 am" src="https://user-images.githubusercontent.com/1700973/44480857-30dc8c00-a5f9-11e8-84f0-6db5dbababe9.png">)

Would that be possible? If it already is, please let me know, and I'll happily close this out!

**Comment by jake-lester** [comment]
Hey! Was this ever implemented? (sorry for resurrecting 🧟‍♂️)
