### ISSUE TITLE
Change to the new GitHub App Installation Access Token route

### ISSUE THREAD

**Issue by andymckay** [integrations/slack#671]
In order to support the change of the app installation token route:

https://developer.github.com/changes/2018-08-16-renaming-and-deprecation-of-github-app-installation-access-token-route/

We'll need to update octokit, then update slack and deploy that.

**Comment by andymckay** [comment]
@wilhelmklopp would you be able to get this in the pipeline, so we can deprecate then end point please?

**Comment by wilhelmklopp** [comment]
This is currently blocked by performance issues with Probot 7

https://github.com/integrations/slack/pull/605/
https://probot-talk.slack.com/archives/G82AMJYC9/p1536239538000100

**Comment by wilhelmklopp** [comment]
We're on Probot 7 and have been for a while!
