### ISSUE TITLE
Allow image attachments when creating an issue

### ISSUE THREAD

**Issue by oweskeez** [integrations/slack#673]
This would be a super helpful feature for front end bug reporting especially. Also if the image attachments could be pasted in from clipboard (exactly how slack does it) that would be epic. See snip below:

![image](https://user-images.githubusercontent.com/3844029/45047477-1ff33800-b047-11e8-87a2-36bcda14d7fe.png)

**Comment by gimenete** [comment]
Thank you @oweskeez for your suggestion. I agree with you that this would be great to have. However we are limited by Slack in this case. Checking the [documentation](https://api.slack.com/dialogs) they only support textfields, textareas and selects/dropdowns. There's nothing about file uploads or allowing us to interact with the pasteboard, drag and drop, etc.

My only suggestion is to use some app that allows you to upload files quickly to the cloud and provide you a link that you can put in the issue body. Absolutely not ideal, but that's my only suggestion at this moment.

**Comment by yashvesikar** [comment]
is this possible now? i see that slack support file uploads @gimenete do you know is Slack supports this use case in 2022?

I tried poking around the api docs but was not sure where exactly to look.
