### ISSUE TITLE
Can't subscribe to only one feature

### ISSUE THREAD

**Issue by matkoch** [integrations/slack#680]
When typing `/github subscribe xxx/yyy releases`, this won't only subscribe to releases, but to all features.

**Comment by wilhelmklopp** [comment]
👋 @matkoch By default that syntax subscribes to all features + releases.

To be only subscribed to releases you can now do this for your existing subscription:

`/github unsubscribe xxx/yyy issues,pulls,deployments,statuses,public,commits`

**Comment by matkoch** [comment]
this is unintuitive.

**Comment by wilhelmklopp** [comment]
Thanks for the feedback! ✨ 

Let me clarify further:
`/github subscribe xxx/yyy` subscribes to all features
`/github subscribe xxx/yyy releases` subscribes to all features and also to releases

**Comment by matkoch** [comment]
It already is clear to me how it works. What I'm trying to say is that it's not natural.

**Comment by wilhelmklopp** [comment]
Awesome! Yeah, I agree with that. If you wanted to contribute this functionality, i.e. that `/github subscribe xxx/yyy releases` subscribes _only_ to releases, we would welcome that contribution.
