### ISSUE TITLE
Rich preview for private repos doesn't work

### ISSUE THREAD

**Issue by valignatev** [integrations/slack#687]
Hi! For some reason, GitHub app doesn't expand previews for private repos link while public repos work fine.
From the readme, it seems that I should do `/GitHub signin` which I've done, and the app shows me that my slack user connected with my GitHub account.
Also, I have access to the private repo, and I am a member of an organization which owns the repo.

What step did I miss? Maybe, an organization owner should install the app to the repo and sign in within the Slack? From the readme, it doesn't look like that.

**Comment by valignatev** [comment]
Sure, double checked:

link previews for github.com have been disabled for your workspace - `not disabled, OSS links work`
the same link was already shared in the last 30 minutes in the same channel - `nope, it wasn't`
3 or more links are shared in the same chat message - `nope, tested with only one link`
The repository is private and the user that shared the link:
    has not signed in to their GitHub account - `signed in (proof below, I resigned again just in case)`
    asked not to show a preview when prompted - `there was no prompt`
    the GitHub app is not in the channel, which you can remedy with /invite @github - `invited, proof below`

![image](https://user-images.githubusercontent.com/7038954/46383004-c2d6ba80-c6b6-11e8-821b-992711cbf919.png)
![image](https://user-images.githubusercontent.com/7038954/46383026-e3067980-c6b6-11e8-80c8-8e38a04a2f1b.png)

Is there anything else I can try/check?

**Comment by valignatev** [comment]
Ok, it seems that besides all the things mentioned in the readme, there's also some kind of an approval needed from the repo owner. After this approval, all started to work. I think it worths to update the readme then

**Comment by mcaballeropinto** [comment]
@valignatev can you share how to do that approval you mentioned? I am having exactly the same issue. 😕

**Comment by valignatev** [comment]
Hey @mcaballeropinto, organization/repo owner should be pinged by the integration for approval, and the owner should confirm. Just having push access to the repo is not enough.

**Comment by mcaballeropinto** [comment]
We don't recall any notification about this specifically. We will dig in the settings to see if there is something being turned off.

The weird thing is that it was working until 2 weeks ago, then it just stopped showing previes for private repos anymore.

**Comment by davidcelis** [comment]
We're being affected by this over at @hashicorp as well, though I think that rich previews very suddenly stopped working when we switched to Slack Enterprise Grids.

@valignatev where does that ping for integration approval actually happen? Is that a ping in Slack, or somewhere on GitHub?

**Comment by valignatev** [comment]
@davidcelis Should be on github if I got it correctly. I personally haven't received it, the owner of the repo I'm working on got it, so I don't know where exactly this ping should happen.

**Comment by davidcelis** [comment]
@valignatev Thanks. I thought that might be the case, so I found the authorization page for the "Slack" GitHub App and asked our organization admins to re-authorize it against every repository. They claim to have done that but rich previews still don't work, unfortunately 😞

**Comment by mcaballeropinto** [comment]
For me it started working again when the organization admin logged out and in again of GitHub **in Slack**. Did you tried that?

**Comment by davidcelis** [comment]
Unfortunately that didn't work either (I had someone who is both a Slack admin and an owner of our GitHub org do a `/github signout` and `/github signin` in slack)

**Comment by davidcelis** [comment]
I opened a new issue after realizing that we can't even show rich previews/unfurls for _public_ issues or PRs. Seems like a different problem.

**Comment by kesor** [comment]
It is also worth to check if github.com has not been blacklisted on Slack for previews.
Looks like this - 
![image](https://user-images.githubusercontent.com/7056/56862240-74ba3900-69b1-11e9-828f-d787656723d6.png)

**Comment by michaelstanton** [comment]
Try this slash command `/github subscribe org/repo`. It should take you to a page on GitHub where you can pick the organization or repo that you want to authorize.

Private repo unfurls were not working for me until I did that.

**Comment by valignatev** [comment]
I had it working a long time ago, so closing it. I think other people can create a new issue if a similar thing happens to them

**Comment by youtux** [comment]
Still relevant after 2 years. I had to follow https://github.com/integrations/slack/issues/687#issuecomment-498047919 to make it work (brand new slack channel, brand new github repo)
