### ISSUE TITLE
Provide a deployments API in slack

### ISSUE THREAD

**Issue by andymckay** [integrations/slack#688]
It would be nice to provide a deployments API in slack such that a command such as `/github deploy` would trigger the API.

https://developer.github.com/v3/repos/deployments/

Todo:
* add in a bit more information about exactly which of the APIs we want to call
* we should listen to the webhooks to inform slack about the status of deployments

**Comment by bkeepers** [comment]
> we should listen to the webhooks to inform slack about the status of deployments

Deployment status is already implemented, so it should just be a matter of triggering the deployment:  https://github.com/integrations/slack/blob/master/lib/activity/index.js#L39

**Comment by judoole** [comment]
Does this mean that `/github deploy` should start working now?

**Comment by gimenete** [comment]
@judoole this is in the codebase but not enabled yet. We need to ask to upgrade permissions of the app in order to enable it so we are waiting to do the proper communication on why we need upgraded permissions, etc.

**Comment by judoole** [comment]
Thanks for a quick answer and good work @gimenete!

**Comment by wushujames** [comment]
@gimenete , do you have an estimate for when /deploy will be enabled? It sounds like a really useful feature.

**Comment by assimovt** [comment]
@wushujames In the meantime, check out https://getslashdeploy.com It already provides `/deploy` with a bunch of other useful [commands](https://docs.getslashdeploy.com/commands) and it's built on top of GitHub deployment API - so works out of the box. I've built it to specifically uplift GH deployment workflows.

**Comment by torbjornvatn** [comment]
@gimenete any news on when the deploy functionality will be enabled?

**Comment by gimenete** [comment]
@torbjornvatn we are waiting on some changes that the team in charge of app permissions is going to do to, in order to make the permissions upgrade smoother. Sorry for the inconvenience.

**Comment by torbjornvatn** [comment]
@gimenete did you make any progress on this?

**Comment by torbjornvatn** [comment]
I get this when I try `/github deploy owner/repo list`

![Screen Shot 2019-05-03 at 16 38 54](https://user-images.githubusercontent.com/4453/57144722-f818c780-6dc1-11e9-9f16-cb58e9e593f4.png)
