### ISSUE TITLE
Feature request: Send pull request review messages to DM

### ISSUE THREAD

**Issue by flybd5** [integrations/slack#694]
In the current integration it is possible to subscribe to a repo and get all kinds of messages related to it, including messages about pull request reviews. 

However, developers may decide to ignore this being sent to a channel because it may become information overload, and they may not be interested in sorting through the chaff to find the nuggets. In our case, developers are also ignoring emails. They will, however, pay attention to DM's if they are directly related to them.

This request is to add a feature that will allow a developer to subscribe to a repo so that pull request reviews that include them as requested reviewers are DM'd directly to them.

Suggested format of the subscribe command might be:

`/github subscribe-dm owner/repo reviews

This should then trigger DM's associated with the pull request reviews when the user is included in the request to review.

**Comment by pbatorre** [comment]
@flybd5 I made an app that works as you mentioned - where review requests and reviews are sent as a DM to the reviewer and assignee respectively. The idea is to limit notifications to the person who can directly move the state of the pull request forward. Message me through https://divvycodereviews.com if you have questions.

**Comment by the-double** [comment]
@flybd5 I appreciate the response. One thing that might be helpful to mention is each membership is on an opt-in basis: members in your GitHub organization or Slack workspace will not automatically count into the subscription unless they explicitly link their accounts. For example, a GitHub organization with 10 developers and 2 managers would likely only have the developers subscribe into the service.

If you think the app could be valuable to the team and would like to see if we can work something out, email me at support@divvycodereviews.com :)

**Comment by pbatorre** [comment]
@flybd5 I appreciate the response. One thing that might be helpful to mention is each membership is on an opt-in basis: members in your GitHub organization or Slack workspace will not automatically count into the subscription unless they explicitly link their accounts. For example, a GitHub organization with 10 developers and 2 managers would likely only have the developers subscribe into the service.

If you think the app could be valuable to the team and would like to see if we can work something out, email me at support@divvycodereviews.com :)

**Comment by dalen** [comment]
https://pullreminders.com/ is also doing basically this. But I agree it would be nice to just have it built in to the regular integration.
