### ISSUE TITLE
Trello icon not being rendered in Slack comment; renders correctly in GitHub pull request comment

### ISSUE THREAD

**Issue by arielkirkwood** [integrations/slack#704]
Hi folks! Hoping to figure out if this is a GitHub issue, a Trello issue, a Slack issue, or some combination of the three.

I'm using the [GitHub Power-Up for Trello](https://trello.com/power-ups/55a5d916446f517774210004/github) to reference pull requests within Trello cards and simultaneously post a comment on the pull request with a link to the Trello card. I'm noticing that the comment includes a small image of the Trello logo, and it looks nice rendered on GitHub.com:
<img width="784" alt="screen shot 2018-09-30 at 10 39 52 pm" src="https://user-images.githubusercontent.com/414839/46267373-806c7c80-c502-11e8-9c44-0fa17ab3b565.png">

When this pull request comment is shared in a Slack channel via this integration, it looks like the Trello logo is included as an attachment, and the text of the image's URL is included in the body of the comment instead:
<img width="641" alt="screen shot 2018-09-30 at 10 40 08 pm" src="https://user-images.githubusercontent.com/414839/46267394-a8f47680-c502-11e8-9765-a6bb8d4e52a6.png">

What I suppose I would've expected was the Trello image being rendered inline with the comment, but I also suppose seeing that it's an attachment makes sense for other use cases.

Thanks in advance for your attention to this!

**Comment by gimenete** [comment]
Hi @arielkirkwood 

I don't think we can render the icon to the left of the text, like in the GitHub comment. But I think we can improve the formatting by removing that long URL. Can you provide the source of the github comment by clicking on "edit" and copying and pasting it here so I can see it and try to improve the parsing?

<img width="171" alt="screen shot 2018-10-01 at 11 00 57" src="https://user-images.githubusercontent.com/50486/46279439-6023d880-c569-11e8-8e6a-5cceec4ec3bf.png">

Thanks!

**Comment by arielkirkwood** [comment]
@gimenete Thanks for the reply! Here's the source of an example comment:
```markdown
![](https://github.trello.services/images/mini-trello-icon.png) [(8) Q3 Mx Engagement Email Test](https://trello.com/c/zCdIpjVt/2668-8-q3-mx-engagement-email-test)
```

**Comment by arielkirkwood** [comment]
It’s not relevant for me any more, my organization has moved to Clubhouse.
