### ISSUE TITLE
No notifications for pushed tags

### ISSUE THREAD

**Issue by shanemcd** [integrations/slack#707]
Is this the intended behavior? I see messages when I delete a tag, but not when I push.

**Comment by allendewilzin** [comment]
@shanemcd make sure the releases feature is added to the repo subscribition as a feature
```
/github subscribe owner/repo releases
```
To watch all releases
```
/github subscribe owner releases
```

If i have this wrong can you maybe share a screenshot?

**Comment by shanemcd** [comment]
Fantastic. Thank you!

**Comment by tdmalone** [comment]
Releases aren't the same as tags - and `releases` doesn't seem to activate alerts for tags either. We're experiencing the same problem - notifications are sent for deleted tags, but not newly pushed tags (and `releases` is turned on).

This is probably covered by https://github.com/integrations/slack/issues/1445 now, though.
