### ISSUE TITLE
Can't access organization private repo

### ISSUE THREAD

**Issue by Seanmatthews** [integrations/slack#710]
I'm a GitHub organization owner. The slack app authorized my user and sign me in. However, I get this message whenever trying to subscribe to a repo/issue/etc:

`Note: You need to be an organization owner to install the app (or ask one to install it for you).`

I can't find anything in the installation instructions for authorizing access to an organization.

**Comment by theundebruijn** [comment]
Hi @Seanmatthews, I'm running into the exact same issue. Did you find a way to resolve it?

**Comment by Seanmatthews** [comment]
Nope!

**Comment by allendewilzin** [comment]
@Seanmatthews 
Might need to be an slack owner or workspace admin try that maybe.

**Comment by vmandic** [comment]
I am able to sign in with my account (and I am also my orgs owner) but, after multiple subscribes with `/github subscribe myOrg/myOrgRepo` I still do not get any notifications from github to slack. I observed that `/github settings` tells me I have no settings configured... all in all my org can not connect to slack.

**Comment by doganarif** [comment]
Interesting. It is interesting that this feature that is so important for the company level.
