### ISSUE TITLE
slack integration thinks "https://github.com/apps/wip-beta" is a private repository

### ISSUE THREAD

**Issue by gr2m** [integrations/slack#715]
![image](https://user-images.githubusercontent.com/39992/46911669-ecde7700-cf17-11e8-919a-0ba708e1b912.png)

**Comment by wilhelmklopp** [comment]
This PR should address that: https://github.com/integrations/slack/pull/623 I've been meaning to add some tests to that so that we can get it merged

**Comment by gimenete** [comment]
is this the same issue? https://github.com/integrations/slack/issues/690
