### ISSUE TITLE
[Feature Request] New repository created notification

### ISSUE THREAD

**Issue by JsseL** [integrations/slack#728]
**Shortly**
Now that #709 introduced the ability to subscribe to whole organization, it would be really nice if you could subscribe to repository events e.g. "New repository created".

**Use case example:**
In a large organization, it would be nice to keep people up to track on new repositories created. Having something like `/github subscribe <org_name> repositories` would allow us to have a channel that would have such information "in real time".

Anyways, thanks for the great tool! Already does lots of cool things. 💯 👍

**Comment by joshbranham** [comment]
ping
