### ISSUE TITLE
Feature request: auto subscribe to new repos created

### ISSUE THREAD

**Issue by miguelmota** [integrations/slack#739]
Currently when someone creates a repo on github they must run the command `/github subscribe myorg/myrepo` in slack in order to start getting notifications for that repo. I'd be useful if there was a command to auto subscribe to all new repos created as well as get a notification when a new repo is created

**Comment by gimenete** [comment]
@miguelmota you can subscribe to an entire org by using `/github subscribe myorg`. This will subscribe you automatically to events in new repos.

**Comment by miguelmota** [comment]
@gimenete good to know 👍
