### ISSUE TITLE
[Feature request] Subscribe to all repositories matching criteria

### ISSUE THREAD

**Issue by galenskap** [integrations/slack#749]
The GitHub integration of our organization's repositories is divided in separate slack channels. All notifications from repositories having a label "something" or prefixed by "smthg-*" go into channel #about-smthg, and so on.

Right now this is done by hand, but maybe a filter-based subscription would be a conceivable improvment?

I am thinking about
`/github subscribe Our-organization/smthg-*`
or
`/github subscribe Our-organization label:[smthg]`

Related to : 
- #384 : subscribe to one repo but notify only about issues/PR having a specific label
- #557 : mass subscribing (one line, multiple repo)

**Comment by alkanalkn63** [comment]
True

**Comment by ghirsch1** [comment]
Yes, this would still be really helpful

**Comment by Eduardoveras** [comment]
Our org has 1.2k repos, and it would be great to be able to track labels across all repos, something like 
`/github subscribe Our-organization label:[smthg]`
should be work, but it currently does not
