### ISSUE TITLE
Documentation for creating deployments

### ISSUE THREAD

**Issue by jgreat** [integrations/slack#752]
Looks like support for creating a deployment may have been added in #698, but there is no documentation on how to use it.

**Comment by IAmHughes** [comment]
Hey @jgreat, just wanted to let you know that the `/github deploy` feature is now live including documentation in the help output in Slack! You can read about the changes we shipped today [on the GitHub Blog](https://github.blog/2019-07-29-whats-new-in-the-github-and-slack-integration/). 

The key thing to note is that this required some updated permissions on the application, so the owner of any repositories that have the GitHub Slack App installed will need to accept those permissions. If you try to use the command without the permissions, you'll be prompted to update them ❤️.

Thanks for your patience on this!
