### ISSUE TITLE
Add support for the in_progress and queued deployment statuses

### ISSUE THREAD

**Issue by kberzinch** [integrations/slack#756]
There is currently an [API preview](https://developer.github.com/v3/previews/#deployment-statuses) that provides for additional deployment statuses. As of this writing, the Slack integration does not properly render at least the `in_progress` state and most likely neither the `queued` state based on my skimming of the source.

**Comment by wilhelmklopp** [comment]
I believe this shipped as part of https://github.com/integrations/slack/pull/771 🎉
