### ISSUE TITLE
Unable to unlick slack user from github account

### ISSUE THREAD

**Issue by alwyn** [integrations/slack#757]
Out of confusion about what account should be linked with on the github side (Still confused), I picked a generic user to link the app with.

It is impossible to unlink that relationship.  You can uninstall the app and go crazy, when you install again and try to subscribe, the link for connecting to github will by default use a token for the original github account used.

So:
1) How can we remove this slack user -> github account relationship so it can be changed?
2) Is there a single github account relationship for all subscriptions, or is it on a per slack user basis?

**Comment by NathanZook** [comment]
https://github.com/settings/apps/authorizations @alwyn
