### ISSUE TITLE
Users without github account (linked to slack) can't create issues on private repo

### ISSUE THREAD

**Issue by VesterDe** [integrations/slack#760]
I'm not sure if this is expected behaviour, I wasn't able to find documentation about it, or similar issues.

I have a private repo, and want the team (not all developers, not all with github accounts) to be able to open issues in a bug report channel via the github integration. It works for me and the other devs, but users without github accounts can't open them, and when they try github just says "Need help getting started?" and lists the possible commands.

Is there a quick fix for this? Like creating a generic user and having all of them link their slack account to it? Or have I stumbled upon an actual bug?

**Comment by tcbyrd** [comment]
The Slack integration doesn't inherently give users of Slack access to anything on GitHub. It maintains a mapping of Slack User <-> GitHub User so we can check if the Slack user has the appropriate permissions on GitHub. But even on public repos, GitHub still requires the user to at least have a GitHub account before they can open an issue, so the Slack integration can't really do anything to work around this.

The "need help getting started" is displayed to help a user go through the process of linking their GitHub account, so if they don't have an account there's really no way to use the github integration. I'm not sure if its possible for multiple Slack users to be linked to the same GitHub user. @wilhelmklopp or @gimenete might have better info on how that would be behave, but my guess is it can only be linked to one user at a time.

**Comment by VesterDe** [comment]
Alright, thank you for your answer!

I'll figure out a different mechanism.
