### ISSUE TITLE
IOS APP show additional APP TEXT aside username even using as_user=true and username

### ISSUE THREAD

**Issue by be-services** [integrations/slack#762]
It's  failing is just in IOS application because in Android app, web app using chrome and windows desktop the additional APP text aside the username doesn't appear

curl -X POST "https://slack.com/api/chat.postMessage" -d"token=XXXXXXXXXX&channel=XXXXXX&text=HELLO&as_user=true;username=XXXXX"

**One Unexpected Behavior**
IOS APP
![slackiosappbug](https://user-images.githubusercontent.com/46540009/50928081-eea5d100-1459-11e9-824e-a6027ec6255a.jpeg)

**Two Expected behaviors**
Windows Desktop
![windows](https://user-images.githubusercontent.com/46540009/50928306-9de2a800-145a-11e9-9deb-e52b3c601e8c.JPG)

Web Chrome
![webchrome](https://user-images.githubusercontent.com/46540009/50928332-b18e0e80-145a-11e9-814b-494660b7f864.JPG)

**Comment by gimenete** [comment]
This issue looks like a Slack issue, not an issue with the GitHub integration. Please contact API Slack support https://api.slack.com/support
