### ISSUE TITLE
How to subscribe organization only about new releases

### ISSUE THREAD

**Issue by sean-ahn** [integrations/slack#763]
I found an issue #709, which makes us subscribe entire organization activities.

However, it cannot subscribe about some specified activities, such as new releases.

I typed
```
/github subscribe {Organization Name} releases
```

I expected to be notified only new releases,
but all activities are notified in channel.

How to subscribe organization only about new releases?

**Comment by githubERIK** [comment]
Check the default settings that are true
https://github.com/integrations/slack/blob/master/lib/models/subscription.js#L20
```js
  const DefaultSettings = {
    issues: true,
    pulls: true,
    deployments: true,
    statuses: true,
    public: true,
    commits: true,
    releases: true,
    comments: false,
    branches: false,
    reviews: false,
  };
```

and use `/github unsubscribe {Organization Name} issues pulls deployments statuses` etc

**Comment by scepticulous** [comment]
Hi @sean-ahn,

as `@githubERIK` mentioned, some features are enabled by default. 
These are the most commonly used features so having those as default, supports the majority of cases.

You can list your active features with:
`/github subscribe list features`

You can disable features with
 `/github unsubscribe <org> <feature1> <feature1> ...` 

Quick example that only leaves releases active:

<img width="794" alt="Screenshot 2019-08-12 at 16 15 02" src="https://user-images.githubusercontent.com/3408791/62871788-6acc0400-bd1c-11e9-91ae-7c6605defd5e.png">

I hope this helps and feel free to close the issue if that answers your question :)

**Comment by sean-ahn** [comment]
@scepticulous thanks! it was helpful.

**Comment by filipesperandio** [comment]
I still think this is a bad UX to this date.
`/github subscribe [org|repo]` with no features already do that. If you pass in `/github subscribe [org|repo] releases` is because you only want `releases`. You shouldn't need to further unsubscribe the other features you don't want.

**Comment by JustMyGithub** [comment]
How does 

/github subscribe [org|repo] releases work?

Is there a shell on the website that I do not know about?

**Comment by guiyumin** [comment]
> Check the default settings that are true https://github.com/integrations/slack/blob/master/lib/models/subscription.js#L20
> 
> ```js
>   const DefaultSettings = {
>     issues: true,
>     pulls: true,
>     deployments: true,
>     statuses: true,
>     public: true,
>     commits: true,
>     releases: true,
>     comments: false,
>     branches: false,
>     reviews: false,
>   };
> ```
> 
> and use `/github unsubscribe {Organization Name} issues pulls deployments statuses` etc

great

you have to unsubscribe things you don't need
