### ISSUE TITLE
Is the feature "releases" send notifications for pushed tags?

### ISSUE THREAD

**Issue by artful88533** [integrations/slack#764]
Hello!
Can I send notifications only for new Releases and Tags?
I subscribe only feature "releases". 
When I create releases in Github Web, notifications send correct.
When I create and push tags from console, notifications don't send.

**Comment by samg** [comment]
I'd also like to be able to have the bot announce notifications of new git tags (without having to configure a github release for each tag)

**Comment by samg** [comment]
I looked into implementing this.  I'm not able to find any event in the webhook api for subscribing to new tags in a repo.  Has this functionality been dropped in the new webhook API?  It seems like this would be a pre-requisite for adding this feature to this slack bot integration.

**Comment by ikornienko** [comment]
According to the doc here https://developer.github.com/webhooks/:
> | `push` | Triggered on a push to a repository branch. Branch pushes and repository tag pushes also trigger webhook push events. This is the default event.
> -- | --
So it seems like subscribing webhook to a `push` event then filtering out non-tag pushes can solve it, though I have no idea if this "filtering out" can be done in the context of this Slack app.

**Comment by philnielsen** [comment]
This should still be open?

**Comment by louisrli** [comment]
+1 for this being an issue with tags not being marked as releases

**Comment by joaquimg** [comment]
Any plans for alerting when tags are created?

**Comment by omesser** [comment]
pinging maintainers - @ashokirla @snankani - please reopen / update

**Comment by leejinlee-kr** [comment]
I need too.

**Comment by ilyakonrad** [comment]
This would be very useful.

**Comment by jzeipelt** [comment]
Yes, please add this.

**Comment by wdlkmpx** [comment]
Github has failed us

**Comment by billybooth** [comment]
I would like the opposite, i.e., I want to subscribe to commits but exclude tags. A separate tags subscription would obviously cover our need as well.
