### ISSUE TITLE
[Feature request] Tagging PR owner on all messages

### ISSUE THREAD

**Issue by avantjustus** [integrations/slack#776]
Currently, when a user performs an action, their username will be included in the slack message, but it would be very helpful if the PR owner was always tagged in any actions related to it (statuses, commits, comments, reviews, etc) so that we can be properly alerted in slack.

**Comment by abinoda** [comment]
@avantjustus A quick way to achieve this is to add your GitHub username under "My keywords" in your Slack notification preferences:

<img width="731" alt="screen shot 2019-02-01 at 10 54 26 am" src="https://user-images.githubusercontent.com/50083/52140348-c8fe8880-260f-11e9-81c2-38af3a3b3eb2.png">

**Comment by avantjustus** [comment]
Thanks @abinoda I am aware of this and I do this already. The purpose of this feature request is so that  my username is tagged on all PRs that I own, so that I can get notified via these means
