### ISSUE TITLE
[Feature Request] Mention slack user with their Github username when accounts are linked

### ISSUE THREAD

**Issue by MaralKay** [integrations/slack#784]
We would love that when a Github username is mentioned in a channel (with the @GithubUsername), the corresponding Slack user gets a notification - in the case that the user has connected the accounts.
Our usecase is: a Jenkins instance sends notifications for builds in a Slack channel and we want to notify the commit author in Slack by mentioning them with their Github username.

Assuming users have connected their accounts:

<img width="628" alt="screenshot 2019-02-11 at 16 48 25" src="https://user-images.githubusercontent.com/15269097/52574913-92015180-2e1d-11e9-94a3-b6caadc34eab.png">

Be able to get a notification when mentioned like this, although my Slack username is still _Maral_:

<img width="556" alt="screenshot 2019-02-11 at 16 54 15" src="https://user-images.githubusercontent.com/15269097/52575242-21a70000-2e1e-11e9-936b-b0f75af999c7.png">

**Comment by say8425** [comment]
https://github.com/integrations/slack/issues/435#issuecomment-424857414
