### ISSUE TITLE
Show a gray line instead of green for new, draft PRs

### ISSUE THREAD

**Issue by JasonEtco** [integrations/slack#788]
Since [Draft PRs](https://twitter.com/github/status/1096093162345508864) were introduced, there's now a new distinction for PRs and their state. In GitHub, Draft PRs are denoted by a gray `Draft` label:

<img width="451" alt="image" src="https://user-images.githubusercontent.com/10660468/52825527-05f46180-308b-11e9-9c7e-23c7cf6fcbd0.png">

<img width="774" alt="image" src="https://user-images.githubusercontent.com/10660468/52825533-0bea4280-308b-11e9-8b2e-2c3b59f1c191.png">

However, the Slack integration makes it look like those PRs are regular new ones, with the green signifier for a new PR (regardless of draft or not draft).

I think this is useful for a few reasons - there's less urgency to look at draft PRs, and they're a different way of communicating planned work vs. "production-ready" work.

Let me know if I can help! I'm even open to a PR if y'all can point me to the right spot 👀

**Comment by gimenete** [comment]
I've seen that you have already created a branch! https://github.com/integrations/slack/compare/master...gray-draft-prs That should be it, right? Feel free to open a PR and thanks for this!
