### ISSUE TITLE
Close markdown block when a large file unfurl is truncated

### ISSUE THREAD

**Issue by PranayAgarwal** [integrations/slack#812]
If a user links to a large source file, the unfurled file text will automatically be truncated after a certain limit (not sure if this happens on the Slack or Github side). The markdown tag for closing the code block, however, is truncated as well. So you end up with an unformatted block of text with starting ``` characters only.

If a file is too large to fit in a Slack unfurl, ``` should still be placed at the end.

**Comment by wilhelmklopp** [comment]
Thanks for reporting this @PranayAgarwal ✨ 

I believe the truncating happens on the Slack side and that's why the closing backticks are omitted.

> If a file is too large to fit in a Slack unfurl, ``` should still be placed at the end.

Agreed. Do you know what the limit of "too large" is on the Slack side? ❤️

**Comment by PranayAgarwal** [comment]
We truncate attachment text at 8000 (UTF-8) characters.

**Comment by sanpaudel** [comment]
A bit late to the party but is the 8000 (UTF-8) characters limit documented somewhere?
