### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by ivirshup** [integrations/slack#836]
Hi! I'm having some trouble linking accounts with the `\github signin` command. I get to a page with a "Connect GitHub account" button, but that leads me to a page that says:

> An unexpected error occured: {some long token}

Where `{some long token}` is a long token, like `cb881ee9f31840089d0e072816346e1d`. Any idea what's up?

Thanks!

**Comment by ivirshup** [comment]
Tried it again using a different link, and it worked!

**Comment by AireshBhat** [comment]
I'm having the same issue. Have tried 8 different links so far(8 different times). Keep getting the same error all the time.

**Comment by scepticulous** [comment]
Hi :wave:,
thanks for bringing this up.

I suggest [getting in touch with the GitHub Support](https://github.com/contact?form%5Bsubject%5D=Re:+GitHub%2BSlack+Integration).
They will be able to offer better and further assistance.

When contacting them, please provide as much detail as possible about:
* The repo, especially if it is private
* The Slack instance: workspace, channel, etc
* Any other details about the command you tried, the errors, tokens, requests, date/time, etc

And everything else, that might be helpful for their investigation.

**Comment by AireshBhat** [comment]
Hey. Thanks for the swift reply. Will definitely contact them.

**Comment by mvaragnat** [comment]
@AireshBhat have you been able to resolve your issue ? Same problem trying to log in "An unexpected error occured"

**Comment by smart-campus** [comment]
Hey @mvaragnat, I was told to create a private channel and use the GitHub app. They told me that they will look into the issue.

**Comment by AireshBhat** [comment]
Hey @mvaragnat, I was told to create a private channel and use the GitHub app. They told me that they will look into the issue.

**Comment by jsrozner** [comment]
I ran into this same error (private slack channel, private repo). 

First run of /github subscribe <repo> told me to add github
Clicking launch github gave "An unexpected error occurred. ref: <long key>"
Rerunning /github subscrive <repo> resulted in success

So just some weird state maybe. Seems that rerunning can fix.

**Comment by m8ow** [comment]
I faced same error.
I uninstalled Github App in Slack, and re-installing would solve this problem...
