### ISSUE TITLE
`/github subscribe awslabs/amazon-eks-ami` failed

### ISSUE THREAD

**Issue by chenrui333** [integrations/slack#838]
I have used github slack command for doing bunch of repos without any issues, but I found I could do not it for `/github subscribe awslabs/amazon-eks-ami`

Always return the error message ("Either the app isn't installed on your repository or the repository does not exist."), I tried in both public and private channels.

To provide extra data point, it does not work with `terraform-aws-modules/terraform-aws-eks` repo either. 

Thanks!

**Comment by scepticulous** [comment]
Hi @chenrui333 ,
it might be a silly question, but did you check whether the GitHub App for the Slack Integration is installed on those repositories? If not, could you please check?

You cannot subscribe to a repo without the app being installed. This is also true for public repositories/public content.

**Comment by chenrui333** [comment]
@scepticulous I think that is public repo, belongs to somebody else?

**Comment by scepticulous** [comment]
Yes, it seems to be public and the app is not installed. 

Your intention here seems to be subscribing to public repos from orgs, you are not part of. 
This is currently not supported by this integration.
I hope this answers your question.

**Comment by chenrui333** [comment]
yeah, it does. Thanks for clarifying it!

**Comment by chenrui333** [comment]
Closing the issue now. :)
