### ISSUE TITLE
[Feature Request] Notification Subscription Aliases?

### ISSUE THREAD

**Issue by dcmbrown** [integrations/slack#842]
This idea doesn't appear to have been rejected already but let me know. We're an organization which likes seeing everything which passes through GitHub. I'm sure there are others like us so having aliases for certain notification subscription groups seems like a decent idea.  I just did the following subscription command to subscribe to a repo for example:

`/github subscribe TMIOrg/one-of-many-repos issues,pulls,statuses,commits,deployments,public,releases,reviews,comments,branches,commits:all`

Could this not be turned into a command like

`/github subscribe TMIOrg/one-of-many-repos all`

Alternatively it could be `everything` and people would also just get standard notifications if they used nothing as it currently is or `standard` if they wanted their Slack history to be explicit.

I see this repo is currently in a non-development Security review period so I may simply submit a PR change unless someone pipes up and says "We've rejected this idea previously. It's just dumb." Or "See linkX"

I am not suggesting giving the app the ability to make custom aliases, just grouping certain notifications into an alias.

**Comment by scepticulous** [comment]
Like the idea of giving the current "default" a name like `default` or `standard` and also a way to peek into what default means.
Subscribing to `all` or `everything` seems related to #374.
