### ISSUE TITLE
Breaking with screenshots as comment

### ISSUE THREAD

**Issue by shashanoid** [integrations/slack#850]
App doesn't show any description of the pull request whatsoever if I upload window sized screenshots from my macbook pro.

<img width="681" alt="Screen Shot 2019-05-23 at 5 08 55 PM" src="https://user-images.githubusercontent.com/5573677/58294166-76dba180-7d7d-11e9-8ac4-69f4587fb3cd.png">

**Comment by clapinton** [comment]
Just saw this last Friday, May 22nd, so it's still happening.
