### ISSUE TITLE
/github deploy

### ISSUE THREAD

**Issue by torbjornvatn** [integrations/slack#860]
We're eagerly awaiting the changes in https://github.com/integrations/slack/pull/698 as our current `hubot-deploy` + `heaven` setup is starting to cause us headaches.

Any news on when we can expect it to be turned on in the integration @gimenete ?

**Comment by IAmHughes** [comment]
Hey @torbjornvatn, just wanted to let you know that the `/github deploy` feature is now live! You can read about it [on the GitHub Blog](https://github.blog/2019-07-29-whats-new-in-the-github-and-slack-integration/). The key thing to note is that this required some updated permissions on the application, so the owner of any repositories that have the GitHub Slack App installed will need to accept those permissions. If you try to use the command without the permissions, you'll be prompted to update them ❤️.

Thanks for your patience on this!
