### ISSUE TITLE
How do I get subscribe to listen to "checks" in a PR?

### ISSUE THREAD

**Issue by mastoj** [integrations/slack#862]
We are moving more and more things over to github action, and one thing we want to have then is a notification in slack whenever a build finishes, either success or fail. 

I thought subscribing to the `statuses` would be enough, but nothing is published to the slack channel when a check finishes or fails.

Have I misunderstood the use of `/github subscribe owner/respository statuses`?

**Comment by mastoj** [comment]
Reading here I start to believe that maybe I need to post to the statuses api myself: https://developer.github.com/v3/repos/statuses/, is that correct?

**Comment by mastoj** [comment]
So `statuses` and `checks` are different I realized, but I still can't get it working. I do manage to post `statuses` updates to github using the api (which I verify worked through the api).

I have tried to subscribe to statuses by running the following:

    /github subscribe list <owner>/<repo> statuses 

But nothing is updated when I do `POST` a status update.

**Comment by IAmHughes** [comment]
Hey @mastoj , just wanted to let you know that the integration now supports displaying checks in the PR messaging you see in Slack. You can read about the changes we shipped today [on the GitHub Blog](https://github.blog/2019-07-29-whats-new-in-the-github-and-slack-integration/). 

The key thing to note is that this required some updated permissions on the application, so the owner of any repositories that have the GitHub Slack App installed will need to accept those permissions. If you try to use the command without the permissions, you'll be prompted to update them ❤️.

Thanks for your patience on this!

**Comment by villesau** [comment]
@IAmHughes is the feature deprecated? I'm not able to subscribe to check statuses in Slack.

<img width="731" alt="Screenshot 2022-08-09 at 15 28 34" src="https://user-images.githubusercontent.com/2647016/183646898-d1f016c9-65f1-4402-857a-f9a844ed968f.png">

**Comment by david-wolgemuth** [comment]
> Uh oh! `statuses` is not a feature. Available features are:
> `issues`, `pulls`, `commits`, `releases`, `deployments`, `reviews`, `comments`, `branches`, `+label:"my label"`, `discussions`, `workflows`
