### ISSUE TITLE
Add DB indexes on unfurls table to improve debuggability

### ISSUE THREAD

**Issue by wilhelmklopp** [integrations/slack#869]
Errors with unfurls can be hard to debug at the moment, in part because the database table is quite large and because we don't have indexes on any of the columns that are often used for debugging, digging into a particular issue.

Add indexes 
- [ ]  chanelSlackId
- [ ]  slackWorkspaceId
- [ ] slackUserId
- [ ] githubRepoId

**Comment by IAmHughes** [comment]
I should be able to pick this up within the next week. Wouldn't mind pairing since it's touching the DB, but I think I'll take the lead on it 😄

**Comment by srinjoym** [comment]
Just opened up a PR to add the indexes in #936. Will post another update here once the migration is run 🎉

**Comment by philipbremer** [comment]
@tebriel to write up thoughts and close.

**Comment by tebriel** [comment]
Right now database query time doesn't seem to be our limiting factor. Adding these indexes doesn't seem like it's going to buy us anything, but would increase the database size and latency for inserts. I think we can close this for now and re-open/cherry-pick individual indices if we need them!
