### ISSUE TITLE
I can't sign in 

### ISSUE THREAD

**Issue by geverghe** [integrations/slack#884]
Running into the same issue as #836 - however, I am not able to get it working

**Comment by scepticulous** [comment]
Hi :wave:,
thanks for bringing this up.

I suggest [getting in touch with the GitHub Support](https://github.com/contact?form%5Bsubject%5D=Re:+GitHub%2BSlack+Integration).
They will be able to offer better and further assistance.

When contacting them, please provide as much detail as possible about:
* The repo, especially if it is private
* The Slack instance: workspace, channel, etc
* Any other details about the command you tried, the errors, tokens, requests, date/time, etc

And everything else, that might be helpful for their investigation.
