### ISSUE TITLE
Cannot connect Slack to Private Repo

### ISSUE THREAD

**Issue by lbussy** [integrations/slack#964]
I have seen a few issues posted which greatly describe this issue.  Some say they were fixed and some just end.   I have a private repository to which I would like to connect Slack.  When I issue the command `/github signin` I get the indicator to connect via OAuth:

![OAuth Prompt](https://www.brewbubbles.com/wp-content/uploads/2019/11/OAuth.png)

I do so and hit the right page I assume:

![OAuth Connect](https://www.brewbubbles.com/wp-content/uploads/2019/11/Connect.png)

When I press the "Connect to GitHub account" button (I am already signed in) I get the following error on an otherwise blank page:

```
An unexpected error occured. ref: d0afd718fd6b415c960501d43006d513
```

Aside from the typo, I'm obviously not getting anything that tells me what's going wrong.  OAuth seems pretty straightforward so I'm not sure what I could be doing.

**Comment by 4k1k0** [comment]
Same for me. I have already connected two private repos in one slack channel, but when I try to connect another private repo to another channel I can't. 

![Screenshot_20191205_174629](https://user-images.githubusercontent.com/3821782/70283605-6920c300-1787-11ea-9298-f3a9606dc5ff.png)

**Comment by lbussy** [comment]
I had an email thread going with GitHub support and I got this resolved,  In my case, I issued the command `/github signin` which succeeded and then I was able to `/github subscribe owner/repository`.

**Comment by gcase555** [comment]
just FYI this no longer works since `/github signin` is not a command anymore
