### ISSUE TITLE
Subscribe to label does not accept special characters in label

### ISSUE THREAD

**Issue by lptr** [integrations/slack#983]
We use the `@` character as a prefix for team labels at https://github.com/gradle/gradle. It is currently not possible to subscribe to these labels via the Slack command:

`/github subscribe gradle/native-platform +label:@build-cache`

> `+label:@build-cache` is not a valid argument.

**Comment by tebriel** [comment]
Looks like the bug is here: https://github.com/integrations/slack/blob/master/lib/settings-helper.js#L7-L26
I'll see what I can do about getting a fix out in the next week.

**Comment by tebriel** [comment]
@lptr fixed in our internal fork, I'll try to backport it here this week. Can you verify that you're good now? Re-open and tag me if not!

**Comment by lptr** [comment]
Thanks @tebriel, I just had a chance to test, and it works!
