### ISSUE TITLE
[Bug] Automatically subscribed to wrong repository in organisation

### ISSUE THREAD

**Issue by alexanderkogan** [integrations/slack#994]
I subscribed to an organisation with the Slack command /github subscribe org and chose several repositories (for example with the prefix one_) in the configuration dialogue reachable from here: https://github.com/apps/slack/
But somehow a repository (for example the repository not_mine) got selected which I didn't select myself. It shows pull requests and comments for that repository in our channel even though we don't want it there.
org/not_mine is also not shown in the list of selected repositories on the configuration page. The information text "Selected 7 repositories." always shows one more repository than selected even if I unselect all repositories - it shows "Selected 1 repository."
In the selection dialogue the label "Installed" is shown for org/not_mine. Other repositories (for example other repositories with the not_ prefix) show "request". Maybe that is an indication, what is wrong, but I don't know how these labels get added.
If I explicitly select the repository org/not_mine, it is also not shown in the list of selected repositories.

Please ask if I can provide any more help.

**Comment by zmoazeni** [comment]
Hi @alexanderkogan! Would you mind submitting a support ticket? I'd like to get some more information about how you set this up and ran into this scenario so that we can reproduce on our side!

**Comment by alexanderkogan** [comment]
Support Ticket: https://enterprise.githubsupport.com/hc/requests/571936
