### ISSUE TITLE
subscribe does not show branches commit

### ISSUE THREAD

**Issue by vkuehn** [integrations/slack#997]
when subscribed to a  repo to does not show anything when commits are done to a none master branch. is that expected ?

**Comment by haakonnessjoen** [comment]
I have the same problem, and can't find any configuration option to add all branches? When I subscribed to an entire organization, I expected all pushes to be notified.

**Comment by haakonnessjoen** [comment]
I just found the documentation for this.

You need to add commits:all as a flag to the /github subscribe command

I think this issue can be closed :)

**Comment by vkuehn** [comment]
Thanks for that. Not sure if that could be mentioned in the main documentation. However closing that

**Comment by xtealer** [comment]
> I just found the documentation for this.
> 
> You need to add commits:all as a flag to the /github subscribe command
> 
> I think this issue can be closed :)

Having the same issue, tried your solutions and still does not work. Only pull requests are shown but no new commits.

**Comment by jesussteve** [comment]
We are also having this issue now across our slack organisations

It was working previously 

The `commits:all`  flag was re-run but commits are not showing - PRs, issue changes etc still working?
