### ISSUE TITLE
Subscriptions disappear in my most important channel

### ISSUE THREAD

**Issue by fitzyjoe** [integrations/slack#998]
When I subscribe to a repo in a new public or private channel, I receive notifications just fine.  However, if I subscribe to a repo in a certain channel ("dev") the subscription succeeds, I can list the subscription, but it doesn't notify me... and in a short while later when I try to list the subscription again - it is gone.  This particular channel is the main channel that our developers use and it has been around for maybe 5 years.

I have tried subscribing to all repos for my account and subscribing to a specific repo.  Same result.

I just submitted a debug message:
Debug information
```
{
  "team_id": "T046ULW56",
  "team_domain": "teslagovernment",
  "user_id": "U047K4U6D",
  "channel_id": "C4LPVJHEE",
  "channel_name": "dev",
  "text": "debug after I subscribe to a repo in this channel, my subscription is soon lost.  Other channels work properly, but this is my main dev channel... was created probably 5 years ago."
}
```

I noticed another issue reported relating to channels that have changed from public/private.  I don't know the history of this channel, but my symptom is not exactly the same... because I'm able to successfully subscribe.

**Comment by 4k1k0** [comment]
Same for me, I've struggling with the same issue for a few months now.
